"""Шаблони колекцій: архетип fine_art. Збираються в templates.COLLECTION_TEMPLATES
(через collection_templates.__init__._assemble). НЕ змінюй порядок тут — порядок
дропдауна задає ORDER у __init__.py. Нові шаблони: додай сюди + у ORDER.
"""

TEMPLATES: dict[str, dict] = {'1/1 Fine Art': {'label': '🎨 1/1 Fine Art',
                  'archetype': 'fine_art',
                  'description': "Один унікальний арт-об'єкт: олійний живопис, сюрреалізм або "
                                 'концепт-арт преміум-класу. 1/1 — Конвеєр → режим Сингл.',
                  'description_en': 'A single premium art piece: oil painting, surrealism or '
                                    'concept art. 1/1 — Pipeline → Single mode.',
                  'idea': 'surreal creature from cosmic mythology',
                  'style': 'Oil Painting / Classical Art (Класичний живопис, текстурні мазки)',
                  'camera': 'Full Body Shot (Персонаж у повний зріст)',
                  'lighting': 'Volumetric / God Rays (Драматичні промені світла крізь туман)',
                  'background': 'Cosmic Nebula & Deep Space (Космічна туманність, зірки)',
                  'quality': 'Masterpiece Epic Concept Art (Рівень концепт-артів ААА-ігор)',
                  'mood': 'Epic & Heroic',
                  'aspect_ratio': '16:9 (Пейзаж)',
                  'stylize': 500,
                  'chaos': 30,
                  'collection_size': 1,
                  'traits': {'Голова / Шолом / Маска': ['crown of stars',
                                                        'mythical god mask',
                                                        'halo of light',
                                                        'demon horns'],
                             'Очі / Окуляри': ['cosmic glow',
                                               'eyes closed in meditation',
                                               'double pupils',
                                               'fiery eyes'],
                             'Одяг / Броня': ['nebula cape',
                                              'gold armor',
                                              'oracle robes',
                                              'energy cloak'],
                             'Аксесуари / Зброя': ['cosmic staff',
                                                   'power crystal',
                                                   'sphere of fate',
                                                   'wings of light'],
                             'Фон / Аура': ['orion nebula',
                                            'black hole',
                                            'meteor shower',
                                            'aurora of the gods'],
                             'Емоція / Вираз обличчя': ['transcendence',
                                                        'courage',
                                                        'wisdom',
                                                        'mystery']}},
 'Sumi-e Ink Studies': {'label': '🖋️ Sumi-e Ink Studies',
                        'archetype': 'fine_art',
                        'description': 'Монохромна туш / sumi-e: 5 мотивів × 5 настроїв = 25. '
                                       'Міні-дроп fine-art без PFP.',
                        'description_en': 'Monochrome ink / sumi-e: 5 motifs × 5 moods = 25. '
                                          'Fine-art mini drop without PFP.',
                        'idea': 'zen ink wash study without characters',
                        'style': 'Ink Wash / Sumi-e (monochrome brushwork, rice paper)',
                        'camera': 'Wide Establishing Shot',
                        'lighting': "Soft Studio Light (М'яке студійне світло, пастельні тони)",
                        'background': 'Solid Minimalist Color (Однотонний яскравий NFT-фон)',
                        'quality': 'Vintage / Textured Matte (Ефект старої плівки або матового '
                                   'паперу)',
                        'mood': 'Serene & Meditative',
                        'aspect_ratio': '1:1 (Квадрат для NFT)',
                        'stylize': 280,
                        'chaos': 18,
                        'collection_size': 25,
                        'traits': {'Форма / Силует': ['bamboo grove silhouette',
                                                      'crane in flight stroke',
                                                      'mountain peak minimal line',
                                                      'enso circle meditation',
                                                      'koi fish ripple pattern'],
                                   'Фон / Поле': ['empty rice paper white',
                                                  'soft gray ink wash',
                                                  'misty gradient fade',
                                                  'subtle gold leaf accent',
                                                  'deep black ink void']}}}
