"""i18n-рядки: домен admin (адмін-панель / ops / провайдери / калькулятор).

Збираються в `ui_strings._STRINGS` через `ui_strings._merge_strings()`. НЕ імпортуй
цей модуль у застосунку — використовуй `ui_strings.t()`. Парність uk↔en, плейсхолдери
й повноту ключів звіряє `tests/test_ui_strings.py` проти зібраного `_STRINGS`.
"""

STRINGS: dict[str, dict[str, str]] = {
    'adm.title': {'uk': '🛠 Адмін', 'en': '🛠 Admin'},
    'adm.tab.overview': {'uk': 'Огляд', 'en': 'Overview'},
    'adm.tab.economics': {'uk': 'Економіка', 'en': 'Economics'},
    'adm.tab.users': {'uk': 'Користувачі', 'en': 'Users'},
    'adm.tab.ops': {'uk': 'Ops', 'en': 'Ops'},
    'adm.tab.providers': {'uk': 'Провайдери', 'en': 'Providers'},
    'adm.ov.wallets': {'uk': 'Гаманців', 'en': 'Wallets'},
    'adm.ov.wallets_help': {'uk': 'Усього зареєстрованих гаманців', 'en': 'Total registered wallets'},
    'adm.ov.verified': {'uk': 'Підтверджених', 'en': 'Verified'},
    'adm.ov.verified_help': {'uk': 'Пройшли вхід підписом', 'en': 'Signed in with a signature'},
    'adm.ov.revenue': {'uk': 'Дохід', 'en': 'Revenue'},
    'adm.ov.revenue_help': {'uk': '{count} оплат', 'en': '{count} payments'},
    'adm.ov.outstanding': {'uk': 'Кредитів в обігу', 'en': 'Credits outstanding'},
    'adm.ov.outstanding_help': {'uk': "Невитрачені кредити = зобов'язання перед користувачами", 'en': 'Unspent credits = liability to users'},
    'adm.ov.sold_caption': {'uk': 'Продано кредитів: {sold} · нових гаманців за 7 днів: {n7} · за 30: {n30}', 'en': 'Credits sold: {sold} · new wallets in 7 days: {n7} · in 30: {n30}'},
    'adm.ov.external_caption': {'uk': 'Джерело оплат: зовнішні ${rev} ({count}) · свої ${internal}. Усі оплати офіційні й входять у дохід — розділ показує лише джерело.', 'en': 'Payment source: external ${rev} ({count}) · own ${internal}. All payments are real and counted in revenue — this only shows the source.'},
    'adm.period.label': {'uk': 'Період (Економіка та Користувачі)', 'en': 'Period (Economics & Users)'},
    'adm.period.7d': {'uk': '7 днів', 'en': '7 days'},
    'adm.period.30d': {'uk': '30 днів', 'en': '30 days'},
    'adm.period.all': {'uk': 'Увесь час', 'en': 'All time'},
    'adm.period.help': {'uk': 'Маржа, ARPU, воронка та таблиця двигунів рахуються за обраним вікном (created_at).', 'en': 'Margin, ARPU, funnel and engine table are computed over the selected window (created_at).'},
    'adm.econ.margin_help': {'uk': 'Оцінка: списані cr × середня ціна продажу мінус орієнтовна API-собівартість (див. services/margin_report.py). Не замінює інвойси провайдерів.', 'en': 'Estimate: debited cr × avg sale price minus approximate API cost (see services/margin_report.py). Does not replace provider invoices.'},
    'adm.econ.est_api': {'uk': 'Оцінка API $', 'en': 'Estimated API $'},
    'adm.econ.est_api_help': {'uk': 'Сума count×$/op по debit за двигуном', 'en': 'Sum of count×$/op over debits per engine'},
    'adm.econ.actual_api': {'uk': 'Факт API $', 'en': 'Actual API $'},
    'adm.econ.delta_vs_est': {'uk': '{delta:+.2f} vs оцінка', 'en': '{delta:+.2f} vs estimate'},
    'adm.econ.actual_api_help': {'uk': 'Імпорт з кабінетів / OpenAI Costs API (provider_spend.db); delta = факт − оцінка', 'en': 'Import from dashboards / OpenAI Costs API (provider_spend.db); delta = actual − estimate'},
    'adm.econ.margin_est': {'uk': 'Маржа (оцінка)', 'en': 'Margin (estimate)'},
    'adm.econ.margin_actual': {'uk': 'Маржа (факт)', 'en': 'Margin (actual)'},
    'adm.econ.margin_actual_help': {'uk': 'Якщо є імпорти витрат за період', 'en': 'If cost imports exist for the period'},
    'adm.econ.util_help': {'uk': 'Списано / усі продані кредити (all-time)', 'en': 'Spent / all credits sold (all-time)'},
    'adm.econ.stab_help': {'uk': 'Частка Stability серед списаних кредитів; >40% — ризик маржі', 'en': 'Stability share of debited credits; >40% — margin risk'},
    'adm.econ.arpu_caption': {'uk': 'ARPU: {arpu} ({count} оплат за період) · avg ${avg}/cr · welcome за період: {welcome} cr', 'en': 'ARPU: {arpu} ({count} payments in period) · avg ${avg}/cr · welcome in period: {welcome} cr'},
    'adm.econ.import_by_provider': {'uk': 'Імпорт за провайдерами: ', 'en': 'Imports by provider: '},
    'adm.econ.stab_warn': {'uk': 'Висока частка Stability ({stab}% debit) — перевірте ціну кредита або мікс двигунів (ПЛАН_БІЗНЕС B2.5).', 'en': 'High Stability share ({stab}% debit) — review credit price or engine mix (ПЛАН_БІЗНЕС B2.5).'},
    'adm.econ.net_title': {'uk': '**Чиста маржа** — валова мінус комісії, обмін крипти, фікс-кости', 'en': '**Net margin** — gross minus fees, crypto exchange, fixed costs'},
    'adm.econ.net_profit': {'uk': 'Чистий прибуток', 'en': 'Net profit'},
    'adm.econ.net_profit_help': {'uk': 'Дохід − API − комісія Helio − обмін USDC→фіат − фікс (за період)', 'en': 'Revenue − API − Helio fee − USDC→fiat exchange − fixed (per period)'},
    'adm.econ.net_margin': {'uk': 'Чиста маржа', 'en': 'Net margin'},
    'adm.econ.net_margin_help': {'uk': "net_profit / дохід; від'ємна, якщо фікс-кости перевищують виторг", 'en': 'net_profit / revenue; negative if fixed costs exceed earnings'},
    'adm.econ.fixed_period': {'uk': 'Фікс за період', 'en': 'Fixed per period'},
    'adm.econ.fixed_period_help': {'uk': '${monthly}/міс × {days}д ÷ 30', 'en': '${monthly}/mo × {days}d ÷ 30'},
    'adm.econ.net_caption': {'uk': 'Дохід ${rev} − API ${api} − Helio {fee_pct}% (${fee}) − обмін {fx_pct}% (${fx}) − фікс ${fixed} = ${net}. Ставки/фікс — env PAYMENT_FEE_PCT · FX_FEE_PCT · FIXED_MONTHLY_USD.', 'en': 'Revenue ${rev} − API ${api} − Helio {fee_pct}% (${fee}) − exchange {fx_pct}% (${fx}) − fixed ${fixed} = ${net}. Rates/fixed — env PAYMENT_FEE_PCT · FX_FEE_PCT · FIXED_MONTHLY_USD.'},
    'adm.econ.be_title': {'uk': '**Беззбитковість** — скільки оплат «Start» на місяць покриває фікс-кост', 'en': '**Break-even** — how many «Start» payments per month cover the fixed cost'},
    'adm.econ.be_need': {'uk': 'Треба Start/міс', 'en': 'Start needed/mo'},
    'adm.econ.be_need_help': {'uk': 'ceil(фікс ${fixed} ÷ внесок ${contrib})', 'en': 'ceil(fixed ${fixed} ÷ contribution ${contrib})'},
    'adm.econ.be_this_month': {'uk': 'Цього місяця', 'en': 'This month'},
    'adm.econ.be_this_month_help': {'uk': 'оплат із початку календарного місяця (${rev})', 'en': 'payments since start of calendar month (${rev})'},
    'adm.econ.be_remaining': {'uk': 'Бракує', 'en': 'Remaining'},
    'adm.econ.be_remaining_help': {'uk': 'ще Start-оплат до беззбитковості цього місяця', 'en': 'more Start payments to break even this month'},
    'adm.econ.be_progress': {'uk': '{pct}% покрито ({have}/{need})', 'en': '{pct}% covered ({have}/{need})'},
    'adm.econ.be_caption': {'uk': 'Внесок Start ${contrib} (ціна ${price} − API ${api} − Helio/FX). Creator/Pro закривають швидше (вищий внесок). Поріг — від FIXED_MONTHLY_USD.', 'en': 'Start contribution ${contrib} (price ${price} − API ${api} − Helio/FX). Creator/Pro close faster (higher contribution). Threshold — from FIXED_MONTHLY_USD.'},
    'adm.econ.be_zero': {'uk': 'Беззбитковість: фікс-кост $0 (self-host) — задайте FIXED_MONTHLY_USD для порогу.', 'en': 'Break-even: fixed cost $0 (self-host) — set FIXED_MONTHLY_USD for a threshold.'},
    'adm.econ.by_engine_title': {'uk': '**Генерації за двигуном** ({period}, списано кредитів)', 'en': '**Generations by engine** ({period}, credits debited)'},
    'adm.econ.no_debits': {'uk': 'Списань за цей період не було.', 'en': 'No debits for this period.'},
    'adm.econ.credits_by_kind': {'uk': '**Кредити за видом**', 'en': '**Credits by kind**'},
    'adm.econ.no_tx': {'uk': 'Транзакцій немає.', 'en': 'No transactions.'},
    'adm.econ.top_wallets': {'uk': '**Топ-гаманці за витратами**', 'en': '**Top wallets by spend**'},
    'adm.econ.no_spend': {'uk': 'Витрат ще не було.', 'en': 'No spend yet.'},
    'adm.econ.float_title': {'uk': '**Провайдерський флоат** — рекомендований мінімум vs баланс', 'en': '**Provider float** — recommended minimum vs balance'},
    'adm.econ.float_caption': {'uk': 'Прямий баланс лише в Stability; інші — postpaid (баланс у кабінеті, вкладка «Провайдери»). Оплата йде попереду витрати → флоат це обіговий буфер, не «згоряє». 🔴 нижче порогу алерту · 🟡 нижче рекомендованого · 🟢 ок.', 'en': "Direct balance only for Stability; others are postpaid (balance in dashboard, «Providers» tab). Payment precedes spend → float is a working buffer, it doesn't «burn». 🔴 below alert threshold · 🟡 below recommended · 🟢 ok."},
    'adm.spend.expander': {'uk': '📥 Імпорт фактичних витрат API (для маржі-факт)', 'en': '📥 Import actual API spend (for actual margin)'},
    'adm.spend.caption': {'uk': 'CSV з кабінету провайдера (OpenAI/Replicate/Anthropic/Stability) або кнопка OpenAI Costs. Записи — UPSERT за (провайдер, період, джерело), повторний імпорт не дублює.', 'en': "CSV from a provider dashboard (OpenAI/Replicate/Anthropic/Stability) or the OpenAI Costs button. Records UPSERT by (provider, period, source), re-import doesn't duplicate."},
    'adm.spend.uploader': {'uk': 'CSV-файл витрат', 'en': 'Spend CSV file'},
    'adm.spend.imported_ok': {'uk': 'Імпортовано {saved} рядків ({rows} розпізнано).', 'en': 'Imported {saved} rows ({rows} recognized).'},
    'adm.spend.imported_none': {'uk': 'Не розпізнано жодного рядка з сумою — перевірте формат CSV.', 'en': 'No rows with an amount recognized — check the CSV format.'},
    'adm.spend.import_err': {'uk': 'Помилка імпорту: {err}', 'en': 'Import error: {err}'},
    'adm.spend.already': {'uk': 'Цей файл уже імпортовано в цій сесії.', 'en': 'This file was already imported in this session.'},
    'adm.spend.fetch_openai': {'uk': '⬇️ Завантажити OpenAI Costs (30д)', 'en': '⬇️ Fetch OpenAI Costs (30d)'},
    'adm.spend.openai_err': {'uk': 'OpenAI Costs: {err}', 'en': 'OpenAI Costs: {err}'},
    'adm.spend.openai_ok': {'uk': 'Завантажено {saved} денних записів OpenAI.', 'en': 'Fetched {saved} daily OpenAI records.'},
    'adm.spend.openai_none': {'uk': 'Витрат за період немає або вже імпортовано.', 'en': 'No spend for the period, or already imported.'},
    'adm.spend.last': {'uk': 'Останній імпорт: {provider} ${amount} ({start}…{end}, {source}) · {at}', 'en': 'Last import: {provider} ${amount} ({start}…{end}, {source}) · {at}'},
    'adm.spend.last_none': {'uk': 'Імпортів витрат ще не було.', 'en': 'No spend imports yet.'},
    'adm.users.title': {'uk': '**Користувачі та воронка** ({period})', 'en': '**Users & funnel** ({period})'},
    'adm.users.new_verified': {'uk': 'Нові verified', 'en': 'New verified'},
    'adm.users.new_verified_help': {'uk': 'Пройшли вхід підписом за період', 'en': 'Signed in with a signature in the period'},
    'adm.users.paying': {'uk': 'Платники', 'en': 'Paying'},
    'adm.users.paying_help': {'uk': 'Унікальні гаманці з оплатою за період', 'en': 'Unique wallets with a payment in the period'},
    'adm.users.conv_pay': {'uk': 'Конверсія→оплата', 'en': 'Conversion→payment'},
    'adm.users.conv_pay_help': {'uk': 'Платники / нові verified за період', 'en': 'Paying / new verified in the period'},
    'adm.users.churn': {'uk': 'Churn-проксі', 'en': 'Churn proxy'},
    'adm.users.churn_help': {'uk': 'Verified >30 днів тому, які жодного разу не списували кредити', 'en': 'Verified >30 days ago who never debited any credits'},
    'adm.users.generators': {'uk': 'Генератори', 'en': 'Generators'},
    'adm.users.generators_help': {'uk': 'Гаманці з першим списанням (генерацією) за період', 'en': 'Wallets with a first debit (generation) in the period'},
    'adm.users.exporters': {'uk': 'Експортери', 'en': 'Exporters'},
    'adm.users.exporters_help': {'uk': 'Гаманці, що зібрали export-бандл за період', 'en': 'Wallets that built an export bundle in the period'},
    'adm.users.conv_export': {'uk': 'Конверсія ген→експорт', 'en': 'Conversion gen→export'},
    'adm.users.conv_export_help': {'uk': 'Експортери / генератори — чи доходять до термінальної події білдера', 'en': "Exporters / generators — whether they reach the builder's terminal event"},
    'adm.users.savers': {'uk': 'Зберегли в чергу', 'en': 'Saved to queue'},
    'adm.users.savers_help': {'uk': 'Унікальні гаманці з подією curator_save (збереження з куратора) у вікні.', 'en': 'Unique wallets with curator_save (curator save) in the window.'},
    'adm.users.conv_save': {'uk': 'Конверсія ген→save', 'en': 'Conversion gen→save'},
    'adm.users.conv_save_help': {'uk': 'Гаманці з curator_save / гаманці з першим debit у вікні.', 'en': 'Wallets with curator_save / wallets with first debit in the window.'},
    'adm.users.conv_save_export': {'uk': 'Конверсія save→експорт', 'en': 'Conversion save→export'},
    'adm.users.conv_save_export_help': {'uk': 'Гаманці з export / гаманці з curator_save у вікні.', 'en': 'Wallets with export / wallets with curator_save in the window.'},
    'adm.quality.title': {'uk': '**Якість конвеєра**', 'en': '**Pipeline quality**'},
    'adm.quality.avg_rating': {'uk': 'Сер. рейтинг куратора', 'en': 'Avg curator rating'},
    'adm.quality.avg_rating_help': {'uk': 'Зважене середнє з payload curator_save (лише оцінені зображення).', 'en': 'Weighted average from curator_save payloads (rated images only).'},
    'adm.quality.items_saved': {'uk': 'Збережено активів', 'en': 'Items saved'},
    'adm.quality.items_saved_help': {'uk': 'Сума items у всіх curator_save подіях за вікно.', 'en': 'Sum of items across all curator_save events in the window.'},
    'adm.quality.top_engine': {'uk': 'Топ-двигун (save)', 'en': 'Top engine (save)'},
    'adm.quality.top_engine_help': {'uk': 'Двигун із найбільшою кількістю збережених активів за вікно.', 'en': 'Engine with the most saved assets in the window.'},
    'adm.quality.save_events': {'uk': 'Події save', 'en': 'Save events'},
    'adm.quality.save_events_help': {'uk': 'Кількість curator_save подій (кожне натискання «Зберегти»).', 'en': 'Number of curator_save events (each Save click).'},
    'adm.quality.regen_rate': {'uk': 'Regenerate / generate', 'en': 'Regenerate / generate'},
    'adm.quality.regen_rate_help': {'uk': 'Події regenerate ÷ події generate за вікно (не унікальні кадри).', 'en': 'Regenerate events ÷ generate events in the window (not unique frames).'},
    'adm.quality.save_clean': {'uk': 'Save без regenerate', 'en': 'Save w/o regenerate'},
    'adm.quality.save_clean_help': {'uk': '% save після generate без regenerate між ними (на гаманець).', 'en': '% saves after generate with no regenerate in between (per wallet).'},
    'adm.quality.median_export': {'uk': 'Медіана до export', 'en': 'Median to export'},
    'adm.quality.median_export_help': {'uk': 'Медіана хвилин від першого generate до першого export на гаманець.', 'en': 'Median minutes from first generate to first export per wallet.'},
    'adm.quality.classic_share': {'uk': 'Classic-частка', 'en': 'Classic share'},
    'adm.quality.classic_share_help': {'uk': 'Частка зображень із classic-вкладок (Images/Collection) серед генерацій з відомим джерелом. Поріг §2.8 для E7 Classic merge — >15%.', 'en': 'Share of images from classic tabs (Images/Collection) among generations with known source. §2.8 threshold for E7 Classic merge — >15%.'},
    'adm.quality.style_bible_share': {'uk': 'Style Bible-частка', 'en': 'Style Bible share'},
    'adm.quality.style_bible_share_help': {'uk': 'Частка генерацій з активною Style Bible. Сигнал попиту на PFP-consistency; поріг §2.8 для E6 img2img — >20%.', 'en': 'Share of generations with an active Style Bible. Demand signal for PFP-consistency; §2.8 threshold for E6 img2img — >20%.'},
    'adm.quality.gen_source_split': {'uk': 'Classic / Pipeline', 'en': 'Classic / Pipeline'},
    'adm.quality.gen_source_split_help': {'uk': 'Кількість згенерованих зображень за джерелом (classic / pipeline) у вікні.', 'en': 'Generated image count by source (classic / pipeline) in the window.'},
    'adm.quality.gen_untracked': {'uk': '{n} генерацій без мітки джерела (legacy-події до інструментації §2.8) — не входять у частки.', 'en': '{n} generations without a source tag (legacy events before §2.8 instrumentation) — excluded from shares.'},
    'adm.quality.alerts_ok': {'uk': 'Пороги якості за {days} днів у нормі (QUALITY_ALERT_*).', 'en': 'Quality thresholds OK for the last {days} days (QUALITY_ALERT_*).'},
    'adm.quality.alert.low_rating': {'uk': '⚠️ Сер. рейтинг куратора **{avg:.2f}** нижче порогу **{threshold:.1f}**.', 'en': '⚠️ Avg curator rating **{avg:.2f}** is below threshold **{threshold:.1f}**.'},
    'adm.quality.alert.low_save_export': {'uk': '⚠️ Конверсія save→export **{pct:.1f}%** нижче порогу **{threshold:.0f}%**.', 'en': '⚠️ Save→export conversion **{pct:.1f}%** is below threshold **{threshold:.0f}%**.'},
    'adm.users.pkgs_title': {'uk': '**Оплати за пакетами**', 'en': '**Payments by package**'},
    'adm.users.no_pay': {'uk': 'Оплат ще не було.', 'en': 'No payments yet.'},
    'adm.users.recent_title': {'uk': '**Останні оплати**', 'en': '**Recent payments**'},
    'adm.users.sybil_warn': {'uk': '⚠️ Sybil-кандидати ({n}): гаманці зі списаннями >20 cr без жодної оплати', 'en': '⚠️ Sybil candidates ({n}): wallets with >20 cr debits and no payment'},
    'adm.users.sybil_none': {'uk': 'Sybil-кандидатів (списання >20 cr без оплат) немає.', 'en': 'No Sybil candidates (>20 cr debits without payment).'},
    'adm.ops.title': {'uk': '**Операційний стан стека**', 'en': '**Operational stack status**'},
    'adm.refresh': {'uk': '🔄 Оновити', 'en': '🔄 Refresh'},
    'adm.ops.checking': {'uk': 'Перевірка стека…', 'en': 'Checking stack…'},
    'adm.ops.reconcile': {'uk': 'Останнє звіряння Helio: {at}', 'en': 'Last Helio reconcile: {at}'},
    'adm.ops.reconcile_none': {'uk': 'Звіряння Helio ще не виконувалось (маркер data/last_reconcile.txt відсутній).', 'en': 'Helio reconcile has not run yet (marker data/last_reconcile.txt missing).'},
    'adm.ops.reconcile_suffix': {'uk': ' · деталі — ОПЕРАТОР.md §12', 'en': ' · details — ОПЕРАТОР.md §12'},
    'adm.ops.workspace_title': {'uk': '**Workspace на диску**', 'en': '**Workspace disk usage**'},
    'adm.ops.workspace_total_mb': {'uk': 'Усього MB', 'en': 'Total MB'},
    'adm.ops.workspace_wallets': {'uk': 'Гаманців', 'en': 'Wallets'},
    'adm.ops.workspace_limits': {'uk': 'Ліміти env', 'en': 'Env limits'},
    'adm.ops.workspace_unlimited': {'uk': 'без ліміту', 'en': 'unlimited'},
    'adm.ops.workspace_lim_projects': {'uk': '≤{n} проєктів', 'en': '≤{n} projects'},
    'adm.ops.workspace_lim_mb': {'uk': '≤{n} MB', 'en': '≤{n} MB'},
    'adm.ops.workspace_top_caption': {'uk': 'Топ гаманців за обʼємом (data/workspace/)', 'en': 'Top wallets by size (data/workspace/)'},
    'adm.ops.workspace_empty': {'uk': 'Workspace порожній або ще не створений.', 'en': 'Workspace is empty or not created yet.'},
    'adm.ops.mint_path_title': {'uk': '### Шлях мінту (7д)', 'en': '### Mint path intents (7d)'},
    'adm.ops.mint_path_total': {'uk': 'Intent-подій', 'en': 'Intent events'},
    'adm.ops.mint_path_window': {'uk': 'Вікно: {days} дн. · подія `export_intent_mint_path`', 'en': 'Window: {days}d · event `export_intent_mint_path`'},
    'adm.ops.mint_path_empty': {'uk': 'Ще немає виборів шляху в Export Center.', 'en': 'No mint-path choices in Export Center yet.'},
    'adm.ops.concierge_title': {'uk': '### Concierge-заявки', 'en': '### Concierge requests'},
    'adm.ops.concierge_empty': {'uk': 'Заявок ще немає.', 'en': 'No requests yet.'},
    'adm.prov.title': {'uk': '**Провайдери API — валідність ключів**', 'en': '**API providers — key validity**'},
    'adm.prov.caption': {'uk': 'Валідність ключа перевіряється автоматично (кеш ~5 хв). Прямий баланс через ключ дає лише Stability; для решти баланс/витрати — за посиланням у кабінеті.', 'en': 'Key validity is checked automatically (cache ~5 min). Direct balance via key is available only for Stability; for others see balance/spend via the dashboard link.'},
    'adm.prov.checking': {'uk': 'Перевірка ключів…', 'en': 'Checking keys…'},
    'adm.prov.st_unconfigured': {'uk': 'не налаштовано', 'en': 'not configured'},
    'adm.prov.st_no_probe': {'uk': 'налаштовано (без проби)', 'en': 'configured (no probe)'},
    'adm.prov.st_valid': {'uk': 'ключ валідний', 'en': 'key valid'},
    'adm.prov.st_invalid': {'uk': 'ключ недійсний', 'en': 'key invalid'},
    'adm.prov.st_unknown': {'uk': 'не вдалося перевірити (мережа)', 'en': 'could not verify (network)'},
    'adm.prov.balance': {'uk': ' · баланс: {bal:.1f} cr', 'en': ' · balance: {bal:.1f} cr'},
    'adm.prov.dashboard': {'uk': '↗ Кабінет', 'en': '↗ Dashboard'},
    'adm.prov.tg_title': {'uk': '**Сповіщення (Telegram)**', 'en': '**Notifications (Telegram)**'},
    'adm.prov.tg_on': {'uk': '✅ Telegram налаштовано · поріг низького балансу Stability: {threshold:.0f} cr (env STABILITY_LOW_BALANCE). Планові алерти/дайджест — завдання W3IR-Provider-Check / W3IR-Daily-Digest.', 'en': '✅ Telegram configured · Stability low-balance threshold: {threshold:.0f} cr (env STABILITY_LOW_BALANCE). Scheduled alerts/digest — tasks W3IR-Provider-Check / W3IR-Daily-Digest.'},
    'adm.prov.tg_test_btn': {'uk': '📨 Тест-сповіщення', 'en': '📨 Test notification'},
    'adm.prov.tg_test_msg': {'uk': '✅ Тест: сповіщення NFT Prompt Builder працюють.', 'en': '✅ Test: NFT Prompt Builder notifications work.'},
    'adm.prov.tg_sent': {'uk': 'Надіслано ✓', 'en': 'Sent ✓'},
    'adm.prov.tg_fail': {'uk': 'Не вдалося надіслати', 'en': 'Failed to send'},
    'adm.prov.tg_digest_btn': {'uk': '📊 Надіслати дайджест', 'en': '📊 Send digest'},
    'adm.prov.tg_digest_sent': {'uk': 'Дайджест надіслано ✓', 'en': 'Digest sent ✓'},
    'adm.prov.tg_off': {'uk': '⚠️ Telegram не налаштовано — задайте TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID у .env, щоб отримувати алерти про низький баланс і денний дайджест.', 'en': '⚠️ Telegram not configured — set TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID in .env to receive low-balance alerts and the daily digest.'},
    'ops.detail.url_only': {'uk': '{url}', 'en': '{url}'},
    'ops.detail.api': {'uk': '{url} (без нього — фолбек polling)', 'en': '{url} (without it — polling fallback)'},
    'ops.detail.siwe_enforced': {'uk': "{url} · гард увімкнено, API обов'язковий", 'en': '{url} · guard on, API required'},
    'ops.detail.empty': {'uk': '(порожньо)', 'en': '(empty)'},
    'ops.detail.value': {'uk': '{val}', 'en': '{val}'},
    'ops.detail.enforce_true': {'uk': "{val} — 'true' НЕ вмикає гард, лише '1'", 'en': "{val} — 'true' does NOT enable the guard, only '1'"},
    'ops.detail.sim_off': {'uk': 'вимкнено', 'en': 'disabled'},
    'ops.detail.sim_on': {'uk': '1 — імітація оплат (не для production!)', 'en': '1 — simulated payments (not for production!)'},
    'ops.detail.secret_missing': {'uk': 'не задано — вхід НЕМОЖЛИВИЙ при увімкненому гарді', 'en': 'not set — sign-in IMPOSSIBLE with the guard on'},
    'ops.detail.secret_test': {'uk': 'тестовий ключ зі smoke (НЕ для production)', 'en': 'test key from smoke (NOT for production)'},
    'ops.detail.set': {'uk': 'задано', 'en': 'set'},
    'ops.detail.sec_openai': {'uk': 'промти + зображення (критичний)', 'en': 'prompts + images (critical)'},
    'ops.detail.sec_helio_webhook': {'uk': 'перевірка підпису webhook оплат', 'en': 'payment webhook signature check'},
    'ops.detail.sec_helio_api': {'uk': 'звіряння оплат (polling/cron)', 'en': 'payment reconciliation (polling/cron)'},
    'prov.purpose.openai': {'uk': 'Промти (GPT-4o/4.1/o4) + зображення (gpt-image-1) + Image-to-Prompt (vision). Конструктор/Batch/Колекція, Етап 2 Конвеєра.', 'en': 'Prompts (GPT-4o/4.1/o4) + images (gpt-image-1) + Image-to-Prompt (vision). Constructor/Batch/Collection, Pipeline Stage 2.'},
    'prov.purpose.anthropic': {'uk': 'Claude-моделі (haiku/sonnet/opus) як альтернатива GPT для генерації промтів. Конструктор/Batch/Колекція.', 'en': 'Claude models (haiku/sonnet/opus) as a GPT alternative for prompt generation. Constructor/Batch/Collection.'},
    'prov.purpose.stability': {'uk': 'Двигун зображень Stable Image Core (Етап 2), бюджетний — 1 кредит/зображення. ai_service.', 'en': 'Stable Image Core image engine (Stage 2), budget — 1 credit/image. ai_service.'},
    'prov.purpose.replicate': {'uk': 'Двигун Flux.1 на Етапі 2 (REPLICATE_API_TOKEN). ai_service.', 'en': 'Flux.1 engine on Stage 2 (REPLICATE_API_TOKEN). ai_service.'},
    'prov.purpose.pinata': {'uk': 'Завантаження зображень і метаданих у IPFS (Етап 3 / експорт-бандл). ipfs, ipfs_storage.', 'en': 'Uploading images and metadata to IPFS (Stage 3 / export bundle). ipfs, ipfs_storage.'},
    'prov.purpose.helio': {'uk': 'Платіжний шлюз — оплата пакетів кредитів (USDC, Base): звіряння платежів + webhook. payment_service.', 'en': 'Payment gateway — credit package payments (USDC, Base): reconciliation + webhook. payment_service.'},
    'prov.purpose.base_rpc': {'uk': 'JSON-RPC до Base — Sybil-перевірка балансу ETH для вітальних кредитів. wallet_auth.', 'en': 'JSON-RPC to Base — Sybil check of ETH balance for welcome credits. wallet_auth.'},
    'prov.purpose.solana_rpc': {'uk': 'JSON-RPC до Solana — Sybil-перевірка балансу SOL для вітальних кредитів. wallet_auth.', 'en': 'JSON-RPC to Solana — Sybil check of SOL balance for welcome credits. wallet_auth.'},
    'prov.note.postpaid': {'uk': 'postpaid — баланс у кабінеті', 'en': 'postpaid — balance in dashboard'},
    'prov.note.unavailable': {'uk': 'баланс недоступний', 'en': 'balance unavailable'},
    'prov.note.stability': {'uk': '{credits} cr · поріг алерту {hard} cr', 'en': '{credits} cr · alert threshold {hard} cr'},
    'prov.note.free_tier': {'uk': 'free-tier (на час бети)', 'en': 'free-tier (during beta)'},
    'adm.col.engine': {'uk': 'двигун', 'en': 'engine'},
    'adm.col.ops': {'uk': 'операцій', 'en': 'ops'},
    'adm.col.credits': {'uk': 'кредитів', 'en': 'credits'},
    'adm.col.api_est': {'uk': 'оцінка API $', 'en': 'est. API $'},
    'adm.col.kind': {'uk': 'вид', 'en': 'kind'},
    'adm.col.credits2': {'uk': 'кредити', 'en': 'credits'},
    'adm.col.wallet': {'uk': 'гаманець', 'en': 'wallet'},
    'adm.col.debits': {'uk': 'списань', 'en': 'debits'},
    'adm.col.provider': {'uk': 'провайдер', 'en': 'provider'},
    'adm.col.status': {'uk': 'стан', 'en': 'status'},
    'adm.col.balance_usd': {'uk': 'баланс $', 'en': 'balance $'},
    'adm.col.rec_min': {'uk': 'рек. мін $', 'en': 'rec. min $'},
    'adm.col.note': {'uk': 'нотатка', 'en': 'note'},
    'adm.col.package': {'uk': 'пакет', 'en': 'package'},
    'adm.col.payments': {'uk': 'оплат', 'en': 'payments'},
    'adm.col.when': {'uk': 'коли', 'en': 'when'},
    'adm.col.first_seen': {'uk': 'перший', 'en': 'first seen'},
    'calc.title': {'uk': '💰 Калькулятор вартості дропу', 'en': '💰 Drop cost calculator'},
    'calc.supply': {'uk': 'Supply (кількість NFT)', 'en': 'Supply (number of NFTs)'},
    'calc.engine': {'uk': 'Двигун зображень', 'en': 'Image engine'},
    'calc.final': {'uk': 'Final-якість (дорожче)', 'en': 'Final quality (costs more)'},
    'calc.credits_per': {'uk': 'Кредитів за 1 NFT', 'en': 'Credits per NFT'},
    'calc.total_credits': {'uk': 'Разом кредитів', 'en': 'Total credits'},
    'calc.package_hint': {'uk': 'Рекомендований пакет', 'en': 'Suggested package'},
    'calc.usd_hint': {'uk': 'Орієнтовно USD (пакети Helio)', 'en': 'Approx. USD (Helio packages)'},
    'calc.sync_queue': {'uk': '↩ Узяти {n} із черги промптів', 'en': '↩ Use {n} from prompt queue'},
    'calc.pay_cta': {'uk': '💳 Поповнити: {label}', 'en': '💳 Top up: {label}'},
}
