"""i18n-рядки: домен collection (класична колекція (traits, build, batch, images)).

Збираються в `ui_strings._STRINGS` через `ui_strings._merge_strings()`. НЕ імпортуй
цей модуль у застосунку — використовуй `ui_strings.t()`. Парність uk↔en, плейсхолдери
й повноту ключів звіряє `tests/test_ui_strings.py` проти зібраного `_STRINGS`.
"""

STRINGS: dict[str, dict[str, str]] = {
    'classic.forward_caption': {'uk': 'Етап **{stage}** готовий — відкрийте наступну вкладку:', 'en': 'Stage **{stage}** complete — open the next tab:'},
    'classic.tab_flash': {'uk': 'Натисніть вкладку **{tab}** у рядку зверху (автоперемикання вкладок у Streamlit недоступне).', 'en': 'Click the **{tab}** tab in the bar above (Streamlit cannot switch tabs automatically).'},
    'classic.ctx_prefix': {'uk': '**Конструктор →**', 'en': '**Builder →**'},
    'classic.ctx_no_idea': {'uk': '— ідея —', 'en': '— no idea —'},
    'classic.ctx_notes': {'uk': 'зауваження: {text}', 'en': 'notes: {text}'},
    'classic.ctx_combos': {'uk': '{n:,} комб.', 'en': '{n:,} combos'},
    'build.caption': {'uk': 'Зберіть один промпт із аналізом: ліворуч оберіть напрямок (стиль, камера, світло) — праворуч отримаєте готовий промпт. Далі → **② Traits** або **③ Batch**.', 'en': 'Build one analyzed prompt: choose direction (style, camera, light) on the left — get a ready prompt on the right. Next → **② Traits** or **③ Batch**.'},
    'build.settings': {'uk': 'Налаштування напрямку', 'en': 'Direction settings'},
    'build.random_params': {'uk': '🎲 Випадкові параметри', 'en': '🎲 Random parameters'},
    'build.random_params_help': {'uk': 'Випадковий стиль, ракурс, освітлення, фон, якість, настрій, stylize і chaos', 'en': 'Random style, camera, lighting, background, quality, mood, stylize and chaos'},
    'build.random_idea': {'uk': '💡 Випадкова ідея', 'en': '💡 Random idea'},
    'build.random_idea_help': {'uk': 'Випадковий персонаж із пулу концептів', 'en': 'Random character from concept pool'},
    'build.random_all': {'uk': '🎰 Все випадково', 'en': '🎰 Randomize all'},
    'build.random_all_help': {'uk': 'Випадкова ідея + всі параметри одразу', 'en': 'Random idea + all parameters at once'},
    'build.traits_unchanged': {'uk': 'Параметри Builder змінено; вкладка Traits **не змінювалась** (ваші трейти збережено).', 'en': 'Builder settings changed; the Traits tab was **not** modified (your traits are kept).'},
    'build.idea': {'uk': "1. Основний персонаж/об'єкт", 'en': '1. Main character/object'},
    'build.style': {'uk': '2. Стиль', 'en': '2. Style'},
    'build.camera': {'uk': '3. Ракурс', 'en': '3. Camera'},
    'build.lighting': {'uk': '4. Освітлення', 'en': '4. Lighting'},
    'build.background': {'uk': '5. Фон', 'en': '5. Background'},
    'build.quality': {'uk': '6. Деталізація', 'en': '6. Detail level'},
    'build.mood': {'uk': '7. Настрій', 'en': '7. Mood'},
    'build.tech_expand': {'uk': '🔧 Технічні параметри', 'en': '🔧 Technical parameters'},
    'build.aspect': {'uk': 'Співвідношення', 'en': 'Aspect ratio'},
    'build.stylize': {'uk': 'Stylize (--s)', 'en': 'Stylize (--s)'},
    'build.chaos': {'uk': 'Chaos (--c)', 'en': 'Chaos (--c)'},
    'build.seed': {'uk': 'Seed', 'en': 'Seed'},
    'build.extra': {'uk': 'Додаткові побажання', 'en': 'Additional notes'},
    'build.submit': {'uk': 'Згенерувати структуру промту ⚡', 'en': 'Generate prompt structure ⚡'},
    'build.result': {'uk': 'Результат', 'en': 'Result'},
    'build.idea_required': {'uk': 'Вкажіть основного персонажа.', 'en': 'Specify the main character.'},
    'build.api_openai_missing': {'uk': 'Відсутній OpenAI API Key.', 'en': 'OpenAI API key missing.'},
    'build.api_anthropic_missing': {'uk': 'Відсутній Anthropic API Key.', 'en': 'Anthropic API key missing.'},
    'build.generating': {'uk': 'Генерація…', 'en': 'Generating…'},
    'build.done_cost': {'uk': 'Готово! Вартість: ${cost:.4f}', 'en': 'Done! Cost: ${cost:.4f}'},
    'build.api_error': {'uk': 'Помилка API: {err}', 'en': 'API error: {err}'},
    'build.last_saved': {'uk': 'Останній результат збережено.', 'en': 'Last result saved.'},
    'build.prompt_label': {'uk': 'Фінальний промпт', 'en': 'Final prompt'},
    'build.ai_lang_note': {'uk': 'Мова аналізу AI залежить від мови інтерфейсу на момент генерації; промпт зображення — завжди англійською.', 'en': 'AI analysis language follows the UI language at generation time; the image prompt is always English.'},
    'build.quickstart_title': {'uk': 'Швидкий старт', 'en': 'Quick start'},
    'build.quickstart_body': {'uk': '1. Шаблон у бічній панелі → «Застосувати»<br>2. Перевірте напрямок тут (опційно 1 промт)<br>3. Traits → ваги та комбінації<br>4. Batch (10–20) → Зображення (превʼю стилю)<br>5. Колекція → повний run + ZIP/IPFS', 'en': '1. Sidebar template → «Apply»<br>2. Check direction here (optional 1 prompt)<br>3. Traits → weights & combos<br>4. Batch (10–20) → Images (style preview)<br>5. Collection → full run + ZIP/IPFS'},
    'traits.title': {'uk': '🧬 Конструктор Traits', 'en': '🧬 Traits builder'},
    'traits.caption': {'uk': 'Один trait на рядок. Рідкісність: `назва | вага` — `золота корона | 1` (рідкісний), `бейсболка | 20` (поширений). Без ваги = 1. Ctrl+Enter лише оновлює поле — не перемикає режим.', 'en': 'One trait per line. Rarity: `name | weight` — `golden crown | 1` (rare), `cap | 20` (common). No weight = 1. Ctrl+Enter only updates the field — it does not switch mode.'},
    'traits.import_hint': {'uk': 'Знайдено **{n}** категорій traits у результаті Конструктора — можна перенести в поля нижче.', 'en': 'Found **{n}** trait categories in the Builder result — you can fill the fields below.'},
    'traits.import_btn': {'uk': '⬇️ Заповнити traits з Конструктора', 'en': '⬇️ Fill traits from Builder'},
    'traits.apply_weights': {'uk': '💾 Застосувати ваги до полів', 'en': '💾 Apply weights to fields'},
    'traits.combos': {'uk': 'Унікальних комбінацій', 'en': 'Unique combinations'},
    'traits.combos_low': {'uk': 'Комбінацій ({total:,}) менше за ціль ({target}). Додайте варіанти або застосуйте шаблон.', 'en': 'Combinations ({total:,}) below target ({target}). Add variants or apply a template.'},
    'traits.dominant': {'uk': '«{cat}»: «{name}» займає {pct:.0f}% ваги — може домінувати в колекції.', 'en': '«{cat}»: «{name}» is {pct:.0f}% of weight — may dominate the collection.'},
    'traits.empty': {'uk': 'Застосуйте шаблон колекції — у **боковій панелі ліворуч** (📋 Шаблони колекцій → «Оберіть шаблон» → ✅ Застосувати) — або заповніть traits вручну / імпортуйте з Конструктора.', 'en': 'Apply a collection template — in the **left sidebar** (📋 Collection templates → «Choose template» → ✅ Apply) — or fill traits manually / import from Builder.'},
    'batch.title': {'uk': '📦 Batch-генерація промтів', 'en': '📦 Batch prompt generation'},
    'batch.caption': {'uk': 'Унікальні промти з traits (ваги рідкісності) та базового концепту. Паралельні запити.', 'en': 'Unique prompts from traits (rarity weights) and base concept. Parallel requests.'},
    'batch.count': {'uk': 'Кількість промтів', 'en': 'Number of prompts'},
    'batch.combos_avail': {'uk': 'Доступно комбінацій', 'en': 'Combinations available'},
    'batch.est_cost': {'uk': '≈ Оцінка вартості', 'en': '≈ Estimated cost'},
    'batch.est_credits': {'uk': '≈ Кредити', 'en': '≈ Credits'},
    'batch.need_traits': {'uk': 'Спочатку застосуйте шаблон або заповніть traits на відповідній вкладці.', 'en': 'Apply a template or fill traits on the Traits tab first.'},
    'batch.need_idea': {'uk': 'Вкажіть основного персонажа на вкладці «Конструктор».', 'en': 'Specify main character on the Builder tab.'},
    'batch.run': {'uk': '🚀 Згенерувати {n} промтів', 'en': '🚀 Generate {n} prompts'},
    'batch.partial': {'uk': 'Згенеровано {ok} промтів, але частина блоків впала ({err} помилок). Перша: {first}', 'en': 'Generated {ok} prompts but some blocks failed ({err} errors). First: {first}'},
    'batch.ok': {'uk': 'Згенеровано {n} промтів!', 'en': 'Generated {n} prompts!'},
    'batch.ok_credits': {'uk': 'Згенеровано {n} промтів! −{cr} cr · залишок: **{balance}** cr', 'en': 'Generated {n} prompts! −{cr} cr · balance: **{balance}** cr'},
    'batch.ok_credits_short': {'uk': 'Згенеровано {n} промтів! −{cr} cr', 'en': 'Generated {n} prompts! −{cr} cr'},
    'batch.error': {'uk': 'Помилка: {err}', 'en': 'Error: {err}'},
    'batch.results': {'uk': '**Результати ({n} шт.)**', 'en': '**Results ({n} items)**'},
    'batch.actual_cost': {'uk': ' · Фактична вартість: ${cost:.4f} ({tokens} токенів)', 'en': ' · Actual cost: ${cost:.4f} ({tokens} tokens)'},
    'batch.actual_credits': {'uk': ' · Списано: **{cr} cr** ({n} промтів)', 'en': ' · Charged: **{cr} cr** ({n} prompts)'},
    'batch.col_prompt': {'uk': 'Промт', 'en': 'Prompt'},
    'batch.expander': {'uk': '#{id} — повний промт (rarity {score})', 'en': '#{id} — full prompt (rarity {score})'},
    'batch.negative': {'uk': 'Negative:', 'en': 'Negative:'},
    'batch.more_export': {'uk': '… та ще {n} промтів у файлі експорту', 'en': '… and {n} more prompts in export file'},
    'batch.meta_expand': {'uk': '🪙 Експорт метаданих (ERC-721 / Metaplex)', 'en': '🪙 Metadata export (ERC-721 / Metaplex)'},
    'batch.meta_caption': {'uk': 'Продукт для мінту — **англійською**: назва, опис, attributes. Промти з batch уже EN.', 'en': 'Mint product — **English**: name, description, attributes. Batch prompts are already EN.'},
    'batch.dist_expand': {'uk': '📊 Розподіл traits (очікуваний vs фактичний)', 'en': '📊 Trait distribution (expected vs actual)'},
    'batch.progress': {'uk': 'Batch-генерація…', 'en': 'Batch generation…'},
    'batch.blocks_done': {'uk': 'Готово блоків: {done} / {total}', 'en': 'Blocks done: {done} / {total}'},
    'batch.no_traits_err': {'uk': 'Додайте traits (вкладка Traits) або застосуйте шаблон колекції.', 'en': 'Add traits (Traits tab) or apply a collection template.'},
    'coll.title': {'uk': '🏭 Повна колекція', 'en': '🏭 Full collection'},
    'coll.caption': {'uk': 'До 10 000 промтів із чекпоінтами: прогрес зберігається, перерваний процес можна продовжити.', 'en': 'Up to 10,000 prompts with checkpoints: progress saved, resume anytime.'},
    'coll.pipeline_banner': {'uk': '💡 **Рекомендовано:** **⛓️ Конвеєр → 2️⃣ Зображення** — Flux/Stability кредитами, Pilot, куратор, QA, export gate, W3IR-бандл. **Нижче** — classic через ваш OpenAI-ключ.', 'en': '💡 **Recommended:** **⛓️ Pipeline → 2️⃣ Images** — Flux/Stability via credits, Pilot, curator, QA, export gate, W3IR bundle. **Below** — classic via your OpenAI key.'},
    'coll.new_run': {'uk': '**🚀 Новий запуск**', 'en': '**🚀 New run**'},
    'coll.run_name': {'uk': 'Назва запуску', 'en': 'Run name'},
    'coll.token_count': {'uk': 'Кількість токенів', 'en': 'Token count'},
    'coll.prompt_cost': {'uk': '≈ Вартість промтів ({model}): ${cost:.2f}', 'en': '≈ Prompt cost ({model}): ${cost:.2f}'},
    'coll.prompt_credits': {'uk': '≈ Промпти ({model}): **{cr} cr** (1 cr / промт)', 'en': '≈ Prompts ({model}): **{cr} cr** (1 cr / prompt)'},
    'coll.start': {'uk': '🚀 Почати генерацію', 'en': '🚀 Start generation'},
    'coll.need_traits': {'uk': 'Заповніть traits або застосуйте шаблон.', 'en': 'Fill traits or apply a template.'},
    'coll.run_exists': {'uk': 'Запуск «{name}» вже існує. Продовжіть його або змініть назву.', 'en': 'Run «{name}» already exists. Resume it or change the name.'},
    'coll.saved_runs': {'uk': '**📂 Збережені запуски**', 'en': '**📂 Saved runs**'},
    'coll.no_runs': {'uk': 'Збережених запусків немає.', 'en': 'No saved runs.'},
    'coll.run_select': {'uk': 'Запуск', 'en': 'Run'},
    'coll.metric_prompts': {'uk': 'Промти', 'en': 'Prompts'},
    'coll.metric_images': {'uk': 'Зображення', 'en': 'Images'},
    'coll.metric_spent': {'uk': 'Витрачено', 'en': 'Spent'},
    'coll.metric_credits_spent': {'uk': 'Промпти (cr)', 'en': 'Prompts (cr)'},
    'coll.resume': {'uk': '▶️ Продовжити', 'en': '▶️ Resume'},
    'coll.to_batch': {'uk': '📦 У вкладку Batch', 'en': '📦 To Batch tab'},
    'coll.to_batch_help': {'uk': 'Переглянути результати та експортувати на вкладці Batch', 'en': 'View results and export on the Batch tab'},
    'coll.loaded_batch': {'uk': 'Результати завантажено у вкладку Batch.', 'en': 'Results loaded into Batch tab.'},
    'coll.delete_run': {'uk': '🗑️ Видалити запуск', 'en': '🗑️ Delete run'},
    'coll.prompt_progress': {'uk': 'Генерація промтів…', 'en': 'Generating prompts…'},
    'coll.prompts_of': {'uk': 'Промтів: {done} / {total}', 'en': 'Prompts: {done} / {total}'},
    'coll.done_prompts': {'uk': 'Готово: {done} / {target} промтів.', 'en': 'Done: {done} / {target} prompts.'},
    'coll.interrupted': {'uk': 'Перервано: {err}. Прогрес збережено — продовжіть запуск.', 'en': 'Interrupted: {err}. Progress saved — resume the run.'},
    'coll.resuming': {'uk': 'Продовження…', 'en': 'Resuming…'},
    'coll.images_for': {'uk': '### 🎨 Зображення для «{run}»', 'en': '### 🎨 Images for «{run}»'},
    'coll.images_progress': {'uk': 'Готово {done} із {total} зображень. Наявні файли пропускаються.', 'en': 'Done {done} of {total} images. Existing files are skipped.'},
    'coll.size': {'uk': 'Розмір', 'en': 'Size'},
    'coll.size_help': {'uk': 'За замовчуванням від aspect ratio Конструктора ({ar})', 'en': 'Default from Builder aspect ratio ({ar})'},
    'coll.quality': {'uk': 'Якість', 'en': 'Quality'},
    'coll.budget': {'uk': 'Бюджет, $ (0 = без ліміту)', 'en': 'Budget, $ (0 = unlimited)'},
    'coll.image_cost_hint': {'uk': '≈ ${per:.3f} за зображення · буде згенеровано до {n} шт. (≈ ${total:.2f})', 'en': '≈ ${per:.3f} per image · up to {n} images (≈ ${total:.2f})'},
    'coll.gen_images': {'uk': '🎨 Згенерувати {n} зображень', 'en': '🎨 Generate {n} images'},
    'coll.no_openai': {'uk': 'Відсутній OpenAI API Key для генерації зображень.', 'en': 'OpenAI API key missing for image generation.'},
    'coll.img_progress': {'uk': 'Генерація зображень…', 'en': 'Generating images…'},
    'coll.images_of': {'uk': 'Зображень: {done} / {total}', 'en': 'Images: {done} / {total}'},
    'coll.images_done': {'uk': 'Згенеровано {n} зображень (≈ ${spent:.2f})', 'en': 'Generated {n} images (≈ ${spent:.2f})'},
    'coll.images_failed': {'uk': ', помилок: {n}', 'en': ', failures: {n}'},
    'coll.images_interrupted': {'uk': 'Перервано: {err}. Готові зображення збережено.', 'en': 'Interrupted: {err}. Completed images saved.'},
    'coll.export_title': {'uk': '### 📦 Збірний експорт', 'en': '### 📦 Bundle export'},
    'coll.export_caption': {'uk': 'Файли для мінту — **англійською**. UI оператора може бути українською.', 'en': 'Mint files — **English**. Operator UI may be Ukrainian.'},
    'coll.ipfs_title': {'uk': '#### 📡 IPFS (Pinata)', 'en': '#### 📡 IPFS (Pinata)'},
    'coll.pinata_hint': {'uk': 'Додайте `PINATA_JWT` у `.env` або Streamlit Secrets для IPFS.', 'en': 'Add `PINATA_JWT` to `.env` or Streamlit Secrets for IPFS.'},
    'coll.ipfs_images': {'uk': 'Зображення: `ipfs://{cid}`', 'en': 'Images: `ipfs://{cid}`'},
    'coll.ipfs_meta': {'uk': 'Метадані: `ipfs://{cid}` · Token URI: `ipfs://{cid}/<id>.json`', 'en': 'Metadata: `ipfs://{cid}` · Token URI: `ipfs://{cid}/<id>.json`'},
    'coll.upload_images': {'uk': '📡 Зображення → IPFS', 'en': '📡 Images → IPFS'},
    'coll.upload_meta': {'uk': '📡 Метадані → IPFS', 'en': '📡 Metadata → IPFS'},
    'coll.upload_meta_help': {'uk': 'Метадані з полів вище завантажуються каталогом.', 'en': 'Metadata from fields above uploaded as directory.'},
    'coll.uploading_images': {'uk': 'Завантаження {n} зображень у Pinata…', 'en': 'Uploading {n} images to Pinata…'},
    'coll.uploading_meta': {'uk': 'Завантаження метаданих у Pinata…', 'en': 'Uploading metadata to Pinata…'},
    'coll.ipfs_images_ok': {'uk': 'Зображення в IPFS: ipfs://{cid} — base URI підставлено.', 'en': 'Images on IPFS: ipfs://{cid} — base URI applied.'},
    'coll.ipfs_meta_ok': {'uk': 'Метадані в IPFS: ipfs://{cid} · Token URI: ipfs://{cid}/<id>.json', 'en': 'Metadata on IPFS: ipfs://{cid} · Token URI: ipfs://{cid}/<id>.json'},
    'coll.ipfs_error': {'uk': 'Помилка IPFS: {err}', 'en': 'IPFS error: {err}'},
    'coll.build_zip': {'uk': '📦 Зібрати ZIP (images + metadata + prompts)', 'en': '📦 Build ZIP (images + metadata + prompts)'},
    'coll.zip_ok': {'uk': 'Архів зібрано: `{path}` ({mb:.1f} МБ)', 'en': 'Archive built: `{path}` ({mb:.1f} MB)'},
    'coll.download_zip': {'uk': '📥 Завантажити ZIP', 'en': '📥 Download ZIP'},
    'coll.zip_too_large': {'uk': 'Архів завеликий для браузера — візьміть з `data/exports/`.', 'en': 'Archive too large for browser — use `data/exports/`.'},
    'coll.pick_run_hint': {'uk': 'Оберіть запуск і догенеруйте промти для зображень та експорту.', 'en': 'Select a run and finish prompts to proceed to images and export.'},
    'img.title': {'uk': '🖼️ Швидке превʼю (1–4 кадри)', 'en': '🖼️ Quick preview (1–4 frames)'},
    'img.caption': {'uk': 'Перевірити **один промпт** перед дропом. **Не** mint-ready експорт — лише PNG-чернетки.', 'en': 'Test **one prompt** before a drop. **Not** mint-ready export — draft PNGs only.'},
    'img.requirements': {'uk': '**Що потрібно на ai.w3ir.io:** (1) підключений гаманець · (2) **OpenAI API key** у sidebar · (3) **{per} кредитів за кадр** на платформі. Рахунок OpenAI списується **окремо** (USD нижче). Без свого OpenAI key — **⛓️ Конвеєр → 2️⃣** (Flux/Stability за кредити).', 'en': '**Required on ai.w3ir.io:** (1) connected wallet · (2) **OpenAI API key** in sidebar · (3) **{per} platform credits per frame**. Your OpenAI account is billed **separately** (USD below). No OpenAI key — use **⛓️ Pipeline → 2️⃣** (Flux/Stability for credits).'},
    'img.pipeline_banner': {'uk': '💡 **Для готового дропу:** **⛓️ Конвеєр → 2️⃣** — куратор, QA, Prompt-Lock, export. **Ця вкладка** — лише швидкий тест промпта (1–4 PNG), не заміна Конвеєра.', 'en': '💡 **For a finished drop:** **⛓️ Pipeline → 2️⃣** — curator, QA, Prompt-Lock, export. **This tab** — quick prompt test only (1–4 PNGs), not a Pipeline replacement.'},
    'img.pipeline_bridge_caption': {'uk': 'Перенеси промпти в **⛓️ Конвеєр → 2️⃣ Зображення**: генерація **кредитами** (не потрібен OpenAI key), куратор, regenerate, export preflight.', 'en': 'Move prompts to **⛓️ Pipeline → 2️⃣ Images**: **credit-based** generation (no OpenAI key needed), curator, regenerate, export preflight.'},
    'img.pipeline_no_prompts': {'uk': '**Зараз:** введи промпт нижче або згенеруй **③ Batch** / **④ Колекція** · **Далі:** зʼявиться **«→ У Конвеєр»** · **Порада:** Batch достатньо для тесту перед повним run.', 'en': '**Now:** enter a prompt below or generate **③ Batch** / **④ Collection** · **Next:** **«→ To Pipeline»** appears · **Tip:** Batch is enough to test before a full run.'},
    'img.expand_title': {'uk': 'ℹ️ Швидке превʼю vs інші шляхи зображень', 'en': 'ℹ️ Quick preview vs other image paths'},
    'img.expand_body': {'uk': '| | **⑤ Швидке превʼю** | **④ Колекція → images** | **⛓️ Конвеєр → 2️⃣** |\n|---|---|---|---|\n| Мета | Тест 1 промпта | Масові PNG для run | Mint-ready дроп |\n| OpenAI key | Так | Так | Ні (кредити) |\n| Кредити W3IR (ai.w3ir.io) | **4 cr/кадр** | Ні (лише USD-бюджет) | Так |\n| Куратор / export | Ні | ZIP у Колекції | Так |\n| Зберігання | `data/previews/` | `data/images/<run>/` | Проєкт + export |', 'en': '| | **⑤ Quick preview** | **④ Collection → images** | **⛓️ Pipeline → 2️⃣** |\n|---|---|---|---|\n| Goal | Test 1 prompt | Bulk PNGs for a run | Mint-ready drop |\n| OpenAI key | Yes | Yes | No (credits) |\n| W3IR credits (ai.w3ir.io) | **4 cr/frame** | No (USD budget only) | Yes |\n| Curator / export | No | ZIP in Collection | Yes |\n| Storage | `data/previews/` | `data/images/<run>/` | Project + export |'},
    'img.cloud_hint': {'uk': '☁️ Streamlit Cloud: превʼю тимчасові. Завантажте PNG одразу після генерації.', 'en': '☁️ Streamlit Cloud: previews are temporary. Download PNGs right after generation.'},
    'img.no_idea': {'uk': 'Ідея не задана — заповніть персонажа на **Конструкторі** або шаблон. Можна ввести EN-промт нижче.', 'en': 'No idea set — fill character on **Builder** or apply template. Or enter EN prompt below.'},
    'img.prompt_pick': {'uk': 'Промт із batch або колекції', 'en': 'Prompt from batch or collection'},
    'img.prompt_pick_help': {'uk': 'Обраний run синхронізується з вкладкою «Колекція».', 'en': 'Selected collection run syncs with Collection tab.'},
    'img.from_constructor': {'uk': 'Промт підставлено з останньої генерації на **Конструкторі**. Можна редагувати.', 'en': 'Prompt from last **Builder** generation. You can edit it.'},
    'img.prompt_hint': {'uk': 'Для автопідстановки: **Batch** або **Колекція**. Або введіть EN-промт вручну.', 'en': 'For auto-fill: **Batch** or **Collection**. Or enter EN prompt manually.'},
    'img.prompt_label': {'uk': 'Промт для зображення', 'en': 'Image prompt'},
    'img.prompt_help': {'uk': 'Можна відредагувати перед генерацією.', 'en': 'Editable before generation.'},
    'img.variants': {'uk': 'Варіантів', 'en': 'Variants'},
    'img.cost_hint': {'uk': 'Орієнтовно на рахунку OpenAI: ≈ {per:.3f} USD × {n} = ≈ {total:.3f} USD (окремо від кредитів W3IR)', 'en': 'Estimated on your OpenAI account: ≈ {per:.3f} USD × {n} = ≈ {total:.3f} USD (separate from W3IR credits)'},
    'img.credits_hint': {'uk': 'На ai.w3ir.io додатково: {per} cr × {n} = {total} cr на платформі', 'en': 'On ai.w3ir.io additionally: {per} cr × {n} = {total} cr on the platform'},
    'img.gen_one': {'uk': '🎨 Згенерувати зображення', 'en': '🎨 Generate image'},
    'img.gen_many': {'uk': '🎨 Згенерувати {n} варіанти', 'en': '🎨 Generate {n} variants'},
    'img.prompt_required': {'uk': 'Вкажіть промт.', 'en': 'Enter a prompt.'},
    'img.gen_spin_one': {'uk': 'Генерація зображення…', 'en': 'Generating image…'},
    'img.gen_spin_many': {'uk': 'Генерація {n} зображень…', 'en': 'Generating {n} images…'},
    'img.gen_ok_one': {'uk': 'Готово! 1 зображення. Файл: `{path}`', 'en': 'Done! 1 image. File: `{path}`'},
    'img.gen_ok_many': {'uk': 'Готово! {n} зображень. Файл: `{path}` … (+{extra})', 'en': 'Done! {n} images. File: `{path}` … (+{extra})'},
    'img.gen_error': {'uk': 'Помилка генерації зображення: {err}', 'en': 'Image generation error: {err}'},
    'img.recent': {'uk': '**Останні превʼю ({n})**', 'en': '**Recent previews ({n})**'},
    'img.clear': {'uk': '🗑️ Очистити', 'en': '🗑️ Clear'},
    'img.clear_help': {'uk': 'Видалити PNG з data/previews/', 'en': 'Delete PNGs from data/previews/'},
    'img.variant_cap': {'uk': 'Варіант {v} · ', 'en': 'Variant {v} · '},
    'img.download_png': {'uk': '📥 Завантажити PNG', 'en': '📥 Download PNG'},
    'img.download_help': {'uk': 'Файл збережеться у «Завантаження»; застосунок залишиться відкритим.', 'en': 'File saves to Downloads; app stays open.'},
}
