"""i18n-рядки: домен commerce (гроші: Export Center, білінг, пакети, проєкти, метадані).

Збираються в `ui_strings._STRINGS` через `ui_strings._merge_strings()`. НЕ імпортуй
цей модуль у застосунку — використовуй `ui_strings.t()`. Парність uk↔en, плейсхолдери
й повноту ключів звіряє `tests/test_ui_strings.py` проти зібраного `_STRINGS`.
"""

STRINGS: dict[str, dict[str, str]] = {
    'pkg.start.label': {'uk': '🟢 Старт', 'en': '🟢 Start'},
    'pkg.start.note': {'uk': 'Низький поріг входу — спробувати сервіс', 'en': 'Low entry point — try the service'},
    'pkg.creator.label': {'uk': '🟡 Креатор', 'en': '🟡 Creator'},
    'pkg.creator.note': {'uk': '350 базових + 50 бонусних за обсяг', 'en': '350 base + 50 volume bonus'},
    'pkg.pro.label': {'uk': '🔵 Профі / Колекція', 'en': '🔵 Pro / Collection'},
    'pkg.pro.note': {'uk': '750 базових + 250 бонусних — для матричних дропів', 'en': '750 base + 250 bonus — for matrix drops'},
    'project.title': {'uk': '📂 Проєкт', 'en': '📂 Project'},
    'project.autosave_hint': {'uk': 'Autosave: промпти, зображення, експорт. Керуйте дропами тут (новий, копія, перейменувати).', 'en': 'Autosave: prompts, images, export. Manage drops here (new, duplicate, rename).'},
    'project.active_caption': {'uk': 'Активний: **{name}**', 'en': 'Active: **{name}**'},
    'project.pick': {'uk': 'Мої проєкти', 'en': 'My projects'},
    'project.new': {'uk': '➕ Новий', 'en': '➕ New'},
    'project.duplicate': {'uk': '📋 Копія', 'en': '📋 Copy'},
    'project.duplicate_help': {'uk': 'Копія поточного проєкту (промпти, PNG, схвалені) — займає місце на диску.', 'en': 'Copy the current project (prompts, PNGs, approved) — uses disk space.'},
    'project.rename': {'uk': '✏️ Імʼя', 'en': '✏️ Rename'},
    'project.rename_ph': {'uk': 'Нова назва', 'en': 'New name'},
    'project.rename_pick': {'uk': 'Проєкт', 'en': 'Project'},
    'project.rename_help': {'uk': 'Перейменувати будь-який збережений проєкт.', 'en': 'Rename any saved project.'},
    'project.rename_none': {'uk': 'Немає проєктів для перейменування.', 'en': 'No projects to rename.'},
    'project.rename_failed': {'uk': 'Не вдалося перейменувати проєкт.', 'en': 'Could not rename the project.'},
    'project.rename_save': {'uk': 'Зберегти', 'en': 'Save'},
    'project.cancel': {'uk': 'Скасувати', 'en': 'Cancel'},
    'project.download': {'uk': '⬇️ ZIP', 'en': '⬇️ ZIP'},
    'project.download_help': {'uk': 'Завантажити проєкт на свій ПК (ZIP: промпти, зображення, стан). Сервер не бекапить ваші PNG — тримайте локальну копію.', 'en': 'Download this project to your PC (ZIP: prompts, images, state). The server does not back up your PNGs — keep a local copy.'},
    'project.download_ready': {'uk': 'Архів готовий (~{size_mb} MB).', 'en': 'Archive ready (~{size_mb} MB).'},
    'project.download_save': {'uk': '💾 Зберегти ZIP', 'en': '💾 Save ZIP'},
    'project.load_disk_error': {
        'uk': 'Не вдалося зберегти/завантажити проєкт на диск (тимчасове блокування файлу). Спробуйте ще раз через кілька секунд.',
        'en': 'Could not save/load the project on disk (file temporarily locked). Try again in a few seconds.',
    },
    'project.delete': {'uk': '🗑️ Вид.', 'en': '🗑️ Del'},
    'project.delete_help': {'uk': 'Видалити проєкт і всі його файли (промпти, зображення).', 'en': 'Delete project and all its files (prompts, images).'},
    'project.delete_pick': {'uk': 'Проєкт для видалення', 'en': 'Project to delete'},
    'project.delete_confirm': {'uk': 'Видалити «{name}» назавжди? Дію не можна скасувати.', 'en': 'Delete «{name}» permanently? This cannot be undone.'},
    'project.delete_confirm_btn': {'uk': 'Видалити', 'en': 'Delete'},
    'project.delete_none': {'uk': 'Немає проєктів для видалення.', 'en': 'No projects to delete.'},
    'project.delete_failed': {'uk': 'Не вдалося видалити проєкт.', 'en': 'Could not delete the project.'},
    'project.warn_many': {'uk': 'У вас {count} проєктів — зайві копії та зображення займають місце. Видаліть непотрібне (🗑️).', 'en': "You have {count} projects — duplicates and images use disk space. Delete what you don't need (🗑️)."},
    'project.quota_usage': {'uk': 'Проєкти: {count}{limit_part} · ~{used_mb} MB{mb_part}', 'en': 'Projects: {count}{limit_part} · ~{used_mb} MB{mb_part}'},
    'project.active_disk': {'uk': '~{size_mb} MB · {files} файлів', 'en': '~{size_mb} MB · {files} files'},
    'project.quota.project_limit': {'uk': 'Досягнуто ліміт проєктів ({limit}). Видаліть непотрібні (🗑️) або поповніть баланс — платники без цього ліміту.', 'en': 'Project limit reached ({limit}). Delete unused projects (🗑️) or top up — paying users are exempt.'},
    'project.quota.disk_limit': {'uk': 'Перевищено ліміт місця ({limit_mb} MB, зараз ~{used_mb} MB). Видаліть проєкти або зображення.', 'en': 'Disk quota exceeded ({limit_mb} MB, currently ~{used_mb} MB). Delete projects or images.'},
    'project.new_ph': {'uk': 'Назва проєкту', 'en': 'Project name'},
    'project.new_save': {'uk': 'Створити', 'en': 'Create'},
    'project.new_help': {'uk': 'За замовчуванням — поточна дата й час; можна змінити перед створенням.', 'en': 'Default is current date and time; edit before creating if you prefer.'},
    'project.untitled': {'uk': 'Без назви', 'en': 'Untitled'},
    'project.classic_new': {'uk': 'Classic', 'en': 'Classic'},
    'project.stage_hint': {'uk': 'Етап: {stage}', 'en': 'Stage: {stage}'},
    'project.classic_hint': {'uk': 'Колекція · {idea}', 'en': 'Collection · {idea}'},
    'project.classic_hint_empty': {'uk': 'Колекція · розширений режим', 'en': 'Collection · advanced mode'},
    'bill.title': {'uk': '##### 💳 Кредити та оплата', 'en': '##### 💳 Credits & billing'},
    # ── Genesis holder bonus (holder_rewards) ──
    'holder.title': {'uk': '**🟣 Genesis holder bonus**', 'en': '**🟣 Genesis holder bonus**'},
    'holder.need_solana': {'uk': 'Увійдіть гаманцем **Solana (Phantom)**, який тримає W3IR Genesis Avatar, щоб отримати бонусні кредити.', 'en': 'Sign in with the **Solana (Phantom)** wallet that holds your W3IR Genesis Avatar to claim bonus credits.'},
    'holder.not_holder': {'uk': 'На цьому гаманці немає W3IR Genesis Avatar. Замінтуйте на [mint.w3ir.io](https://mint.w3ir.io) — і отримайте безкоштовні кредити.', 'en': 'No W3IR Genesis Avatar on this wallet. Mint one at [mint.w3ir.io](https://mint.w3ir.io) and earn free credits.'},
    'holder.claimable': {'uk': 'Ви тримаєте **{count}** Genesis · доступно **{credits}** бонусних кредитів.', 'en': 'You hold **{count}** Genesis · **{credits}** bonus credits available.'},
    'holder.claim_btn': {'uk': '🎁 Отримати {credits} кредитів', 'en': '🎁 Claim {credits} credits'},
    'holder.claimed': {'uk': 'Бонус уже отримано ({period}). Дякуємо, що ви холдер! 💜', 'en': 'Bonus already claimed ({period}). Thanks for holding! 💜'},
    'holder.granted': {'uk': '✅ Нараховано {credits} кредитів. Новий баланс: {balance}.', 'en': '✅ Granted {credits} credits. New balance: {balance}.'},
    'holder.budget': {'uk': 'Бонусний фонд цього періоду вичерпано. Спробуйте пізніше.', 'en': 'The bonus pool for this period is exhausted. Try again later.'},
    'holder.error': {'uk': 'Не вдалося перевірити володіння зараз. Оновіть сторінку.', 'en': 'Could not verify holdings right now. Refresh and try again.'},
    'holder.team_excluded': {'uk': 'Бонус для командних/сервісних гаманців не нараховується.', 'en': 'Bonus credits are not granted to team/service wallets.'},
    'ec.sugar_runbook': {
        'uk': '**Далі (LAUNCH):** розпакуйте ZIP у `C:\\Sugar\\` → runbook `docs/DROP_FROM_PROMPT.md`. Приклад: [mint.w3ir.io](https://mint.w3ir.io).',
        'en': '**Next (LAUNCH):** unzip into `C:\\Sugar\\` → runbook `docs/DROP_FROM_PROMPT.md`. Example: [mint.w3ir.io](https://mint.w3ir.io).',
    },
    'bill.balance': {'uk': 'Баланс кредитів', 'en': 'Credit balance'},
    'bill.connected_wallet': {'uk': 'Підключено · `{short}`', 'en': 'Connected · `{short}`'},
    'bill.copy_wallet': {'uk': 'Копіювати адресу', 'en': 'Copy address'},
    'bill.disconnect': {'uk': "🔌 Від'єднати", 'en': '🔌 Disconnect'},
    'bill.connect_metamask': {'uk': '🦊 Підключити MetaMask (підпис одним кліком)', 'en': '🦊 Connect MetaMask (one-click sign-in)'},
    'bill.manual_expand': {'uk': '⌨️ Ручне підключення (якщо MetaMask-компонент не завантажився)', 'en': '⌨️ Manual connect (if MetaMask component failed to load)'},
    'bill.component_fallback': {'uk': 'Якщо зверху помилка завантаження компонента — скористайтесь **ручним підключенням** нижче.', 'en': 'If the component failed to load above — use **manual connect** below.'},
    'bill.wallet_placeholder': {'uk': 'Адреса гаманця (Base 0x… або Solana)', 'en': 'Wallet address (Base 0x… or Solana)'},
    'bill.evm_caption': {'uk': '**EVM:** підпишіть повідомлення в MetaMask — захист від підміни адреси.', 'en': '**EVM:** sign a message in MetaMask — prevents address spoofing.'},
    'bill.get_message': {'uk': '🔐 Отримати повідомлення для підпису', 'en': '🔐 Get message to sign'},
    'bill.paste_sig': {'uk': 'Вставте підпис (0x…)', 'en': 'Paste signature (0x…)'},
    'bill.verify': {'uk': '✅ Підключити з підписом', 'en': '✅ Connect with signature'},
    'bill.solana_caption': {'uk': '**Solana:** підпишіть повідомлення в Phantom — захист від підміни адреси.', 'en': '**Solana:** sign a message in Phantom — prevents address spoofing.'},
    'bill.connect_phantom': {'uk': '👻 Підключити Phantom', 'en': '👻 Connect Phantom'},
    'bill.no_phantom': {'uk': 'Phantom не знайдено. Встановіть розширення або використайте ручне підключення.', 'en': 'Phantom not found. Install the extension or use manual connect.'},
    'bill.paste_sol_sig': {'uk': 'Вставте підпис (hex або base58)', 'en': 'Paste signature (hex or base58)'},
    'bill.solana_unverified_note': {'uk': 'ℹ️ Гаманець не підтверджено підписом — генерація недоступна. Перепідключіться через MetaMask або Phantom.', 'en': 'ℹ️ Wallet not verified by signature — generation disabled. Reconnect via MetaMask or Phantom.'},
    'bill.connect_hint': {'uk': 'Підключіть гаманець. EVM з балансом на Base — до {welcome} вітальних кредитів.', 'en': 'Connect a wallet. EVM with Base balance — up to {welcome} welcome credits.'},
    'billing.done': {'uk': 'Готово!', 'en': 'Done!'},
    'billing.done_credits': {'uk': 'Готово! −{cr} cr · залишок: **{balance}** cr', 'en': 'Done! −{cr} cr · balance: **{balance}** cr'},
    'billing.done_credits_short': {'uk': 'Готово! −{cr} cr', 'en': 'Done! −{cr} cr'},
    'billing.charged_suffix': {'uk': '−{cr} cr · залишок: **{balance}** cr', 'en': '−{cr} cr · balance: **{balance}** cr'},
    'billing.charged_suffix_short': {'uk': '−{cr} cr', 'en': '−{cr} cr'},
    'bill.history': {'uk': '**Історія операцій**', 'en': '**Transaction history**'},
    'bill.packages': {'uk': '**Пакети кредитів** · оплата USDC (Base) через Helio Pay', 'en': '**Credit packages** · pay USDC (Base) via Helio Pay'},
    'bill.buy': {'uk': '💸 Придбати через Helio Pay', 'en': '💸 Buy via Helio Pay'},
    'bill.sync': {'uk': '🔄 Перевірити оплату (опитати Helio)', 'en': '🔄 Check payment (poll Helio)'},
    'bill.costs': {'uk': '**Списання кредитів за двигунами**', 'en': '**Credit cost per engine**'},
    'bill.no_metamask': {'uk': 'MetaMask не знайдено. Встановіть розширення або скористайтесь ручним підключенням нижче.', 'en': 'MetaMask not found. Install the extension or use manual connect below.'},
    'bill.welcome_success': {'uk': '🎁 Нараховано вітальні кредити. Баланс: {balance}.', 'en': '🎁 Welcome credits applied. Balance: {balance}.'},
    'bill.registered_no_credits': {'uk': 'Гаманець зареєстровано. Вітальні кредити не нараховано (Sybil-перевірка балансу ETH на Base).', 'en': 'Wallet registered. No welcome credits (Sybil check: min ETH on Base).'},
    'bill.sig_mismatch': {'uk': 'Підпис не відповідає адресі гаманця.', 'en': 'Signature does not match wallet address.'},
    'bill.nonce_expired': {'uk': 'Nonce застарів. Спробуйте ще раз.', 'en': 'Nonce expired. Try again.'},
    'bill.connected_no_welcome': {'uk': 'Гаманець підключено без вітальних кредитів.', 'en': 'Connected without welcome credits.'},
    'bill.helio_missing': {'uk': 'Helio paylink не налаштовано (.env)', 'en': 'Helio paylink not configured (.env)'},
    'bill.helio_env_hint': {'uk': 'Додайте `HELIO_API_KEY`, `HELIO_API_SECRET`, `HELIO_PAYLINK_*` для автозарахування.', 'en': 'Add `HELIO_API_KEY`, `HELIO_API_SECRET`, `HELIO_PAYLINK_*` for auto-credit.'},
    'bill.payment_ok': {'uk': 'Зараховано {credited} кредитів ({new_tx} нових транзакцій).', 'en': 'Credited {credited} credits ({new_tx} new transactions).'},
    'bill.no_payments': {'uk': 'Нових платежів не знайдено.', 'en': 'No new payments found.'},
    'bill.test_topup': {'uk': '🧪 Тестове поповнення', 'en': '🧪 Test top-up'},
    'bill.package': {'uk': 'Пакет', 'en': 'Package'},
    'bill.simulate': {'uk': 'Імітувати платіж', 'en': 'Simulate payment'},
    'bill.balance_after': {'uk': 'Баланс: {balance}.', 'en': 'Balance: {balance}.'},
    'bill.col_engine': {'uk': 'Двигун', 'en': 'Engine'},
    'bill.col_credits': {'uk': 'Кредитів', 'en': 'Credits'},
    'ec.header.title': {'uk': '### 🎉 Колекція готова до експорту', 'en': '### 🎉 Your collection is ready to export'},
    'ec.header.subtitle': {
        'uk': 'Ми готуємо **mint-ready бандл** (ZIP / IPFS). On-chain мінт — на обраній платформі або через concierge; цей застосунок сам NFT не мінтить.',
        'en': 'We prepare a **mint-ready bundle** (ZIP / IPFS). On-chain minting is on your chosen platform or via concierge — this app does not mint NFTs itself.',
    },
    'ec.path.title': {'uk': '### Який шлях обрати?', 'en': '### Which path should I take?'},
    'ec.path.caption': {
        'uk': 'Спочатку оберіть рівень складності — платформа підставиться автоматично. Sugar/Metaplex — для розробників з CLI.',
        'en': 'Pick a difficulty first — the platform is pre-selected. Sugar/Metaplex are for developers with a CLI.',
    },
    'ec.path.evm_easy': {'uk': '🟢 EVM · Thirdweb', 'en': '🟢 EVM · Thirdweb'},
    'ec.path.evm_opensea': {'uk': '🟢 OpenSea Studio', 'en': '🟢 OpenSea Studio'},
    'ec.path.solana_dev': {'uk': '🛠 Solana · CLI', 'en': '🛠 Solana · CLI'},
    'ec.path.concierge': {'uk': '🛎️ Launch for you', 'en': '🛎️ Launch for you'},
    'ec.path.hint.evm_easy': {
        'uk': '**Рекомендовано для не-девів:** візуальний мінт на **Base** через thirdweb — без командного рядка.',
        'en': '**Recommended for non-devs:** visual mint on **Base** via thirdweb — no command line.',
    },
    'ec.path.hint.evm_opensea': {
        'uk': '**OpenSea Studio** — класичний візуальний дроп (потрібен IPFS / Pinata). Підходить, якщо хочете одразу маркетплейс.',
        'en': '**OpenSea Studio** — classic visual drop (needs IPFS / Pinata). Best if you want the marketplace immediately.',
    },
    'ec.path.hint.solana_dev': {
        'uk': '**Для розробників:** Candy Machine / Sugar CLI на вашому ПК. Зовнішнім не-девам краще Thirdweb або concierge.',
        'en': '**For developers:** Candy Machine / Sugar CLI on your machine. Non-devs should prefer Thirdweb or concierge.',
    },
    'ec.path.hint.concierge': {
        'uk': '**Під ключ:** ми деплоїмо колекцію за вас (Solana/EVM). Заповніть заявку нижче — оператор відповість на email.',
        'en': '**Turnkey:** we deploy the collection for you (Solana/EVM). Submit the form below — an operator replies by email.',
    },
    'ec.path.solana_dev_note': {
        'uk': 'Sugar ZIP позначено 🛠 — потрібні Phantom + SOL + встановлений Sugar CLI.',
        'en': 'Sugar ZIP is marked 🛠 — you need Phantom + SOL + Sugar CLI installed.',
    },
    'ec.card.solana_dev_only': {
        'uk': '⚠️ Цей шлях для розробників (CLI). Не-девам: Thirdweb / OpenSea або **Launch for you**.',
        'en': '⚠️ Developer path (CLI). Non-devs: Thirdweb / OpenSea or **Launch for you**.',
    },
    'ec.concierge.title': {'uk': '🛎️ We launch it for you', 'en': '🛎️ We launch it for you'},
    'ec.concierge.body': {
        'uk': 'Платна concierge-послуга: оператор деплоїть ваш mint-ready ZIP (як Genesis). Gas — окремо (pass-through). Залиште контакт — ми відповімо з оцінкою.',
        'en': 'Paid concierge: an operator deploys your mint-ready ZIP (same flow as Genesis). Gas is pass-through. Leave a contact — we reply with a quote.',
    },
    'ec.concierge.email': {'uk': 'Email для відповіді', 'en': 'Reply email'},
    'ec.concierge.chain': {'uk': 'Бажана мережа', 'en': 'Preferred chain'},
    'ec.concierge.chain.solana': {'uk': 'Solana (Candy Machine)', 'en': 'Solana (Candy Machine)'},
    'ec.concierge.chain.base': {'uk': 'Base / EVM (thirdweb)', 'en': 'Base / EVM (thirdweb)'},
    'ec.concierge.chain.other': {'uk': 'Інше / порадьте', 'en': 'Other / advise me'},
    'ec.concierge.supply': {'uk': 'Supply (0 = ще не вирішив)', 'en': 'Supply (0 = undecided)'},
    'ec.concierge.supply_help': {'uk': 'Орієнтовна кількість NFT у дропі.', 'en': 'Approximate NFT count in the drop.'},
    'ec.concierge.notes': {'uk': 'Нотатки (опційно)', 'en': 'Notes (optional)'},
    'ec.concierge.notes_ph': {'uk': 'Дедлайн, бюджет, посилання на ZIP…', 'en': 'Deadline, budget, ZIP link…'},
    'ec.concierge.submit': {'uk': 'Надіслати заявку', 'en': 'Submit request'},
    'ec.concierge.ok': {
        'uk': '✅ Заявку прийнято. Оператор напише на вказаний email.',
        'en': '✅ Request received. An operator will email you.',
    },
    'ec.concierge.err_email': {'uk': 'Вкажіть коректний email.', 'en': 'Enter a valid email.'},
    'ec.concierge.err_chain': {'uk': 'Оберіть мережу зі списку.', 'en': 'Pick a chain from the list.'},
    'ec.concierge.err_supply': {'uk': 'Supply має бути від 1 до 100000.', 'en': 'Supply must be between 1 and 100000.'},
    'ec.stat.total': {'uk': 'Активів', 'en': 'Assets'},
    'ec.stat.ready': {'uk': 'Зі зображенням', 'en': 'With image'},
    'ec.stat.export': {'uk': 'Готово до ZIP', 'en': 'Ready for ZIP'},
    'ec.incomplete_warn': {'uk': '⚠️ Схвалено **{approved}** із **{planned}** запланованих. Зберете ZIP неповним дропом — погенеруйте/схваліть решту на Етапі 2, якщо це не навмисно.', 'en': "⚠️ Approved **{approved}** of **{planned}** planned. You'll build a partial drop — generate/approve the rest on Stage 2 unless this is intentional."},
    'ec.qc_banner': {
        'uk': '💡 Перед ZIP/IPFS: розгорніть **NFT Quality Checklist** нижче — безкоштовний score 0–100 + опційний AI deep dive (деталі — **📖 Довідка § 4.4.1**).',
        'en': '💡 Before ZIP/IPFS: open **NFT Quality Checklist** below — free 0–100 score + optional AI deep dive (details — **📖 Help § 4.4.1**).',
    },
    'ec.qc_gate_warn': {
        'uk': '⚠️ QC score **{score}/100** — рекомендуємо виправити попередження в чек-листі перед публікацією (експорт не блокується).',
        'en': '⚠️ QC score **{score}/100** — we recommend fixing checklist warnings before going public (export is not blocked).',
    },
    'ec.qc_gate_low': {
        'uk': '🔶 QC score **{score}/100** — високий ризик для маркетплейсу; перегляньте чек-лист і rarity report.',
        'en': '🔶 QC score **{score}/100** — high marketplace risk; review the checklist and rarity report.',
    },
    'ec.preflight_qc_btn': {'uk': '→ QC', 'en': '→ QC'},
    'ec.naming.title': {'uk': '✏️ Collection naming (EN)', 'en': '✏️ Collection naming (EN)'},
    'ec.naming.caption': {'uk': 'Mint-ready назви токенів і спільний опис з hashtags — одним кліком.', 'en': 'Mint-ready token names and a shared description with hashtags — one click.'},
    'ec.naming.brand': {'uk': 'Бренд / назва колекції', 'en': 'Brand / collection name'},
    'ec.naming.tagline': {'uk': 'Короткий lead (EN, опційно)', 'en': 'Short lead line (EN, optional)'},
    'ec.naming.tagline_ph': {'uk': 'Cyber owls exploring neon cities…', 'en': 'Cyber owls exploring neon cities…'},
    'ec.naming.hashtags': {'uk': 'Hashtags', 'en': 'Hashtags'},
    'ec.naming.hashtags_help': {'uk': '3–5 тегів для опису; кнопка «Заповнити» підставить шаблон.', 'en': '3–5 tags for the description; Fill template inserts defaults.'},
    'ec.naming.fill_tags': {'uk': 'Заповнити hashtags', 'en': 'Fill hashtags'},
    'ec.naming.preview': {'uk': 'Приклад токена: **{example}**', 'en': 'Token example: **{example}**'},
    'ec.naming.apply': {'uk': 'Застосувати до всіх {n} NFT', 'en': 'Apply to all {n} NFTs'},
    'ec.naming.applied': {'uk': '✅ Назви та опис оновлено для {n} токенів.', 'en': '✅ Names and description updated for {n} tokens.'},
    'ec.naming.need_brand': {'uk': 'Вкажіть назву колекції (поле вище або тут).', 'en': 'Enter a collection name (field above or here).'},
    'ec.upscale_nudge': {
        'uk': '💡 Середня роздільність < {target}px — увімкніть **Upscale до 2048** нижче або в QC (див. upscale hint).',
        'en': '💡 Average resolution < {target}px — enable **Upscale to 2048** below or see QC upscale hint.',
    },
    'ec.rarity.skew_warn': {
        'uk': '⚠️ **Rarity skew:** trait **{category} / {trait}** зустрічається у **{pct}%** supply — розгляньте баланс traits на Етапі 1.',
        'en': '⚠️ **Rarity skew:** trait **{category} / {trait}** appears in **{pct}%** of supply — consider rebalancing traits on Stage 1.',
    },
    'ec.structure.title': {'uk': '📂 Що буде в архіві', 'en': "📂 What's in the archive"},
    'ec.structure.caption': {'uk': 'Структура ZIP для обраної платформи (імена за фактичною індексацією).', 'en': 'ZIP structure for the selected platform (names follow the actual indexing).'},
    'ec.pick_platform': {'uk': '**Платформа для мінту**', 'en': '**Mint platform**'},
    'ec.card.thirdweb': {'uk': 'Thirdweb (Base)', 'en': 'Thirdweb (Base)'},
    'ec.card.opensea': {'uk': 'OpenSea', 'en': 'OpenSea'},
    'ec.card.metaplex': {'uk': 'Metaplex · Solana', 'en': 'Metaplex · Solana'},
    'ec.card.solana_me_hint': {'uk': 'Сумісно з **Magic Eden** після `sugar deploy` (Launchpad — окрема заявка на ME).', 'en': '**Magic Eden** compatible after `sugar deploy` (Launchpad requires a separate ME application).'},
    'ec.card.generic': {'uk': 'Generic', 'en': 'Generic'},
    'ec.card.w3ir': {'uk': 'W3IR Platform', 'en': 'W3IR Platform'},
    'ec.build.w3ir': {'uk': '📦 Зібрати .w3ir-nft.zip', 'en': '📦 Build .w3ir-nft.zip'},
    'ec.guide_title': {'uk': '📖 Як мінтити на цій платформі', 'en': '📖 How to mint on this platform'},
    'ec.zip.readme.header': {'uk': 'Згенеровано NFT Prompt Builder (ai.w3ir.io). Бандл готовий до мінту — застосунок сам мінт не проводить.', 'en': 'Generated by NFT Prompt Builder (ai.w3ir.io). Mint-ready bundle — this app does not mint on-chain.'},
    'ec.zip.readme.ipfs': {'uk': '── IPFS (mint-ready) ──\nbaseURI (metadata): {base_uri}\nImages base:        {image_base_uri}\nДеталі — ipfs-manifest.json у корені ZIP.\nMetadata у ZIP уже містить ipfs:// посилання.', 'en': '── IPFS (mint-ready) ──\nbaseURI (metadata): {base_uri}\nImages base:        {image_base_uri}\nDetails — ipfs-manifest.json at the ZIP root.\nMetadata in the ZIP already uses ipfs:// links.'},
    'ec.zip.readme.w3ir_technical': {'uk': "── Структура пакета ──\nbatch-manifest.json + items/item-N/{manifest.json, mint-state.json, asset/<file>}.\nmetadata.json — лише офлайн-прев'ю; платформа будує метадані з mint-state при мінті.", 'en': '── Package layout ──\nbatch-manifest.json + items/item-N/{manifest.json, mint-state.json, asset/<file>}.\nmetadata.json is offline preview only; the platform builds on-chain metadata from mint-state.'},
    'ec.zip.readme.sugar_technical': {'uk': '── Sugar / config ──\nuploadMethod=bundlr (платить SOL). Для Pinata-аплоуду впишіть свій JWT у config.json → pinataConfig самостійно.', 'en': '── Sugar / config ──\nuploadMethod=bundlr (pays SOL). For Pinata upload, set your JWT in config.json → pinataConfig yourself.'},
    'ec.zip.readme.sugar_allowlist': {'uk': 'Whitelist: відредагуйте allowlist.json і застосуйте через `sugar guard add`.', 'en': 'Whitelist: edit allowlist.json and apply via `sugar guard add`.'},
    'ec.guide_intro': {'uk': "### Спочатку головне\n**Цей застосунок сам NFT не мінтить.** Він готує картинки та файли-описи (metadata). **Мінт** — це коли NFT з'являється в блокчейні: ви підключаєте гаманець на іншому сайті і підтверджуєте транзакцію (за це стягується невелика комісія мережі — **gas**).\n\n### Що вже зроблено тут\n1. Згенеровано зображення колекції.\n2. Підготовлено metadata (назва, опис, трейти — англійською).\n3. Зібрано ZIP або відвантажено на IPFS (якщо натиснули кнопку IPFS).\n\n### Що робити далі (загальна схема)\n1. Завантажити файли на обрану платформу мінту.\n2. Підключити гаманець (MetaMask — для Base/Ethereum, Phantom — для Solana).\n3. Створити колекцію або дроп і натиснути **Mint** / **Publish**.\n4. Перевірити NFT у гаманці та на маркетплейсі.\n\n**Безпека:** ніколи не вводьте **seed phrase** (12–24 слова). Лише **Connect wallet** на офіційному сайті платформи.", 'en': "### First things first\n**This app does not mint NFTs by itself.** It prepares images and metadata files. **Minting** is when an NFT appears on-chain: you connect a wallet on another site and confirm a transaction (a small **gas** network fee applies).\n\n### What is already done here\n1. Collection images were generated.\n2. Metadata was prepared (name, description, traits — in English).\n3. A ZIP was built or uploaded to IPFS (if you used the IPFS button).\n\n### What to do next (general flow)\n1. Upload the files to your chosen mint platform.\n2. Connect a wallet (MetaMask for Base/Ethereum, Phantom for Solana).\n3. Create a collection or drop and click **Mint** / **Publish**.\n4. Check the NFTs in your wallet and on the marketplace.\n\n**Security:** never enter your **seed phrase** (12–24 words). Only use **Connect wallet** on the platform's official site."},
    'ec.guide.thirdweb': {'uk': "### Для кого цей формат\nНайпростіший шлях для **Base** (мережа Ethereum від Coinbase). Підходить, якщо у вас гаманець MetaMask або Coinbase Wallet.\n\n### Що знадобиться\n- ZIP з цього Export Center (кнопка **Зібрати ZIP**).\n- Акаунт на [thirdweb.com](https://thirdweb.com) (безкоштовна реєстрація).\n- Трохи **ETH на Base** для gas (зазвичай копійки за NFT).\n\n### Покроково\n1. **Завантажте ZIP** — кнопка «Завантажити ZIP» тут або збережіть файл на комп'ютер.\n2. Відкрийте **thirdweb Dashboard** → розділ **NFTs** → **Batch Upload** (масове завантаження).\n3. Перетягніть ZIP або оберіть файл. thirdweb сам розпізнає `images/` і `metadata.csv`.\n4. Оберіть мережу **Base** і підключіть гаманець (**Connect wallet**).\n5. Перегляньте preview — чи правильні назви та картинки.\n6. Натисніть **Lazy mint** або **Mint** — одна транзакція може покрити всю колекцію (batch mint, дешевше за gas).\n7. Після підтвердження в гаманці NFT з'являться у вашому акаунті thirdweb і на Base.\n\n### Якщо ви вже відвантажили на IPFS\nМожна не завантажувати ZIP повторно: у thirdweb вкажіть `metadata.csv` + папку `images/` з IPFS-експорту — головне, щоб посилання `ipfs://…` у metadata вели на ваші картинки.\n\n### Типові помилки\n- **Немає ETH на Base** — поповніть гаманець через міст (bridge) з Ethereum або купіть на біржі.\n- **Неправильна мережа в MetaMask** — перемкніть на Base Mainnet.\n- **Порожні картинки в preview** — спочатку завантажте images на IPFS, потім metadata.", 'en': "### Who this format is for\nThe easiest path for **Base** (Coinbase's Ethereum L2). Works well with MetaMask or Coinbase Wallet.\n\n### What you need\n- A ZIP from this Export Center (**Build ZIP** button).\n- An account at [thirdweb.com](https://thirdweb.com) (free signup).\n- A little **ETH on Base** for gas (usually cents per NFT).\n\n### Step by step\n1. **Download the ZIP** — use the button here or save the file locally.\n2. Open **thirdweb Dashboard** → **NFTs** → **Batch Upload**.\n3. Drag the ZIP or pick the file. thirdweb reads `images/` and `metadata.csv` automatically.\n4. Select **Base** and connect your wallet (**Connect wallet**).\n5. Review the preview — names and images should look correct.\n6. Click **Lazy mint** or **Mint** — one transaction can cover the whole collection (batch mint, cheaper gas).\n7. After confirming in your wallet, NFTs appear in thirdweb and on Base.\n\n### If you already uploaded to IPFS\nYou do not have to re-upload the ZIP: point thirdweb at `metadata.csv` + `images/` from the IPFS export — metadata `ipfs://…` links must resolve to your images.\n\n### Common mistakes\n- **No ETH on Base** — bridge from Ethereum or buy on an exchange.\n- **Wrong MetaMask network** — switch to Base Mainnet.\n- **Empty preview images** — upload images to IPFS first, then metadata."},
    'ec.guide.opensea': {'uk': "### Для кого цей формат\nКласичний шлях для **OpenSea** (Ethereum, Base, Polygon та ін.). NFT з'являються на найбільшому маркетплейсі.\n\n### Що знадобиться\n- Гаманець MetaMask (або інший EVM-гаманець).\n- Акаунт на [OpenSea](https://opensea.io) і [OpenSea Studio](https://studio.opensea.io).\n- **Pinata** — сервіс зберігання файлів у IPFS (JWT можна ввести тут при експорті).\n- ETH (або інша монета мережі) для gas при створенні дропу.\n\n### Покроково\n1. **Тут, у Export Center:** натисніть **Відвантажити в IPFS** (або спочатку ZIP, потім вручну на pinata.cloud). Дочекайтесь двох кроків: картинки → metadata.\n2. **Скопіюйте baseURI** — рядок виду `ipfs://Qm…/` (кнопка копіювання з'явиться після успішного IPFS). Це адреса папки з metadata.\n3. Відкрийте **OpenSea Studio** → **Create** → **Drop** (або Collection).\n4. Підключіть гаманець тією мережею, де хочете дроп (наприклад **Base**).\n5. У полі **Base URI** / **Metadata** вставте скопійований `ipfs://…`.\n6. Вкажіть назву колекції, ціну мінту (або безкоштовно), дату старту.\n7. Перегляньте **preview** кожного NFT — картинки та описи мають відображатись.\n8. Натисніть **Publish** / **Create drop** і підтвердіть транзакцію в гаманці.\n9. Після публікації дроп з'явиться на opensea.io — поділіться посиланням.\n\n### Простими словами про IPFS\nIPFS — це «де зберігаються файли NFT». OpenSea не тримає ваші картинки на своєму сервері — він читає їх з IPFS за посиланням у metadata. Тому спочатку завантажуємо файли (Pinata), потім даємо OpenSea лише посилання.\n\n### Типові помилки\n- **Preview без картинок** — metadata завантажено раніше за images; повторіть IPFS-експорт.\n- **Інша мережа** — baseURI працює, але гаманець на Polygon, а дроп на Base.\n- **Забули royalty** — в OpenSea Studio можна задати відсоток вторинних продажів.", 'en': "### Who this format is for\nThe classic path for **OpenSea** (Ethereum, Base, Polygon, etc.). NFTs appear on the largest marketplace.\n\n### What you need\n- MetaMask (or another EVM wallet).\n- Accounts on [OpenSea](https://opensea.io) and [OpenSea Studio](https://studio.opensea.io).\n- **Pinata** for IPFS storage (you can enter a JWT here during export).\n- ETH (or the chain's native coin) for gas when creating the drop.\n\n### Step by step\n1. **Here in Export Center:** click **Upload to IPFS** (or build a ZIP and upload manually at pinata.cloud). Wait for both steps: images → metadata.\n2. **Copy the baseURI** — a string like `ipfs://Qm…/` (copy button appears after IPFS succeeds). This is your metadata folder address.\n3. Open **OpenSea Studio** → **Create** → **Drop** (or Collection).\n4. Connect the wallet on the chain you want (e.g. **Base**).\n5. Paste the copied `ipfs://…` into **Base URI** / **Metadata**.\n6. Set collection name, mint price (or free), and start date.\n7. Review **preview** for each NFT — images and descriptions should show.\n8. Click **Publish** / **Create drop** and confirm in your wallet.\n9. After publishing, the drop appears on opensea.io — share the link.\n\n### IPFS in plain language\nIPFS is where NFT files live. OpenSea does not host your images — it reads them from IPFS via links in metadata. Upload files first (Pinata), then give OpenSea the link.\n\n### Common mistakes\n- **Preview without images** — metadata uploaded before images; redo the IPFS export.\n- **Wrong network** — baseURI works but wallet is on Polygon while drop is on Base.\n- **Forgot royalties** — set secondary sale percentage in OpenSea Studio."},
    'ec.guide.metaplex': {'uk': "### Для кого цей формат\n**Solana** — швидка і дешева мережа. Формат Metaplex підходить для Candy Machine через інструмент **Sugar CLI** (для тих, хто готовий до командного рядка або слідує гайду розробника).\n\n### Що знадобиться\n- ZIP з папкою `assets/` (`0.png`, `0.json`, `1.png`, `1.json`, …).\n- Гаманець **Phantom** (або Solflare) з трохи **SOL** на комісії.\n- Встановлений [Sugar CLI](https://developers.metaplex.com/tools/sugar) на комп'ютері.\n- Поля **Symbol**, **Royalty** і **Creator** заповнені вище в Export Center.\n\n### Покроково\n1. **Завантажте ZIP** і розпакуйте в окрему теку на комп'ютері.\n2. Відкрийте термінал у цій теці.\n3. `sugar validate` — перевірка: чи всі файли на місці, чи JSON валідні.\n4. `sugar upload` — завантаження картинок і metadata в Arweave/IPFS (потрібен SOL).\n5. `sugar deploy` — створення Candy Machine у блокчейні Solana.\n6. Підключіть Phantom — підтвердіть транзакції, коли Sugar попросить.\n7. Після deploy отримаєте адресу Candy Machine — її можна дати колекторям для мінту.\n8. **Magic Eden:** після старту мінту NFT з'являються на [Magic Eden](https://magiceden.io) для стандартних Candy Machine. Окремий **Launchpad**-дроп — заявка на сайті ME; w3ir.io її не подає.\n\n### Простими словами\nКожен NFT — пара файлів: картинка `.png` і опис `.json` з однаковим номером. Sugar завантажує їх у мережу і створює «автомат мінту», з якого люди купують NFT.\n\n### Типові помилки\n- **Недостатньо SOL** — поповніть гаманець (≈0.5–2 SOL залежно від розміру колекції).\n- **Порожній creator** — вкажіть Solana-адресу у полі Creator перед збіркою ZIP.\n- **Назва > 32 символів** — Metaplex обрізає; скоротіть у metadata.", 'en': '### Who this format is for\n**Solana** — fast and low-fee. Metaplex format works with **Sugar CLI** (for those comfortable with a terminal or following a developer guide).\n\n### What you need\n- A ZIP with an `assets/` folder (`0.png`, `0.json`, `1.png`, `1.json`, …).\n- A **Phantom** (or Solflare) wallet with some **SOL** for fees.\n- [Sugar CLI](https://developers.metaplex.com/tools/sugar) installed locally.\n- **Symbol**, **Royalty**, and **Creator** filled in above in Export Center.\n\n### Step by step\n1. **Download the ZIP** and unzip to a folder on your computer.\n2. Open a terminal in that folder.\n3. `sugar validate` — checks files and JSON.\n4. `sugar upload` — uploads images and metadata (costs SOL).\n5. `sugar deploy` — creates the Candy Machine on Solana.\n6. Connect Phantom and confirm when Sugar prompts.\n7. After deploy you get a Candy Machine address for collectors to mint from.\n8. **Magic Eden:** once minting starts, NFTs appear on [Magic Eden](https://magiceden.io) for standard Candy Machines. A featured **Launchpad** drop requires a separate application on ME; w3ir.io does not submit it.\n\n### In plain language\nEach NFT is a pair: a `.png` image and a `.json` file with the same number. Sugar uploads them and creates a mint machine collectors buy from.\n\n### Common mistakes\n- **Not enough SOL** — top up the wallet (roughly 0.5–2 SOL depending on size).\n- **Empty creator** — set a Solana address in Creator before building the ZIP.\n- **Name > 32 chars** — Metaplex may truncate; shorten in metadata.'},
    'ec.guide.generic': {'uk': '### Для кого цей формат\nУніверсальний ZIP — якщо ви передаєте колекцію **розробнику**, іншому сервісу або ще не обрали платформу мінту.\n\n### Що всередині ZIP\n- `images/` — усі картинки NFT.\n- `metadata/` — JSON-файли з назвами, описами та трейтами.\n- `collection.json` — загальна інформація про колекцію.\n- `README.txt` — коротка підказка для того, хто імпортує.\n\n### Покроково\n1. **Завантажте ZIP** і (за бажанням) розпакуйте — переконайтесь, що кількість картинок = кількості JSON-файлів.\n2. **Завантажте на IPFS** (Pinata, NFT.Storage або інший сервіс) — спочатку images, потім оновіть посилання в metadata і завантажте metadata.\n3. Передайте **baseURI** (`ipfs://…/`) тому, хто налаштовує смарт-контракт або дроп.\n4. Мінт проводиться **на обраній платформі** (thirdweb, OpenSea, власний контракт) — цей ZIP лише готує файли.\n\n### Порада для початківців\nЯкщо не впевнені — оберіть замість Generic формат **Thirdweb** або **OpenSea**: у них є візуальні інтерфейси без програміста.', 'en': "### Who this format is for\nA universal ZIP when handing the collection to a **developer**, another service, or before you have chosen a mint platform.\n\n### What's inside the ZIP\n- `images/` — all NFT images.\n- `metadata/` — JSON files with names, descriptions, and traits.\n- `collection.json` — collection-level info.\n- `README.txt` — a short note for whoever imports it.\n\n### Step by step\n1. **Download the ZIP** and optionally unzip — image count should match JSON count.\n2. **Upload to IPFS** (Pinata, NFT.Storage, etc.) — images first, then update links in metadata and upload metadata.\n3. Pass the **baseURI** (`ipfs://…/`) to whoever sets up the contract or drop.\n4. Minting happens **on the chosen platform** — this ZIP only prepares files.\n\n### Tip for beginners\nIf unsure, pick **Thirdweb** or **OpenSea** instead of Generic — they have visual UIs without a developer."},
    'ec.guide.w3ir': {
        'uk': '### Для кого цей формат\nПакет **`.w3ir-nft.zip`** для майбутньої **мінт-платформи W3IR** (імпорт колекції в один крок). Це **не** те саме, що публічний [mint.w3ir.io](https://mint.w3ir.io) сьогодні.\n\n### Живий Genesis (зараз)\n**W3IR Genesis Avatar** уже на Solana через **Candy Machine** — оберіть платформу **🍬 Candy Machine · Solana**, зберіть ZIP і деплойте за `C:\\Sugar\\docs\\DROP_FROM_PROMPT.md`. Мінт: [mint.w3ir.io](https://mint.w3ir.io).\n\n### Коли з’явиться W3IR import\n1. **Зібрати .w3ir-nft.zip** тут.\n2. Імпорт на W3IR mint-платформі (окремий продукт).\n3. Preview → мінт за інструкціями платформи.\n\n### Якщо потрібен мінт уже зараз\nОберіть **Candy Machine · Solana** (Solana) або **Thirdweb** / **OpenSea** (EVM) — не W3IR ZIP.',
        'en': '### Who this format is for\nA **`.w3ir-nft.zip`** pack for the future **W3IR mint platform** (one-step collection import). This is **not** the same as public [mint.w3ir.io](https://mint.w3ir.io) today.\n\n### Live Genesis (now)\n**W3IR Genesis Avatar** is already on Solana via **Candy Machine** — pick **🍬 Candy Machine · Solana**, build the ZIP, deploy per `C:\\Sugar\\docs\\DROP_FROM_PROMPT.md`. Mint: [mint.w3ir.io](https://mint.w3ir.io).\n\n### When W3IR import ships\n1. **Build .w3ir-nft.zip** here.\n2. Import on the W3IR mint platform (separate product).\n3. Preview → mint per platform instructions.\n\n### If you need to mint now\nChoose **Candy Machine · Solana** (Solana) or **Thirdweb** / **OpenSea** (EVM) — not the W3IR ZIP.',
    },
    'ec.card.sugar': {'uk': 'Candy Machine · Solana', 'en': 'Candy Machine · Solana'},
    'ec.build.sugar': {'uk': '🍬 Зібрати Candy Machine ZIP', 'en': '🍬 Build Candy Machine ZIP'},
    'ec.guide.sugar': {'uk': "### Для кого цей формат\n**Solana Candy Machine** — професійний дроп з ціною, датами, whitelist. ZIP уже містить `assets/`, `config.json` і (за потреби) guards — менше ручної роботи, ніж у базовому Metaplex.\n\n### Що знадобиться\n- ZIP з кнопки **Зібрати Candy Machine ZIP**.\n- Гаманець **Phantom** з **SOL** (зазвичай 1–3 SOL на deploy + upload).\n- [Sugar CLI](https://developers.metaplex.com/tools/sugar) на комп'ютері.\n- Адреса **Creator (Solana)** заповнена вище; опційно — ціна, дати, whitelist у блоці Guards.\n\n### Покроково\n1. **Завантажте ZIP** і розпакуйте в окрему теку.\n2. У терміналі: `sugar validate` — переконайтесь, що помилок немає.\n3. `sugar deploy` — завантажує `assets/` і створює Candy Machine (підписуйте в Phantom).\n4. Якщо ви задали guards (ціна, старт, whitelist): `sugar guard add` — застосує налаштування з `config.json`.\n5. Збережіть **адресу Candy Machine** — її дають колекторам для мінту.\n6. Перевірте дроп на [solscan.io](https://solscan.io) за цією адресою.\n7. **Magic Eden:** після старту мінту колекція з'явиться на [Magic Eden](https://magiceden.io). Launchpad — окрема заявка на ME.\n\n### Живий приклад\nКолекція, зроблена цим інструментом і запущена на Solana: **[W3IR Genesis Avatar](https://mint.w3ir.io)** (`mint.w3ir.io`) — 50 NFT, random Candy Machine.\n\n### Guards простими словами\n- **Ціна** — скільки SOL платить колектор за 1 NFT (0 = безкоштовно).\n- **Старт / кінець** — коли мінт відкритий.\n- **Whitelist** — список адрес, які можуть мінтити раніше або дешевше.\n\n### Безпека\nУсі транзакції підписує **ваш** гаманець. Seed phrase нікому не показуйте. Ключі на сервері w3ir.io **не зберігаються**.\n\n### Типові помилки\n- **Creator порожній** — заповніть поле Solana-адреси перед збіркою ZIP.\n- **`sugar: command not found`** — встановіть Sugar і перезапустіть термінал.\n- **Insufficient funds** — поповніть SOL у Phantom.", 'en': '### Who this format is for\n**Solana Candy Machine** — a pro drop with price, dates, and whitelist. The ZIP already includes `assets/`, `config.json`, and optional guards — less manual work than basic Metaplex.\n\n### What you need\n- A ZIP from **Build Candy Machine ZIP**.\n- A **Phantom** wallet with **SOL** (often 1–3 SOL for deploy + upload).\n- [Sugar CLI](https://developers.metaplex.com/tools/sugar) on your computer.\n- **Creator (Solana)** filled in above; optionally price, dates, whitelist in Guards.\n\n### Step by step\n1. **Download the ZIP** and unzip to a folder.\n2. In a terminal: `sugar validate` — fix any errors.\n3. `sugar deploy` — uploads `assets/` and creates the Candy Machine (sign in Phantom).\n4. If you set guards (price, start, whitelist): `sugar guard add` applies `config.json`.\n5. Save the **Candy Machine address** for collectors to mint from.\n6. Verify the drop on [solscan.io](https://solscan.io) with that address.\n7. **Magic Eden:** once minting starts, the collection appears on [Magic Eden](https://magiceden.io). Launchpad requires a separate ME application.\n\n### Live example\nA collection made with this tool and launched on Solana: **[W3IR Genesis Avatar](https://mint.w3ir.io)** (`mint.w3ir.io`) — 50 NFTs, random Candy Machine.\n\n### Guards in plain language\n- **Price** — SOL per NFT (0 = free).\n- **Start / end** — when minting is open.\n- **Whitelist** — addresses that can mint early or cheaper.\n\n### Security\nAll transactions are signed by **your** wallet. Never share your seed phrase. No keys are stored on w3ir.io servers.\n\n### Common mistakes\n- **Empty creator** — set a Solana address before building the ZIP.\n- **`sugar: command not found`** — install Sugar and restart the terminal.\n- **Insufficient funds** — add SOL to Phantom.'},
    'ec.candy.guards_title': {'uk': '🛡 Guards (опційно)', 'en': '🛡 Guards (optional)'},
    'ec.candy.price': {'uk': 'Ціна, SOL (0 = безкоштовно)', 'en': 'Price, SOL (0 = free)'},
    'ec.candy.treasury': {'uk': 'Гаманець для оплати (treasury)', 'en': 'Payment wallet (treasury)'},
    'ec.candy.treasury_help': {'uk': 'Куди йде SOL за мінт. Порожнє → береться адреса creator.', 'en': 'Where mint SOL goes. Empty → falls back to the creator address.'},
    'ec.candy.start': {'uk': 'Старт мінту (ISO)', 'en': 'Mint start (ISO)'},
    'ec.candy.end': {'uk': 'Кінець мінту (ISO)', 'en': 'Mint end (ISO)'},
    'ec.candy.limit': {'uk': 'Ліміт на гаманець (0 = без ліміту)', 'en': 'Per-wallet limit (0 = unlimited)'},
    'ec.candy.allowlist': {'uk': 'Whitelist-адреси (по одній на рядок)', 'en': 'Whitelist addresses (one per line)'},
    'ec.candy.allowlist_help': {'uk': 'Записуються в allowlist.json; merkleRoot додається кроком `sugar guard add`.', 'en': 'Written to allowlist.json; merkleRoot is added via `sugar guard add`.'},
    'ec.candy.creator_required': {'uk': 'Candy Machine потребує адресу creator (Solana) — заповніть поле вище.', 'en': 'Candy Machine requires a creator address (Solana) — fill the field above.'},
    'ec.issue.no_assets': {'uk': 'Немає активів для експорту.', 'en': 'No assets to export.'},
    'ec.issue.missing_image': {'uk': 'Токен #{n}: немає зображення.', 'en': 'Token #{n}: missing image.'},
    'ec.issue.empty_description': {'uk': 'Токен #{n}: порожній опис (рекомендовано заповнити).', 'en': 'Token #{n}: empty description (recommended to fill).'},
    'ec.issue.name_too_long': {'uk': 'Токен #{n}: назва > 32 символів (Metaplex обрізає).', 'en': 'Token #{n}: name > 32 chars (Metaplex may truncate).'},
    'ec.issue.low_curator_rating': {'uk': 'Токен #{n}: рейтинг куратора нижче мінімуму для експорту.', 'en': 'Token #{n}: curator rating below export minimum.'},
    'ec.issue.corrupt_image': {'uk': 'Токен #{n}: зображення пошкоджене або занадто мале.', 'en': 'Token #{n}: image corrupt or too small.'},
    'ec.issue.duplicate_prompt': {'uk': 'Токен #{n}: дублікат промпту (можлива колізія metadata).', 'en': 'Token #{n}: duplicate prompt (possible metadata collision).'},
    'ec.issue.non_english': {'uk': 'Токен #{n}: не-англійський текст у трейтах/промпті — буде транслітеровано (продукт лише EN).', 'en': 'Token #{n}: non-English text in traits/prompt — will be transliterated (product is EN-only).'},
    'ec.min_rating': {'uk': 'Мін. рейтинг куратора для експорту', 'en': 'Min curator rating to export'},
    'ec.min_rating_help': {'uk': '0 = без фільтра. 4+ — лише схвалені високою оцінкою.', 'en': '0 = no filter. 4+ = only highly rated approvals.'},
    'ec.export.upscale': {'uk': 'Upscale до 2048px (LANCZOS) перед ZIP/IPFS', 'en': 'Upscale to 2048px (LANCZOS) before ZIP/IPFS'},
    'ec.export.upscale_help': {'uk': 'Плавне збільшення малих зображень для маркетплейсу. Потребує Pillow на сервері.', 'en': 'Smooth upscaling for marketplace display. Requires Pillow on the server.'},
    'ec.ipfs.title': {'uk': 'Завантажити на IPFS (Pinata)', 'en': 'Upload to IPFS (Pinata)'},
    'ec.ipfs.flow': {'uk': '**Оптимально:** спочатку **IPFS** (baseURI для контракту) — ZIP з `ipfs-manifest.json` збереться автоматично.', 'en': '**Recommended:** **IPFS** first (contract baseURI) — ZIP with `ipfs-manifest.json` is built automatically.'},
    'ec.ipfs.zip_ready': {'uk': '📦 Mint ZIP готовий (ліворуч) — metadata з `ipfs://`, плюс `ipfs-manifest.json`.', 'en': '📦 Mint ZIP ready (left) — metadata with `ipfs://` plus `ipfs-manifest.json`.'},
    'ec.ipfs.download_manifest': {'uk': '⬇️ ipfs-manifest.json', 'en': '⬇️ ipfs-manifest.json'},
    'ec.zip.hint_local': {'uk': 'Локальний ZIP (відносні шляхи). Для on-chain мінту спочатку натисніть **IPFS**.', 'en': 'Local ZIP (relative paths). For on-chain mint, click **IPFS** first.'},
    'ec.zip.hint_ipfs': {'uk': 'ZIP містить ті самі `ipfs://` metadata + `ipfs-manifest.json` (резервна копія).', 'en': 'ZIP includes matching `ipfs://` metadata + `ipfs-manifest.json` (backup).'},
    'ec.ipfs.base_uri': {'uk': 'baseURI для контракту (metadata):', 'en': 'baseURI for contract (metadata):'},
    'ec.ipfs.images_uri': {'uk': 'База зображень:', 'en': 'Images base:'},
    'ec.ipfs.w3ir_hint': {'uk': 'Для W3IR Platform використовуйте .w3ir-nft.zip (IPFS — через OpenSea/generic).', 'en': 'For W3IR Platform use .w3ir-nft.zip (IPFS via OpenSea/generic).'},
    'ec.ipfs.sugar_hint': {'uk': 'Candy Machine завантажує assets сам при `sugar deploy` — окремий IPFS не потрібен.', 'en': 'Candy Machine uploads assets itself on `sugar deploy` — no separate IPFS needed.'},
    'ec.ipfs.mode.label': {'uk': 'Хто пінить у IPFS', 'en': 'Who pins to IPFS'},
    'ec.ipfs.mode.platform': {'uk': 'W3IR Pinata (включено)', 'en': 'W3IR Pinata (included)'},
    'ec.ipfs.mode.own': {'uk': 'Мій Pinata', 'en': 'My Pinata'},
    'ec.ipfs.mode.platform_help': {'uk': 'Пінимо через акаунт W3IR — безкоштовно для вас, контент публічний на IPFS.', 'en': 'Pinned via the W3IR account — free for you; content is public on IPFS.'},
    'ec.ipfs.mode.own_help': {'uk': 'Ваш JWT з [pinata.cloud](https://pinata.cloud) — піни й оплата на вашому акаунті.', 'en': 'Your JWT from [pinata.cloud](https://pinata.cloud) — pins and billing on your account.'},
    'ec.ipfs.platform_paid_only': {'uk': 'W3IR Pinata доступний після поповнення кредитів. Або введіть свій Pinata JWT, або зберіть лише ZIP.', 'en': 'W3IR Pinata is available after topping up credits. Enter your own Pinata JWT, or build ZIP only.'},
    'ec.ipfs.no_platform_key': {'uk': 'Спільний Pinata на сервері не налаштовано — потрібен ваш JWT або лише ZIP.', 'en': 'No shared Pinata on the server — use your JWT or ZIP only.'},
    'ec.ipfs.jwt_required': {'uk': 'Введіть Pinata JWT або оберіть W3IR Pinata (якщо доступно).', 'en': 'Enter a Pinata JWT or choose W3IR Pinata (if available).'},
    'ec.rarity.title': {'uk': '📊 Rarity Report', 'en': '📊 Rarity Report'},
    'ec.rarity.empty': {'uk': 'Немає traits у черзі — звіт зʼявиться після generative/matrix колекції.', 'en': 'No traits in queue — report appears after a generative/matrix collection.'},
    'ec.rarity.rank_caption': {'uk': 'Рейтинг токенів (1 = найрідкісніший за score)', 'en': 'Token rankings (1 = rarest by score)'},
    'ec.rarity.trait_caption': {'uk': 'Частота traits у колекції', 'en': 'Trait frequency in collection'},
    'ec.rarity.download_md': {'uk': '⬇️ Завантажити rarity-report.md', 'en': '⬇️ Download rarity-report.md'},
    'meta.standard': {'uk': 'Стандарт', 'en': 'Standard'},
    'meta.name': {'uk': 'Назва колекції (EN, для мінту)', 'en': 'Collection name (EN, for mint)'},
    'meta.desc': {'uk': 'Опис колекції (EN)', 'en': 'Collection description (EN)'},
    'meta.base_uri': {'uk': 'Base URI зображень', 'en': 'Images base URI'},
    'meta.base_uri_help': {'uk': 'Префікс до файлів зображень. Порожньо — буде «<id>.png».', 'en': 'Prefix for image files. Empty — defaults to «<id>.png».'},
    'meta.symbol': {'uk': 'Символ', 'en': 'Symbol'},
    'meta.royalty': {'uk': 'Роялті (%)', 'en': 'Royalty (%)'},
    'meta.creator': {'uk': 'Адреса creator (Solana)', 'en': 'Creator address (Solana)'},
}
