"""i18n-рядки: домен pipeline (конвеєр (Етапи 1–3), куратор, підказки, workflow).

Збираються в `ui_strings._STRINGS` через `ui_strings._merge_strings()`. НЕ імпортуй
цей модуль у застосунку — використовуй `ui_strings.t()`. Парність uk↔en, плейсхолдери
й повноту ключів звіряє `tests/test_ui_strings.py` проти зібраного `_STRINGS`.
"""

STRINGS: dict[str, dict[str, str]] = {
    'gate.images.wallet': {'uk': '🔒 **Етап 2️⃣ Зображення заблоковано.** Спочатку **💳 Кредити** → підключи гаманець (Sign-In). Генерація списує кредити: Flux/Stability ≈ **1 cr**, OpenAI ≈ **4 cr**.', 'en': '🔒 **Stage 2️⃣ Images is locked.** First go to **💳 Credits** → connect your wallet (Sign-In). Generation spends credits: Flux/Stability ≈ **1 cr**, OpenAI ≈ **4 cr**.'},
    'gate.images.prompts': {'uk': '🔒 **Етап 2️⃣ Зображення заблоковано.** На **1️⃣ Текст** потрібен хоча б один збережений промпт (Сингл, Матриця або «Свій текст»). Шаблон з sidebar може заповнити Етап 1 автоматично.', 'en': '🔒 **Stage 2️⃣ Images is locked.** On **1️⃣ Text** save at least one prompt (Single, Matrix, or «Own text»). A sidebar template may pre-fill Stage 1.'},
    'gate.mint.approve': {'uk': '🔒 **Етап 3️⃣ Експорт заблоковано.** На **2️⃣ Зображення**: згенеруй кадри → у Кураторі оціни **≥4★** → **Схвалити** → «**Зберегти обрані**». Для 1/1 достатньо одного схваленого.', 'en': '🔒 **Stage 3️⃣ Export is locked.** On **2️⃣ Images**: render frames → in the Curator rate **≥4★** → **Approve** → «**Save selected**». For 1/1, one approval is enough.'},
    'gate.mint.wallet': {'uk': '🔒 **Етап 3️⃣ Експорт заблоковано.** Спочатку **💳 Кредити** → підключи гаманець. Потім схвали зображення на **2️⃣** або завантаж свої PNG/JPG тут.', 'en': '🔒 **Stage 3️⃣ Export is locked.** First **💳 Credits** → connect your wallet. Then approve images on **2️⃣** or upload your own PNG/JPG here.'},
    'empty.pipeline.billing': {'uk': '**Зараз:** підключи гаманець (MetaMask / Phantom) на цій вкладці · **Далі:** **1️⃣ Текст** → **2️⃣ Зображення** · **Чому:** кредити = pay-as-you-go; новим гаманцям — до **5** welcome cr (EVM + мін. ETH на Base).', 'en': '**Now:** connect wallet (MetaMask / Phantom) on this tab · **Next:** **1️⃣ Text** → **2️⃣ Images** · **Why:** credits are pay-as-you-go; new wallets get up to **5** welcome cr (EVM + min ETH on Base).'},
    'empty.pipeline.text': {'uk': '**Зараз:** обери режим (**Сингл** для 1/1, **Матриця** для дропу) або встав свій текст · **Далі:** **2️⃣ Зображення** (списує cr) · **Чому:** текст потрапляє в metadata (Prompt-Lock) — перевір lint перед генерацією.', 'en': '**Now:** pick a mode (**Single** for 1/1, **Matrix** for a drop) or paste your text · **Next:** **2️⃣ Images** (spends cr) · **Why:** text goes into metadata (Prompt-Lock) — run lint before generating.'},
    'empty.pipeline.images': {'uk': '**Зараз:** обери двигун → **Pilot** (рекомендовано) або повна черга · **Далі:** Куратор — рейтинг, **Regenerate** слабких, «**Зберегти обрані**» · **Чому:** лише схвалені кадри йдуть на **3️⃣ Експорт**.', 'en': '**Now:** pick an engine → **Pilot** (recommended) or full queue · **Next:** Curator — rate, **Regenerate** weak frames, «**Save selected**» · **Why:** only approved frames go to **3️⃣ Export**.'},
    'empty.pipeline.mint': {'uk': '**Зараз:** схвали зображення на **2️⃣** (автоматично потраплять сюди) або завантаж свої файли нижче · **Далі:** обери платформу → **Зібрати ZIP** · **Чому:** мінт на маркетплейсі — окремо; ми готуємо mint-ready бандл.', 'en': '**Now:** approve on **2️⃣** (auto-queued here) or upload your files below · **Next:** pick a platform → **Build ZIP** · **Why:** marketplace mint is separate; we prepare the mint-ready bundle.'},
    'pipeline.title': {'uk': '⛓️ Web3-конвеєр: Текст → Зображення → Експорт', 'en': '⛓️ Web3 pipeline: Text → Images → Export'},
    'pipeline.metric_prompts': {'uk': 'Промпти', 'en': 'Prompts'},
    'pipeline.metric_generated': {'uk': 'Згенеровано', 'en': 'Generated'},
    'pipeline.metric_approved': {'uk': 'Схвалено', 'en': 'Approved'},
    'pipeline.metric_queue': {'uk': 'У черзі', 'en': 'Queue'},
    'pipeline.stage_radio': {'uk': 'Етап конвеєра', 'en': 'Pipeline stage'},
    'workflow.mode_title': {'uk': '### 🧭 Режим роботи', 'en': '### 🧭 Workflow mode'},
    'workflow.path': {'uk': 'Шлях', 'en': 'Path'},
    'workflow.classic': {'uk': '🏭 Колекція — LLM, rarity, до 10k', 'en': '🏭 Collection — LLM, rarity, up to 10k'},
    'workflow.pipeline': {'uk': '⛓️ Конвеєр — текст → зображення → експорт', 'en': '⛓️ Pipeline — text → images → export'},
    'workflow.help': {'uk': 'Колекція: traits, rarity, до 10k — промпти й bulk-images через ваш OpenAI/Anthropic key (на ai.w3ir.io LLM також **1 cr/запит**). **⑤ Швидке превʼю** — OpenAI key **+ 4 cr/кадр** на ai.w3ir.io. Конвеєр: дроп за кредитами, куратор, export.', 'en': 'Collection: traits, rarity, up to 10k — prompts and bulk images via your OpenAI/Anthropic key (on ai.w3ir.io LLM also **1 cr/request**). **⑤ Quick preview** — OpenAI key **+ 4 cr/frame** on ai.w3ir.io. Pipeline: credit-based drop, curator, export.'},
    'workflow.classic_caption': {'uk': '**Шлях «Колекція»:** 🛠️ Конструктор → 🧬 Traits → 📦 Batch → 🏭 Колекція → ⑤ Швидке превʼю (тест) / **→ Конвеєр** → ZIP·IPFS. Промпти — ваш ключ (+ cr на ai.w3ir.io).', 'en': '**Collection path:** 🛠️ Builder → 🧬 Traits → 📦 Batch → 🏭 Collection → ⑤ Quick preview (test) / **→ Pipeline** → ZIP·IPFS. Prompts — your key (+ cr on ai.w3ir.io).'},
    'workflow.pipeline_caption': {'uk': '**Шлях «Конвеєр»:** 💳 Кредити → 1️⃣ Текст → 2️⃣ Зображення (Pilot → Куратор) → 3️⃣ Експорт (ZIP / IPFS / W3IR). Кнопки «← / →» і CTA під підказками ведуть далі.', 'en': '**Pipeline path:** 💳 Credits → 1️⃣ Text → 2️⃣ Images (Pilot → Curator) → 3️⃣ Export (ZIP / IPFS / W3IR). «← / →» buttons and CTAs under hints guide you forward.'},
    'workflow.current_pipeline': {'uk': '⛓️ Режим: **Конвеєр** (рекомендовано)', 'en': '⛓️ Mode: **Pipeline** (recommended)'},
    'workflow.advanced_expander': {'uk': '⚙️ Розширений режим (Колекція 50+ NFT)', 'en': '⚙️ Advanced mode (Collection 50+ NFTs)'},
    'workflow.advanced_warning': {'uk': '5 вкладок, свій OpenAI/Anthropic ключ, traits і rarity — для великих generative-колекцій. Для 1–25 NFT залишайтесь у Конвеєрі.', 'en': 'Five tabs, your own OpenAI/Anthropic key, traits and rarity — for large generative collections. For 1–25 NFTs stay in Pipeline.'},
    'workflow.advanced_confirm': {'uk': 'Розумію: перемикаюсь на складніший шлях', 'en': 'I understand: switch to the advanced path'},
    'workflow.advanced_confirm_required': {'uk': 'Поставте галочку підтвердження вище.', 'en': 'Check the confirmation box above.'},
    'workflow.switch_to_classic': {'uk': 'Увімкнути режим Колекція', 'en': 'Enable Collection mode'},
    'workflow.classic_active_banner': {'uk': '🏭 Активний **розширений** режим Колекція (5 вкладок, API-ключ).', 'en': '🏭 **Advanced** Collection mode is active (5 tabs, API key).'},
    'workflow.switch_to_pipeline': {'uk': '← Повернутись до Конвеєра', 'en': '← Back to Pipeline'},
    'workflow.bridge_title': {'uk': '**🔗 Продовжити в Конвеєрі**', 'en': '**🔗 Continue in Pipeline**'},
    'workflow.bridge_caption': {'uk': 'Перенесіть промпти на вкладку **⛓️ Конвеєр** для генерації зображень (GPT Image, Flux, Stability) і експорту бандла під обрану платформу.', 'en': 'Move prompts to **⛓️ Pipeline** for image generation (GPT Image, Flux, Stability) and export of a bundle for your chosen platform.'},
    'workflow.bridge_limit': {'uk': 'Скільки промптів перенести', 'en': 'How many prompts to transfer'},
    'workflow.bridge_btn': {'uk': '→ У Конвеєр ({limit:,} з {total:,})', 'en': '→ To Pipeline ({limit:,} of {total:,})'},
    'workflow.transfer_msg': {'uk': 'Перенесено **{count}** промптів{source}. Відкрийте **⛓️ Конвеєр** — етап: **{stage}**.', 'en': 'Transferred **{count}** prompts{source}. Open **⛓️ Pipeline** — stage: **{stage}**.'},
    'hint.classic.build.start': {'uk': '**Зараз:** опиши **ідею персонажа** (sidebar) або **Застосувати шаблон** · **Далі:** **② Traits** — варіанти та ваги рідкісності · **Порада:** для 1–25 NFT швидше через **⛓️ Конвеєр**.', 'en': '**Now:** describe the **character idea** (sidebar) or **Apply template** · **Next:** **② Traits** — variants and rarity weights · **Tip:** for 1–25 NFTs, **⛓️ Pipeline** is faster.'},
    'hint.classic.build.traits': {'uk': '**Зараз:** ідея є — заповни **② Traits** (`назва | вага`, напр. `gold crown | 5`) · **Далі:** **③ Batch** (10–20 тестових промптів) · **Порада:** шаблон уже міг підставити traits — перевір і підправ.', 'en': '**Now:** idea set — fill **② Traits** (`name | weight`, e.g. `gold crown | 5`) · **Next:** **③ Batch** (10–20 test prompts) · **Tip:** a template may have pre-filled traits — review and tweak.'},
    'hint.classic.build.ready': {'uk': '**Зараз:** концепт готовий · **Далі:** **② Traits** (generative) або **③ Batch** (швидкий тест тексту) · **Порада:** Batch показує rarity до повного run на **④ Колекція**.', 'en': '**Now:** concept ready · **Next:** **② Traits** (generative) or **③ Batch** (quick text test) · **Tip:** Batch shows rarity before full **④ Collection** run.'},
    'hint.classic.traits.empty': {'uk': '**Зараз:** додай traits — шаблон з sidebar або вручну · **Формат:** `назва | вага` (вага = рідкість, вища = рідше) · **Далі:** **③ Batch** або одразу **④ Колекція**.', 'en': '**Now:** add traits — sidebar template or manual · **Format:** `name | weight` (weight = rarity, higher = rarer) · **Next:** **③ Batch** or straight to **④ Collection**.'},
    'hint.classic.traits.no_idea': {'uk': '**Зараз:** traits є, але немає **ідеї** на **🛠️ Конструктор** · **Далі:** вкажи персонажа/світ (1–2 речення) — LLM збере промпти з traits · **Порада:** «Застосувати шаблон» заповнює і ідею, і traits.', 'en': '**Now:** traits set but no **idea** on **🛠️ Builder** · **Next:** describe character/world (1–2 sentences) — LLM builds prompts from traits · **Tip:** «Apply template» fills both idea and traits.'},
    'hint.classic.traits.ready': {'uk': '**Зараз:** traits готові · **Далі:** **③ Batch** (10–20, ~$0.01–0.02/промпт) або **④ Колекція** (50–10 000, з checkpoint) · **Порада:** після Batch — **«→ У Конвеєр»** для зображень кредитами.', 'en': '**Now:** traits ready · **Next:** **③ Batch** (10–20, ~$0.01–0.02/prompt) or **④ Collection** (50–10,000, with checkpoints) · **Tip:** after Batch — **«→ To Pipeline»** for credit-based images.'},
    'hint.classic.batch.empty': {'uk': '**Зараз:** згенеруй **тестову партію** (10–20 промптів) · **Далі:** перевір rarity-розподіл і якість тексту → **④ Колекція** або **→ Конвеєр** · **Чому:** дешевше зловити помилки traits до 500+ run.', 'en': '**Now:** generate a **test batch** (10–20 prompts) · **Next:** check rarity distribution and text quality → **④ Collection** or **→ Pipeline** · **Why:** cheaper to catch trait errors before a 500+ run.'},
    'hint.classic.batch.ready': {'uk': '**Зараз:** промпти batch готові · **Далі:** **④ Колекція** (масштаб) · **🖼️ Зображення** (свій API) · або **«→ У Конвеєр»** (рекомендовано: Flux, куратор, export) · **Порада:** Конвеєр дає Prompt-Lock і mint-ready бандл.', 'en': '**Now:** batch prompts ready · **Next:** **④ Collection** (scale) · **🖼️ Images** (your API) · or **«→ To Pipeline»** (recommended: Flux, curator, export) · **Tip:** Pipeline adds Prompt-Lock and a mint-ready bundle.'},
    'hint.classic.collection.empty': {'uk': '**Зараз:** запусти **повну колекцію** (мін. 50 токенів) або **▶️ Продовжити** збережений run · **Далі:** **«→ У Конвеєр»** для зображень · **Чому:** checkpoint — можна зупинити й продовжити без втрати прогресу.', 'en': '**Now:** start **full collection** (min 50 tokens) or **▶️ Resume** a saved run · **Next:** **«→ To Pipeline»** for images · **Why:** checkpoints let you pause and resume without losing progress.'},
    'hint.classic.collection.ready': {'uk': '**Зараз:** промпти колекції готові · **Далі:** **«→ У Конвеєр»** → **2️⃣ Зображення** (рекомендовано: куратор, export) · **Альтернатива:** **⑤ Швидке превʼю** — 1–4 тестові кадри (OpenAI key + **4 cr/кадр** на ai.w3ir.io) · **Порада:** для дропу — лише Конвеєр.', 'en': '**Now:** collection prompts ready · **Next:** **«→ To Pipeline»** → **2️⃣ Images** (recommended: curator, export) · **Alternative:** **⑤ Quick preview** — 1–4 test frames (OpenAI key + **4 cr/frame** on ai.w3ir.io) · **Tip:** for drops — Pipeline only.'},
    'hint.classic.images': {'uk': '**Зараз:** **тест 1–4 кадрів** (gpt-image-1) — не mint-ready дроп · **Потрібно:** гаманець + **OpenAI key** у sidebar + **4 cr/кадр** на ai.w3ir.io (окремо від USD на рахунку OpenAI) · **Далі:** **⛓️ Конвеєр → 2️⃣** або **«→ У Конвеєр»**.', 'en': '**Now:** **test 1–4 frames** (gpt-image-1) — not a mint-ready drop · **Need:** wallet + **OpenAI key** in sidebar + **4 cr/frame** on ai.w3ir.io (separate from USD on your OpenAI account) · **Next:** **⛓️ Pipeline → 2️⃣** or **«→ To Pipeline»**.'},
    'hint.pipeline.text.empty': {'uk': '**Зараз:** обери **Сингл** (1/1), **Матриця** (дроп) або **Свій текст** · **Далі:** «⚡ Зібрати» / «Згенерувати матрицю» → перевір lint · **Порада:** sidebar **шаблон** + «Застосувати» заповнює Етап 1 одразу.', 'en': '**Now:** pick **Single** (1/1), **Matrix** (drop), or **Own text** · **Next:** «⚡ Build» / «Generate matrix» → check lint · **Tip:** sidebar **template** + «Apply» can pre-fill Stage 1.'},
    'hint.pipeline.text.wallet': {'uk': '**Зараз:** промпти збережено — підключи **гаманець** на **💳 Кредити** · **Далі:** **2️⃣ Зображення** · **Порада:** кнопка **💳 Підключити гаманець** під цією підказкою веде на потрібний етап.', 'en': '**Now:** prompts saved — connect **wallet** on **💳 Credits** · **Next:** **2️⃣ Images** · **Tip:** **💳 Connect wallet** button under this hint jumps to the right stage.'},
    'hint.pipeline.text.ready': {'uk': '**Зараз:** черга промптів готова (перевір таблицю нижче) · **Далі:** **2️⃣ Зображення** — спочатку **Pilot ~10**, потім повний run · **Порада:** опційно **✨ Polish** (1 cr) покращує текст перед генерацією.', 'en': '**Now:** prompt queue ready (check the table below) · **Next:** **2️⃣ Images** — **Pilot ~10** first, then full run · **Tip:** optional **✨ Polish** (1 cr) improves text before generating.'},
    'hint.pipeline.images.wallet': {'uk': '**Зараз:** підключи **гаманець** на **💳 Кредити** · **Далі:** обери двигун і запусти **Pilot** · **Чому:** без verified wallet + балансу генерація заблокована (production).', 'en': '**Now:** connect **wallet** on **💳 Credits** · **Next:** pick engine and run **Pilot** · **Why:** without verified wallet + balance, generation is blocked (production).'},
    'hint.pipeline.images.no_prompts': {'uk': '**Зараз:** черга порожня · **Далі:** **1️⃣ Текст** — Сингл/Матриця/свій список · **Альтернатива:** Classic **«→ У Конвеєр»** з Batch/Колекції · **Порада:** після sidebar-шаблону промпти часто вже на Етапі 1.', 'en': '**Now:** queue empty · **Next:** **1️⃣ Text** — Single/Matrix/your list · **Alternative:** Classic **«→ To Pipeline»** from Batch/Collection · **Tip:** after a sidebar template, prompts are often already on Stage 1.'},
    'hint.pipeline.images.generate': {'uk': '**Зараз:** запусти **Pilot** або повну чергу (Flux ≈ 1 cr/кадр) · **Далі:** **Куратор** — рейтинг 1–5★, **Regenerate** слабких, QA-попередження · **Порада:** **Hybrid** tier — перші N кадрів у вищій якості.', 'en': '**Now:** run **Pilot** or full queue (Flux ≈ 1 cr/frame) · **Next:** **Curator** — rate 1–5★, **Regenerate** weak ones, QA warnings · **Tip:** **Hybrid** tier — first N frames at higher quality.'},
    'hint.pipeline.images.approve': {'uk': '**Зараз:** відміти вдалі кадри **≥4★** → **Схвалити** · **Далі:** «**Зберегти обрані**» (append увімкнено — додає між хвилями) · **Порада:** **Final-pass 3★** — опційне покращення borderline.', 'en': '**Now:** mark good frames **≥4★** → **Approve** · **Next:** «**Save selected**» (append on — adds between waves) · **Tip:** **Final-pass 3★** — optional upgrade for borderline frames.'},
    'hint.pipeline.images.mint': {'uk': '**Зараз:** схвалені роботи збережено · **Далі:** **3️⃣ Експорт** — preflight, ZIP / IPFS, opensea·thirdweb·W3IR · **Порада:** upscale 2048 — чекбокс перед export.', 'en': '**Now:** approved work saved · **Next:** **3️⃣ Export** — preflight, ZIP / IPFS, opensea·thirdweb·W3IR · **Tip:** 2048 upscale — checkbox before export.'},
    'hint.pipeline.mint.empty': {'uk': '**Зараз:** черга export порожня · **Далі:** **2️⃣ Зображення** — згенеруй і «**Зберегти обрані**» · **Альтернатива:** завантаж власні PNG (якщо вже маєш art).', 'en': '**Now:** export queue empty · **Next:** **2️⃣ Images** — generate and «**Save selected**» · **Alternative:** upload your own PNGs (if art is ready).'},
    'hint.pipeline.mint.ready': {'uk': '**Зараз:** обери **платформу** (OpenSea, Thirdweb, Metaplex, W3IR) · **Далі:** preflight → ZIP або IPFS · **Чому:** on-chain **мінт** тут опційний (Thirdweb у «Розширене»); більшість мінтять через dashboard/marketplace.', 'en': '**Now:** pick **platform** (OpenSea, Thirdweb, Metaplex, W3IR) · **Next:** preflight → ZIP or IPFS · **Why:** on-chain **mint** here is optional (Thirdweb under «Advanced»); most mint via dashboard/marketplace.'},
    'hint.pipeline.billing': {'uk': '**Зараз:** підключи гаманець і перевір **баланс** · **Далі:** **1️⃣ Текст** · **Пакети:** Start 100 cr · Creator 400 cr · Pro 1000 cr · **Порада:** калькулятор вартості над вкладками оцінює дроп до старту.', 'en': '**Now:** connect wallet and check **balance** · **Next:** **1️⃣ Text** · **Packages:** Start 100 cr · Creator 400 cr · Pro 1000 cr · **Tip:** cost calculator above tabs estimates your drop before you start.'},
    'cta.connect_wallet': {'uk': '💳 Підключити гаманець', 'en': '💳 Connect wallet'},
    'cta.to_prompts': {'uk': '1️⃣ Перейти до промптів', 'en': '1️⃣ Go to prompts'},
    'cta.to_images': {'uk': '2️⃣ Перейти до зображень', 'en': '2️⃣ Go to images'},
    'cta.to_export': {'uk': '3️⃣ Перейти до експорту', 'en': '3️⃣ Go to export'},
    'cta.write_prompts': {'uk': '1️⃣ Спершу напишіть промпти', 'en': '1️⃣ Write prompts first'},
    'cta.back_to_images': {'uk': '2️⃣ Назад до зображень', 'en': '2️⃣ Back to images'},
    'cta.forward.prompts': {'uk': '➡️ Далі: {next_stage}', 'en': '➡️ Next: {next_stage}'},
    'cta.forward.images': {'uk': '➡️ Далі: {next_stage}', 'en': '➡️ Next: {next_stage}'},
    'cta.forward.export': {'uk': '➡️ Далі: {next_stage}', 'en': '➡️ Next: {next_stage}'},
    'cta.forward.classic': {'uk': '➡️ Далі: {next}', 'en': '➡️ Next: {next}'},
    'pipeline.forward_caption': {'uk': 'Етап **{stage}** готовий — переходьте далі:', 'en': 'Stage **{stage}** complete — continue:'},
    'step.constructor': {'uk': 'Конструктор', 'en': 'Builder'},
    'step.traits': {'uk': 'Traits', 'en': 'Traits'},
    'step.batch': {'uk': 'Batch', 'en': 'Batch'},
    'step.collection': {'uk': 'Колекція', 'en': 'Collection'},
    'step.images': {'uk': 'Зображення', 'en': 'Images'},
    'step.images_classic': {'uk': 'Швидке превʼю', 'en': 'Quick preview'},
    'step.text': {'uk': 'Текст', 'en': 'Text'},
    'step.mint': {'uk': 'Експорт', 'en': 'Export'},
    'step.billing': {'uk': 'Кредити', 'en': 'Credits'},
    'pl1.title': {'uk': "##### 🎨 Етап 1 — Конструктор об'єктних промптів", 'en': '##### 🎨 Stage 1 — Object prompt builder'},
    'pl1.caption': {'uk': 'Структура: **Core Object → Style → Detailing → Engine Tags**. Результат зберігається для **2️⃣ Зображення**. Режим **Сингл** = 1/1, **Матриця** = дроп.', 'en': 'Structure: **Core Object → Style → Detailing → Engine Tags**. Saved for **2️⃣ Images**. **Single** = 1/1, **Matrix** = drop.'},
    'pl1.mode_scale': {'uk': 'Режим масштабування', 'en': 'Scale mode'},
    'pl1.mode.single': {'uk': 'Сингл', 'en': 'Single'},
    'pl1.mode.group': {'uk': 'Специфічна група', 'en': 'Specific group'},
    'pl1.mode.matrix': {'uk': 'Генеративна колекція (Матриця)', 'en': 'Generative collection (Matrix)'},
    'pl1.mode.raw': {'uk': '✍️ Свій текст', 'en': '✍️ Own text'},
    'pl1.mode.i2p': {'uk': '🖼️ Image-to-Prompt', 'en': '🖼️ Image-to-Prompt'},
    'pl1.raw_caption': {'uk': '**Точка входу 1**: готові промпти в обхід конструктора — один на рядок.', 'en': '**Entry point 1**: ready prompts — one per line.'},
    'pl1.raw_prompts': {'uk': 'Ваші промпти', 'en': 'Your prompts'},
    'pl1.use_raw': {'uk': '📥 Використати ці промпти', 'en': '📥 Use these prompts'},
    'pl1.raw_empty': {'uk': 'Введіть хоча б один промпт.', 'en': 'Enter at least one prompt.'},
    'pl1.engine_tags': {'uk': 'Engine Tags (технічні параметри)', 'en': 'Engine Tags (technical params)'},
    'pl1.engine_tags_ph': {'uk': '--ar 1:1 --s 250 --v 6.0', 'en': '--ar 1:1 --s 250 --v 6.0'},
    'pl1.core_object': {'uk': "Головний об'єкт (Core Object)", 'en': 'Core object'},
    'pl1.core_object_ph': {'uk': 'cyber samurai', 'en': 'cyber samurai'},
    'pl1.style': {'uk': 'Стиль', 'en': 'Style'},
    'pl1.lighting': {'uk': 'Освітлення', 'en': 'Lighting'},
    'pl1.camera': {'uk': 'Ракурс/камера', 'en': 'Camera angle'},
    'pl1.colors': {'uk': 'Кольори/деталі (опційно)', 'en': 'Colors/details (optional)'},
    'pl1.colors_ph': {'uk': 'vibrant neon palette, intricate details', 'en': 'vibrant neon palette, intricate details'},
    'pl1.build_one': {'uk': '⚡ Зібрати промпт', 'en': '⚡ Build prompt'},
    'pl1.core_required': {'uk': "Вкажіть головний об'єкт.", 'en': 'Specify the core object.'},
    'pl1.core_group': {'uk': "Головний об'єкт (один для всієї групи)", 'en': 'Core object (one for the group)'},
    'pl1.styles_multi': {'uk': 'Стилі (кожен стиль → окремий промпт)', 'en': 'Styles (each style → separate prompt)'},
    'pl1.build_group': {'uk': '⚡ Зібрати групу ({n} промптів)', 'en': '⚡ Build group ({n} prompts)'},
    'pl1.matrix_caption': {'uk': 'Обери **2+ категорії** (персонаж, фон, аксесуар…) — отримаєш усі комбінації. Для дропу **25**: напр. 5×5. Перевір **Комбінацій у матриці** перед генерацією.', 'en': 'Pick **2+ categories** (character, background, accessory…) — all combos are created. For a **25** drop: e.g. 5×5. Check **Matrix combinations** before generating.'},
    'pl1.matrix_traits_placeholder': {'uk': 'Оберіть або введіть варіанти…', 'en': 'Select or type variants…'},
    'pl1.cat.character': {'uk': 'Варіанти персонажа', 'en': 'Character variants'},
    'pl1.cat.background': {'uk': 'Варіанти фону', 'en': 'Background variants'},
    'pl1.cat.accessory': {'uk': 'Варіанти аксесуарів', 'en': 'Accessory variants'},
    'pl1.cat.form': {'uk': 'Форма / силует', 'en': 'Form / silhouette'},
    'pl1.cat.pattern': {'uk': 'Патерн / візерунок', 'en': 'Pattern / motif'},
    'pl1.cat.scene': {'uk': 'Сцена / локація', 'en': 'Scene / location'},
    'pl1.cat.mood': {'uk': 'Настрій / освітлення', 'en': 'Mood / lighting'},
    'pl1.cat.layout': {'uk': 'Подача / контекст', 'en': 'Layout / context'},
    'pl1.cat.tier': {'uk': 'Рівень / tier', 'en': 'Tier / level'},
    'pl1.cat.style': {'uk': 'Візуальна подача', 'en': 'Visual style'},
    'pl1.cat.subject': {'uk': "Суб'єкт / тема", 'en': 'Subject / theme'},
    'pl1.cat.detail': {'uk': 'Деталь / акцент', 'en': 'Detail / accent'},
    'pl1.matrix_caption_abstract': {'uk': 'Для **абстракції** достатньо **2 осей** (форма × фон) → 5×5 = 25. Без персонажів і PFP-traits.', 'en': 'For **abstract** art, **2 axes** (form × background) → 5×5 = 25. No characters or PFP-style traits.'},
    'pl1.matrix_caption_landscape': {'uk': 'Для **пейзажу**: сцена × настрій (5×5 = 25). Широкий кадр, без портретів.', 'en': 'For **landscapes**: scene × mood (5×5 = 25). Wide shots, no portraits.'},
    'pl1.archetype_gen_title': {'uk': '✨ Згенерувати N archetypes (LLM)', 'en': '✨ Generate N archetypes (LLM)'},
    'pl1.archetype_gen_title_abstract': {'uk': '✨ Згенерувати N мотивів (LLM)', 'en': '✨ Generate N motifs (LLM)'},
    'pl1.archetype_gen_help': {'uk': 'Тема колекції → список унікальних англійських імен для **першої осі** матриці. ~1 кр / 15 імен. Потрібен OpenAI key у sidebar.', 'en': 'Collection theme → unique English names for the **first matrix axis**. ~1 cr / 15 names. Requires OpenAI key in sidebar.'},
    'pl1.archetype_gen_theme': {'uk': 'Тема / напрям', 'en': 'Theme / direction'},
    'pl1.archetype_gen_n': {'uk': 'Кількість (N)', 'en': 'Count (N)'},
    'pl1.archetype_gen_go': {'uk': '⚡ Згенерувати {n} ({cr} cr)', 'en': '⚡ Generate {n} ({cr} cr)'},
    'pl1.archetype_gen_ok': {'uk': 'Згенеровано {n} імен — додано в **{axis}**. Доповніть інші осі та натисніть «Зібрати матрицю».', 'en': 'Generated {n} names — added to **{axis}**. Fill other axes, then build the matrix.'},
    'pl1.archetype_gen_no_key': {'uk': 'Додайте OpenAI API key у sidebar (🤖 AI та ключі).', 'en': 'Add an OpenAI API key in the sidebar (🤖 AI & keys).'},
    'pl1.archetype_gen_blocked': {'uk': 'Тема заблокована content-safety: {code}', 'en': 'Theme blocked by content-safety: {code}'},
    'pl1.archetype_gen_partial': {'uk': 'Отримано {n} з {want} імен ({detail})', 'en': 'Got {n} of {want} names ({detail})'},
    'pl1.shared_style': {'uk': 'Спільний стиль (опційно)', 'en': 'Shared style (optional)'},
    'pl1.matrix_combos': {'uk': 'Комбінацій у матриці', 'en': 'Matrix combinations'},
    'pl1.rarity_preview': {'uk': '📊 Превʼю rarity traits (очікуваний %)', 'en': '📊 Rarity traits preview (expected %)'},
    'pl1.save_matrix_name': {'uk': 'Зберегти матрицю як шаблон', 'en': 'Save matrix as template'},
    'pl1.save_matrix': {'uk': '💾 Зберегти шаблон', 'en': '💾 Save template'},
    'pl1.matrix_saved': {'uk': 'Шаблон «{name}» збережено в data/matrices/.', 'en': 'Template «{name}» saved to data/matrices/.'},
    'pl1.load_matrix': {'uk': 'Завантажити шаблон матриці', 'en': 'Load matrix template'},
    'pl1.apply_matrix': {'uk': '📂 Застосувати шаблон', 'en': '📂 Apply template'},
    'pl1.matrix_warn': {'uk': 'Понад 500 комбінацій — генерація зображень для всіх буде дорогою. Розгляньте скорочення списків.', 'en': 'Over 500 combinations — generating all images will be expensive. Consider shorter lists.'},
    'pl1.rich_matrix': {'uk': '✨ Rich prompts (LLM-полірування після матриці)', 'en': '✨ Rich prompts (LLM polish after matrix)'},
    'pl1.rich_matrix_help': {'uk': 'Після збірки матриці автоматично проганяє Light polish (~1 кр/15 промптів) — узгоджені англомовні промпти + negative.', 'en': 'After matrix build, auto-runs Light polish (~1 cr/15 prompts) — consistent English prompts + negative.'},
    'pl1.rich_matrix_spin': {'uk': 'Rich prompts: LLM полірує матрицю…', 'en': 'Rich prompts: LLM polishing matrix…'},
    'pl1.rich_matrix_no_key': {'uk': 'Для Rich prompts потрібен OpenAI API Key (бічна панель). Збережено сиру матрицю — поліруйте вручну нижче.', 'en': 'Rich prompts need an OpenAI API key (sidebar). Raw matrix saved — polish manually below.'},
    'pl1.gen_matrix': {'uk': '⚡ Згенерувати матрицю ({n} промптів)', 'en': '⚡ Generate matrix ({n} prompts)'},
    'pl1.stored': {'uk': 'Збережено {n} промпт(ів). Далі → **2️⃣ Зображення** (підключіть гаманець на **💳 Кредити**).', 'en': 'Saved {n} prompt(s). Next → **2️⃣ Images** (connect wallet on **💳 Credits**).'},
    'pl1.i2p_caption': {'uk': 'Завантажте зображення — vision-модель відтворить формулу промпту для Етапу 2.', 'en': 'Upload an image — vision model rebuilds the prompt formula for Stage 2.'},
    'pl1.i2p_upload': {'uk': 'Зображення-зразок', 'en': 'Reference image'},
    'pl1.i2p_go': {'uk': '🔍 Відтворити формулу промпту', 'en': '🔍 Reverse-engineer prompt'},
    'pl1.i2p_no_key': {'uk': 'Відсутній OpenAI API Key (бічна панель).', 'en': 'OpenAI API key missing (sidebar).'},
    'pl1.i2p_detailed': {'uk': '🔬 Детальний аналіз (gpt-4o)', 'en': '🔬 Detailed analysis (gpt-4o)'},
    'pl1.i2p_detailed_help': {'uk': 'Точніший розбір зображення детальнішою моделлю (повільніше й дорожче за API).', 'en': 'More accurate image breakdown with a stronger model (slower, pricier API).'},
    'pl1.i2p_error': {'uk': 'Помилка Image-to-Prompt: {err}', 'en': 'Image-to-Prompt error: {err}'},
    'pl1.i2p_analyzing': {'uk': 'Аналіз зображення…', 'en': 'Analyzing image…'},
    'pl1.preview_title': {'uk': '**Поточний результат Етапу 1 ({n} шт.)**', 'en': '**Stage 1 result ({n} items)**'},
    'pl1.col_prompt': {'uk': 'Промпт', 'en': 'Prompt'},
    'pl1.col_traits': {'uk': 'Traits', 'en': 'Traits'},
    'pl1.lint_col': {'uk': '⚠️', 'en': '⚠️'},
    'pl1.lint_summary': {'uk': 'Лінт промптів: {parts}', 'en': 'Prompt lint: {parts}'},
    'lint.empty': {'uk': 'порожній', 'en': 'empty'},
    'lint.too_short': {'uk': 'надто короткий', 'en': 'too short'},
    'lint.too_long': {'uk': 'надто довгий', 'en': 'too long'},
    'lint.duplicate': {'uk': 'дублікат', 'en': 'duplicate'},
    'pl1.polish_title': {'uk': '✨ LLM-полірування промптів', 'en': '✨ LLM prompt polish'},
    'pl1.polish_help': {'uk': 'Переписує сирі промпти матриці в узгоджені за стилем + negative (traits зберігаються). 1 кредит за кожні ~{size} промптів.', 'en': 'Rewrites raw matrix prompts into style-consistent ones + negative (traits preserved). 1 credit per ~{size} prompts.'},
    'pl1.polish_mode': {'uk': 'Глибина', 'en': 'Depth'},
    'pl1.polish_light': {'uk': 'Light (швидко)', 'en': 'Light (quick)'},
    'pl1.polish_full': {'uk': 'Full (якісно)', 'en': 'Full (thorough)'},
    'pl1.polish_go': {'uk': '✨ Полірувати ({n} промптів, ~{cr} кр.)', 'en': '✨ Polish ({n} prompts, ~{cr} cr)'},
    'pl1.polish_preview': {'uk': "👁 Прев'ю на 1 промпті (1 кр.)", 'en': '👁 Preview on 1 prompt (1 cr)'},
    'pl1.polish_before': {'uk': 'До', 'en': 'Before'},
    'pl1.polish_after': {'uk': 'Після', 'en': 'After'},
    'pl1.polish_no_key': {'uk': 'Потрібен OpenAI API-ключ для полірування.', 'en': 'OpenAI API key required for polishing.'},
    'pl1.polish_spin': {'uk': 'LLM полірує промпти…', 'en': 'LLM is polishing prompts…'},
    'pl1.polish_ok': {'uk': 'Відполіровано {n} промптів.', 'en': 'Polished {n} prompts.'},
    'pl1.polish_partial': {'uk': 'Відполіровано частково: {err} чанк(ів) не вдалося (кредити повернено).', 'en': 'Partially polished: {err} chunk(s) failed (credits refunded).'},
    'pl1.bible_title': {'uk': '🎨 Style Bible колекції', 'en': '🎨 Collection Style Bible'},
    'pl1.bible_help': {'uk': 'Зафіксуй вигляд колекції (стиль, світло, ракурс, фон) і натисни «Зберегти». На Етапі 2 правила додаються до промптів автоматично; LLM-полірування теж їх враховує.', 'en': 'Lock the collection look (style, lighting, camera, background) and Save. On Stage 2 rules are added to prompts automatically; LLM polish uses them too.'},
    'pl1.bible_template_pick': {'uk': 'Заповнити з шаблону', 'en': 'Fill from template'},
    'pl1.bible_fill': {'uk': '↧ Підставити', 'en': '↧ Apply'},
    'pl1.bible_style': {'uk': 'Стиль', 'en': 'Style'},
    'pl1.bible_lighting': {'uk': 'Освітлення', 'en': 'Lighting'},
    'pl1.bible_camera': {'uk': 'Ракурс / кадр', 'en': 'Camera / framing'},
    'pl1.bible_background': {'uk': 'Правило фону', 'en': 'Background rule'},
    'pl1.bible_save': {'uk': '💾 Зберегти біблію', 'en': '💾 Save bible'},
    'pl1.bible_saved': {'uk': 'Style Bible збережено.', 'en': 'Style Bible saved.'},
    'pl1.bible_clear': {'uk': 'Очистити', 'en': 'Clear'},
    'pl1.bible_no_wallet': {'uk': 'Підключіть гаманець (Sign-In) — Style Bible зберігається per-wallet.', 'en': 'Connect wallet (Sign-In) — Style Bible is saved per wallet.'},
    'pl1.rules_label': {'uk': 'Несумісні пари traits (по одній на рядок)', 'en': 'Incompatible trait pairs (one per line)'},
    'pl1.rules_help': {'uk': "Пара значень, які не мають з'являтися разом: «значення1 | значення2». Такі комбінації відсіються перед генерацією.", 'en': "Two values that must not appear together: 'value1 | value2'. Such combinations are filtered out before generation."},
    'pl1.rules_blocked': {'uk': 'Відсіяно несумісних комбінацій: {n}', 'en': 'Incompatible combinations filtered: {n}'},
    'pl2.title': {'uk': '##### 🖼️ Етап 2 — ШІ-генератор контенту з чергою обробки', 'en': '##### 🖼️ Stage 2 — AI generator with processing queue'},
    'pl2.source': {'uk': 'Джерело промптів', 'en': 'Prompt source'},
    'pl2.from_stage1': {'uk': 'Взяти промпти з Етапу 1', 'en': 'Use prompts from Stage 1'},
    'pl2.manual': {'uk': '✍️ Вставити власні промпти вручну', 'en': '✍️ Paste own prompts manually'},
    'pl2.prompts_area': {'uk': 'Промпти (один на рядок)', 'en': 'Prompts (one per line)'},
    'pl2.prompts_found': {'uk': 'Розпізнано промптів: **{n}**', 'en': 'Prompts detected: **{n}**'},
    'pl2.no_stage1': {'uk': '**Немає промптів з Етапу 1** — пройди **1️⃣ Текст** (Сингл/Матриця) або обери **✍️ Вставити вручну** · **Порада:** sidebar-шаблон часто заповнює Етап 1 автоматично.', 'en': '**No prompts from Stage 1** — complete **1️⃣ Text** (Single/Matrix) or choose **✍️ Paste manually** · **Tip:** a sidebar template often pre-fills Stage 1.'},
    'pl2.ab_mode': {'uk': '🔀 A/B порівняння (один промпт — два двигуни)', 'en': '🔀 A/B compare (one prompt — two engines)'},
    'pl2.style_lock': {'uk': '🎨 Style lock колекції', 'en': '🎨 Collection style lock'},
    'pl2.style_lock_help': {'uk': 'Додатковий пресет кадру (PFP/full body) + negative-prompt. Style Bible з Етапу 1 застосовується окремо й автоматично.', 'en': 'Extra frame preset (PFP/full body) + negative prompt. Stage 1 Style Bible is applied separately and automatically.'},
    'pl2.suffix_preset': {'uk': 'Пресет кадру', 'en': 'Frame preset'},
    'pl2.preset_pfp': {'uk': 'PFP / портрет', 'en': 'PFP / portrait'},
    'pl2.preset_full_body': {'uk': 'На повний зріст', 'en': 'Full body'},
    'pl2.preset_landscape': {'uk': 'Сцена / фон', 'en': 'Landscape / scene'},
    'pl2.preset_dynamic': {'uk': 'Динамічна сцена', 'en': 'Dynamic scene'},
    'pl2.preset_geometric': {'uk': 'Геометрія / абстракція', 'en': 'Geometric / abstract'},
    'pl2.preset_brand': {'uk': 'Бренд-знак / іконка', 'en': 'Brand mark / icon'},
    'pl2.preset_event_badge': {'uk': 'Івент-бейдж / медальйон', 'en': 'Event badge / medallion'},
    'pl2.preset_fine_art': {'uk': 'Fine art / 1/1', 'en': 'Fine art / 1/1'},
    'pl2.use_negative': {'uk': 'Додавати negative-prompt', 'en': 'Add negative prompt'},
    'pl2.tier': {'uk': 'Рівень якості', 'en': 'Quality tier'},
    'pl2.tier_draft': {'uk': 'Draft (дешево)', 'en': 'Draft (cheap)'},
    'pl2.tier_final': {'uk': 'Final (якісно)', 'en': 'Final (high quality)'},
    'pl2.tier_hybrid': {'uk': 'Hybrid (перші N — Final)', 'en': 'Hybrid (first N Final)'},
    'pl2.tier_hybrid_n': {'uk': 'Скільки перших у Final', 'en': 'How many first as Final'},
    'pl2.tier_help': {'uk': 'Draft — чернетка дешевшою моделлю; Final — вища якість дорожче (gpt-image high, Flux flux-dev).', 'en': 'Draft — cheaper draft model; Final — higher quality at higher cost (gpt-image high, Flux flux-dev).'},
    'pl2.bible_active': {'uk': '🎨 Style Bible активна — правила колекції додаються до промптів.', 'en': '🎨 Style Bible active — collection rules added to prompts.'},
    'pl2.reproducible': {'uk': '🎲 Відтворюваність (seed)', 'en': '🎲 Reproducible (seed)'},
    'pl2.reproducible_help': {'uk': 'Фіксує seed від base_seed (seed[i]=base+i): той самий base дає ту саму колекцію. Працює для Stability/Flux; OpenAI seed ігнорує.', 'en': 'Fixes seeds from base_seed (seed[i]=base+i): same base reproduces the same collection. Works for Stability/Flux; OpenAI ignores seed.'},
    'pl2.base_seed': {'uk': 'Base seed', 'en': 'Base seed'},
    'pl2.pilot': {'uk': '🧪 Pilot ({n})', 'en': '🧪 Pilot ({n})'},
    'pl2.pilot_help': {'uk': 'Згенерувати невелику пробну партію перед великою чергою — оцінити якість, не палячи кредити.', 'en': 'Generate a small pilot batch before the full queue — gauge quality without burning credits.'},
    'pl2.avg_rating': {'uk': 'Середній рейтинг', 'en': 'Average rating'},
    'pl2.engine_winner': {'uk': 'Двигун-переможець', 'en': 'Engine winner'},
    'pl2.apply_engine_winner': {'uk': '⚡ Застосувати двигун-переможець', 'en': '⚡ Apply winning engine'},
    'pl2.polish_recommended': {'uk': 'Рекомендуємо LLM-полірування на Етапі 1 перед генерацією: {parts}', 'en': 'We recommend LLM polish on Stage 1 before generation: {parts}'},
    'pl2.regen_spin': {'uk': 'Перегенерація зображення…', 'en': 'Regenerating image…'},
    'pl2.regen_ok': {'uk': 'Зображення #{n} перегенеровано.', 'en': 'Image #{n} regenerated.'},
    'pl2.regen_failed': {'uk': 'Перегенерація не вдалася: {err}', 'en': 'Regeneration failed: {err}'},
    'pl2.large_batch_warn': {'uk': 'Велика черга ({n} зображень, ~{cr} кр.). Рекомендуємо спочатку Pilot.', 'en': 'Large queue ({n} images, ~{cr} cr). We recommend Pilot first.'},
    'pl2.large_batch_confirm': {'uk': 'Підтверджую запуск повної черги', 'en': 'I confirm running the full queue'},
    'pl2.bulk_min_star': {'uk': 'Поріг ★', 'en': 'Min ★'},
    'pl2.bulk_min_star_help': {'uk': 'Мінімум зірок для «Схвалити ≥ N★». Кадри з ★=0 не враховуються — спочатку **QA → ★** або слайдер під зображенням.', 'en': 'Minimum stars for «Approve ≥ N★». Frames at ★=0 are skipped — use **QA → ★** or the slider under each image first.'},
    'pl2.auto_rate_qa': {'uk': '⭐ QA → ★', 'en': '⭐ QA → ★'},
    'pl2.auto_rate_qa_help': {'uk': 'Технічна оцінка (blur/blank/corrupt) → зірки 1–5. Ручні ★ не перезаписує.', 'en': "Technical score (blur/blank/corrupt) → stars 1–5. Won't overwrite manual ★."},
    'pl2.auto_rate_hint': {'uk': '⭐ Auto-QA: проставлено оцінку для **{n}** кадр(ів) — перевірте й схваліть.', 'en': '⭐ Auto-QA: rated **{n}** frame(s) — review and approve.'},
    'pl2.auto_rate_none': {'uk': 'Усі видимі кадри вже мають ручну оцінку — QA не змінював.', 'en': 'All visible frames already manually rated — QA unchanged.'},
    'pl2.bulk_none_at_star': {'uk': 'Немає кадрів з оцінкою ≥ {star}★ — знизь поріг або натисніть **QA → ★**.', 'en': 'No frames rated ≥ {star}★ — lower threshold or click **QA → ★**.'},
    'pl2.bulk_approve': {'uk': '✅ Схвалити всі ≥ {star}★', 'en': '✅ Approve all ≥ {star}★'},
    'pl2.bulk_approve_help': {'uk': 'Увімкнути toggle «Схвалити» лише для видимих кадрів із ★ ≥ порогу. У чергу не зберігає — натисніть **Зберегти** нижче.', 'en': 'Turn on «Approve» toggles for visible frames rated ≥ threshold. Does not save yet — click **Save** below.'},
    'pl2.bulk_bar_title': {'uk': '##### 👥 Групове схвалення', 'en': '##### 👥 Group approval'},
    'pl2.bulk_bar_caption': {'uk': '**Кроки:** 1) оцініть (⭐ QA → ★ або слайдер) · 2) позначте кадри (☑️ усі або ≥поріг) · 3) перевірте toggle · 4) **Зберегти** або одразу **експорт**.', 'en': '**Steps:** 1) rate (⭐ QA → ★ or slider) · 2) mark frames (☑️ all or ≥threshold) · 3) review toggles · 4) **Save** or straight to **export**.'},
    'pl2.approve_all_visible': {'uk': '☑️ Позначити всі на екрані ({n})', 'en': '☑️ Select all on screen ({n})'},
    'pl2.approve_all_visible_help': {'uk': 'Увімкнути toggle у всіх **видимих** кадрів (після фільтрів), незалежно від ★. Перед експортом перевірте оцінки вручну.', 'en': 'Turn on toggles for all **visible** frames (after filters), regardless of ★. Review ratings manually before export.'},
    'pl2.bulk_save_export': {'uk': '✅ Схвалити ≥{star}★ і перейти до експорту', 'en': '✅ Approve ≥{star}★ and go to export'},
    'pl2.bulk_save_export_help': {'uk': 'Одразу зберегти всі видимі кадри ≥ порогу в чергу мінту й перейти на **3️⃣ Експорт** (toggle не потрібні).', 'en': 'Save all visible frames ≥ threshold to the mint queue and jump to **3️⃣ Export** (no toggles needed).'},
    'pl2.bulk_export_confirm_warn': {'uk': 'Перейти на **3️⃣ Експорт** з **{n}** кадрами ≥{star}★? Переконайтесь, що переглянули всі кадри вручну — дія незворотна для поточного перегляду.', 'en': 'Go to **3️⃣ Export** with **{n}** frames ≥{star}★? Make sure you reviewed every frame manually — this action cannot be undone for the current view.'},
    'pl2.bulk_export_confirm_yes': {'uk': '✅ Так, зберегти й перейти', 'en': '✅ Yes, save and go'},
    'pl2.bulk_export_confirm_no': {'uk': 'Скасувати', 'en': 'Cancel'},
    'pl2.regen_cost_hint': {'uk': '🔄 Перегенерація кадра: **{engine}** — **{per}** кр/зобр. Дешевше: **{alt}** ({alt_per} кр/зобр). Двигун обирається вище в панелі генерації.', 'en': '🔄 Regenerate frame: **{engine}** — **{per}** cr/image. Cheaper: **{alt}** ({alt_per} cr/image). Engine is selected above in the generation panel.'},
    'pl2.regen_cost_info': {'uk': '🔄 Перегенерація кадра: **{engine}** — **{per}** кр/зобр (двигун обирається вище).', 'en': '🔄 Regenerate frame: **{engine}** — **{per}** cr/image (engine selected above).'},
    'pl2.save_and_export': {'uk': '✅ Зберегти і перейти до експорту', 'en': '✅ Save and go to export'},
    'pl2.save_and_export_help': {'uk': 'Зберегти кадри з увімкненим toggle у чергу мінту й перейти на **3️⃣ Експорт**.', 'en': 'Save frames with toggles on to the mint queue and go to **3️⃣ Export**.'},
    'pl2.save_section_caption': {'uk': 'Після групового позначення перевірте toggle під кожним кадром, потім збережіть.', 'en': 'After bulk selection, review toggles under each frame, then save.'},
    'pl2.pilot_low_warn': {'uk': '⚠️ Середній рейтинг низький ({avg}). Спробуйте інший двигун/стиль або polish перед великою чергою.', 'en': '⚠️ Average rating is low ({avg}). Try another engine/style or polish before the full queue.'},
    'pl2.engine': {'uk': 'Двигун', 'en': 'Engine'},
    'pl2.engine_a': {'uk': 'Двигун A', 'en': 'Engine A'},
    'pl2.engine_b': {'uk': 'Двигун B', 'en': 'Engine B'},
    'pl2.size': {'uk': 'Розмір', 'en': 'Size'},
    'pl2.limit': {'uk': 'Скільки генерувати зараз', 'en': 'How many to generate now'},
    'pl2.connect_wallet': {'uk': '👛 Підключіть гаманець на **💳 Кредити**.', 'en': '👛 Connect wallet on **💳 Credits**.'},
    'pl2.low_credits': {'uk': 'Недостатньо кредитів.', 'en': 'Insufficient credits.'},
    'pl2.unverified_wallet': {'uk': '🔒 Генерація недоступна для непідтвердженого гаманця. Підключіть EVM-гаманець із підписом на **💳 Кредити**.', 'en': '🔒 Generation is disabled for an unverified wallet. Connect an EVM wallet with a signature on **💳 Credits**.'},
    'pl2.debit_info': {'uk': 'Списання: **{per}** кредит(и)/зображення · баланс **{bal}** · ліміт **{rate}**/хв', 'en': 'Debit: **{per}** credit(s)/image · balance **{bal}** · limit **{rate}**/min'},
    'pl2.run_ab': {'uk': '🔀 A/B порівняння', 'en': '🔀 A/B compare'},
    'pl2.run_batch': {'uk': '🚀 Запустити генерацію ({n} зображень)', 'en': '🚀 Start generation ({n} images)'},
    'pl2.run_batch_continue': {'uk': '▶️ Продовжити з #{from_} ({n} зображень)', 'en': '▶️ Continue from #{from_} ({n} images)'},
    'pl2.batch_resume': {'uk': 'У партії вже **{done}/{total}** кадрів. Залишилось **{remaining}** — наступний Run **допише**, не перезапише.', 'en': 'Batch has **{done}/{total}** frames. **{remaining}** left — next Run **appends**, does not overwrite.'},
    'pl2.batch_complete': {'uk': '✅ Усі **{n}** промпти вже згенеровано. Очистіть партію, щоб почати спочатку.', 'en': '✅ All **{n}** prompts generated. Clear batch to start over.'},
    'pl2.clear_batch': {'uk': '🗑 Очистити партію', 'en': '🗑 Clear batch'},
    'pl2.gen_ok_append': {'uk': 'Додано {n} зображень ({cr} cr). У партії зараз **{total}**.', 'en': 'Added {n} images ({cr} cr). Batch total **{total}**.'},
    'pl2.gen_partial_append': {'uk': 'Додано {ok}, помилок: {err}. У партії **{total}**. Перша: {first}', 'en': 'Added {ok}, errors: {err}. Batch total **{total}**. First: {first}'},
    'pl2.engine_cost_warn': {'uk': '⚠️ **{engine}** коштує **{per}** кр/зобр → **{total}** кр за {n}. Дешевше: **{alt}** ({alt_per} кр/зобр = {alt_total} кр).', 'en': '⚠️ **{engine}** costs **{per}** cr/image → **{total}** cr for {n}. Cheaper: **{alt}** ({alt_per} cr/image = {alt_total} cr).'},
    'pl2.pilot_recommend': {'uk': '💡 Рекомендуємо почати з Pilot: перевірте стиль на малій партії, перш ніж витрачати кредити на повний дроп.', 'en': '💡 Start with Pilot: check the style on a small batch before spending credits on the full drop.'},
    'pl2.rate_wave_warn': {'uk': '⏳ Ліміт {rate}/хв: {n} зображень підуть хвилями (~{waves} хв, пауза між хвилями автоматична).', 'en': '⏳ Limit {rate}/min: {n} images run in waves (~{waves} min, auto-pause between waves).'},
    'pl2.approved_running': {'uk': '✅ У черзі мінту збережено: **{n}**', 'en': '✅ Saved to mint queue: **{n}**'},
    'pl2.rate_limit': {'uk': 'Ліміт {rate} генерацій/хв. Зачекайте.', 'en': 'Limit {rate} generations/min. Please wait.'},
    'pl2.freemium_limit': {'uk': 'Денний ліміт безкоштовних генерацій вичерпано. Поповніть кредити на **💳 Кредити** або спробуйте завтра.', 'en': 'Daily free-generation limit reached. Top up credits on **💳 Credits** or try again tomorrow.'},
    'pl2.engine_hint': {'uk': "💡 Для цієї ідеї добре підійде двигун **{engine}** (підказка, не обов'язково).", 'en': '💡 For this idea, the **{engine}** engine fits well (a hint, not required).'},
    'pl2.queue_progress': {'uk': 'Черга генерації…', 'en': 'Generation queue…'},
    'pl2.queue_done': {'uk': 'Готово {done} / {total}…', 'en': 'Done {done} / {total}…'},
    'pl2.caption': {'uk': 'Згенеруйте зображення за промптами → оцініть і відсортуйте в **Панелі Куратора** → схваліть найкращі. Схвалені підуть на **3️⃣ Експорт**.', 'en': 'Generate images from prompts → rate & sort in the **Curator Panel** → approve the best. Approved items go to **3️⃣ Export**.'},
    'pl2.gen_partial': {'uk': 'Згенеровано {ok}, помилок: {err}. Перша: {first}', 'en': 'Generated {ok}, errors: {err}. First: {first}'},
    'pl2.gen_partial_moderation_hint': {'uk': '**Порада:** OpenAI іноді блокує **output** (не промпт). У кураторі — **Regenerate** для пропущеного кадру з **Flux/Stability**, або увімкніть `IMAGE_CASCADE_ENABLED=1`.', 'en': '**Tip:** OpenAI sometimes blocks **output** (not your prompt). In the curator — **Regenerate** the missing frame with **Flux/Stability**, or set `IMAGE_CASCADE_ENABLED=1`.'},
    'pl2.gen_ok': {'uk': 'Згенеровано {n} зображень ({cr} cr). Оцініть і відфільтруйте нижче.', 'en': 'Generated {n} images ({cr} cr). Rate and filter below.'},
    'pl2.ab_errors': {'uk': 'Помилки A/B: {errs}', 'en': 'A/B errors: {errs}'},
    'pl2.ab_ok': {'uk': 'A/B готово: {n} варіант(и). Порівняйте та оцініть нижче.', 'en': 'A/B done: {n} variant(s). Compare and rate below.'},
    'pl2.ab_spin': {'uk': 'A/B порівняння двигунів…', 'en': 'A/B engine comparison…'},
    'pl2.parallel_spin': {'uk': 'Паралельна черга (до 3 одночасно)…', 'en': 'Parallel queue (up to 3 at once)…'},
    'pl2.curator_title': {'uk': '##### 🧑\u200d⚖️ Панель Куратора ({n} зображень)', 'en': '##### 🧑\u200d⚖️ Curator Panel ({n} images)'},
    'pl2.curator_lite_title': {'uk': '##### ✅ Схвали зображення', 'en': '##### ✅ Approve your image'},
    'pl2.curator_lite_caption': {'uk': '1/1: оціни кадр і натисни «Зберегти» — одразу перейдеш до експорту.', 'en': "1/1: rate the frame and click «Save» — you'll go straight to export."},
    'pl2.curator_shown': {'uk': 'Показано **{shown}** з {total} після фільтрів.', 'en': 'Showing **{shown}** of {total} after filters.'},
    'pl2.curator_empty': {'uk': 'Жодне зображення не проходить фільтри · **Зараз:** знизь **мін. рейтинг** або **Rarity Score** · **Альтернатива:** згенеруй ще кадри або **Regenerate** слабкі.', 'en': 'No images pass filters · **Now:** lower **min rating** or **Rarity Score** · **Alternative:** generate more frames or **Regenerate** weak ones.'},
    'pl2.save_mint': {'uk': '💾 Зберегти обрані ({n})', 'en': '💾 Save selected ({n})'},
    'pl2.approved': {'uk': 'Схвалено {n} робіт. Далі → **3️⃣ Експорт**.', 'en': 'Approved {n} items. Next → **3️⃣ Export**.'},
    'pl2.approved_append': {'uk': 'Додано {n} до черги (всього **{total}**). Далі → **3️⃣ Експорт**.', 'en': 'Added {n} to queue (**{total}** total). Next → **3️⃣ Export**.'},
    'pl2.append_approved': {'uk': 'Додавати до черги (не замінювати)', 'en': "Append to queue (don't replace)"},
    'pl2.append_approved_help': {'uk': 'Увімкнено: нові схвалені додаються до вже збережених між хвилями генерації.', 'en': 'When on, newly approved items are added to already saved ones between generation waves.'},
    'pl2.final_pass_borderline': {'uk': '✨ Final-pass для 3★ ({n})', 'en': '✨ Final-pass for 3★ ({n})'},
    'pl2.final_pass_spin': {'uk': 'Final-pass для borderline зображень…', 'en': 'Final-pass for borderline images…'},
    'pl2.final_pass_done': {'uk': 'Final-pass: оновлено {ok} з {n}.', 'en': 'Final-pass: updated {ok} of {n}.'},
    'curator.title': {'uk': '##### 🔍 Галерея та фільтри', 'en': '##### 🔍 Gallery & filters'},
    'curator.min_rating': {'uk': 'Мін. рейтинг', 'en': 'Min. rating'},
    'curator.min_rarity': {'uk': 'Мін. Rarity Score', 'en': 'Min. Rarity Score'},
    'curator.trait_filter': {'uk': 'Фільтр trait / промпт', 'en': 'Trait / prompt filter'},
    'curator.tier': {'uk': 'Rarity Tier', 'en': 'Rarity Tier'},
    'curator.sort': {'uk': 'Сортування', 'en': 'Sort by'},
    'curator.sort_num': {'uk': 'За #', 'en': 'By #'},
    'curator.sort_rating': {'uk': 'Рейтинг ↓', 'en': 'Rating ↓'},
    'curator.sort_rarity': {'uk': 'Rarity Score ↓', 'en': 'Rarity Score ↓'},
    'curator.sort_qa': {'uk': 'QA Score ↓', 'en': 'QA Score ↓'},
    'curator.min_qa': {'uk': 'Мін. QA Score', 'en': 'Min. QA Score'},
    'curator.min_qa_help': {'uk': '0 = без фільтра. Вище — ховає зображення з низьким Auto-QA (blur/blank/corrupt).', 'en': '0 = no filter. Higher hides images with low Auto-QA (blur/blank/corrupt).'},
    'curator.rate': {'uk': 'Оцінка #{n}', 'en': 'Rating #{n}'},
    'curator.rate_help': {'uk': '0 = неоцінено (не потрапляє в «≥ N★»). Для швидкої оцінки — **QA → ★** зверху.', 'en': '0 = unrated (excluded from «≥ N★»). For quick rating — **QA → ★** above.'},
    'curator.approve': {'uk': 'Схвалити #{n}', 'en': 'Approve #{n}'},
    'curator.approve_help': {'uk': 'Увімкніть, щоб кадр потрапив у **Зберегти** нижче. Групові кнопки зверху лише позначають toggle.', 'en': 'Turn on to include this frame in **Save** below. Bulk buttons above only set toggles.'},
    'curator.regenerate': {'uk': '🔄 Перегенерувати #{n}', 'en': '🔄 Regenerate #{n}'},
    'curator.qa_card_ok': {'uk': 'Auto-QA **{score}**/100 — технічна перевірка (blur/blank/corrupt), не естетика. Орієнтир: ~{star}★ через «QA → ★».', 'en': 'Auto-QA **{score}**/100 — technical check (blur/blank/corrupt), not aesthetics. Hint: ~{star}★ via «QA → ★».'},
    'curator.qa_card_warn': {'uk': 'Auto-QA **{score}**/100 ⚠ — {issues}. Технічна перевірка, не естетика; орієнтир ~{star}★ через «QA → ★».', 'en': 'Auto-QA **{score}**/100 ⚠ — {issues}. Technical check, not aesthetics; hint ~{star}★ via «QA → ★».'},
    'curator.qa_issue_corrupt': {'uk': 'пошкоджений файл', 'en': 'corrupt file'},
    'curator.qa_issue_tiny': {'uk': 'занадто малий розмір', 'en': 'too small'},
    'curator.qa_issue_blank': {'uk': 'порожнє/однотонне', 'en': 'blank/solid'},
    'curator.qa_issue_blurry': {'uk': 'розмиття', 'en': 'blur'},
    'curator.zoom': {'uk': '🔍 Збільшити #{n}', 'en': '🔍 Zoom #{n}'},
    'curator.zoom_title': {'uk': 'Перегляд #{n}', 'en': 'Preview #{n}'},
    'curator.zoom_prompt': {'uk': '**Промпт:**', 'en': '**Prompt:**'},
    'curator.zoom_traits': {'uk': '**Трейти:**', 'en': '**Traits:**'},
    'pl3.title': {'uk': '##### 👛 Етап 3 — Експорт контенту (готово до мінту)', 'en': '##### 👛 Stage 3 — Export content (mint-ready)'},
    'pl3.queue_count': {'uk': '**Черга: {n} активів**', 'en': '**Queue: {n} assets**'},
    'pl3.coll_name': {'uk': 'Назва колекції (EN)', 'en': 'Collection name (EN)'},
    'pl3.coll_name_ph': {'uk': 'Cosmic Oracles', 'en': 'Cosmic Oracles'},
    'pl3.coll_name_help': {'uk': 'Латиниця без пробілів на початку/кінці. Потрапляє в metadata OpenSea/Metaplex і в імʼя ZIP. Без кирилиці та емодзі.', 'en': 'Latin text, no leading/trailing spaces. Used in OpenSea/Metaplex metadata and the ZIP filename. No Cyrillic or emoji.'},
    'pl3.coll_name_hint': {'uk': 'Приклад: **Cosmic Oracles** → токени «Cosmic Oracles #1», ZIP `Cosmic-Oracles-opensea.zip`.', 'en': 'Example: **Cosmic Oracles** → tokens «Cosmic Oracles #1», ZIP `Cosmic-Oracles-opensea.zip`.'},
    'pl3.coll_name_warn_non_ascii': {'uk': '⚠️ У назві є не-латинські символи — OpenSea/Metaplex можуть відхилити metadata. Використовуйте лише A–Z, цифри, пробіли та дефіс.', 'en': '⚠️ Non-Latin characters detected — OpenSea/Metaplex may reject metadata. Use A–Z, digits, spaces, and hyphens only.'},
    'pl3.coll_name_warn_spaces': {'uk': '⚠️ Зайві пробіли на початку/кінці або подвійні пробіли — приберіть їх перед експортом.', 'en': '⚠️ Leading/trailing or double spaces — trim them before export.'},
    'pl3.advanced_mint': {'uk': '⚙️ Розширене: мінт у застосунку (опційно)', 'en': '⚙️ Advanced: mint in app (optional)'},
    'pl3.export.title': {'uk': '### 📦 Експорт mint-ready бандла', 'en': '### 📦 Export mint-ready bundle'},
    'pl3.export.caption': {'uk': 'Застосунок сам мінт не проводить — він готує контент (зображення + метадані) у форматі обраної платформи. Де мінтити, вирішуєте ви.', 'en': 'The app does not mint itself — it prepares content (images + metadata) in the format of the chosen platform. You decide where to mint.'},
    'pl3.export.platform': {'uk': 'Платформа / формат', 'en': 'Platform / format'},
    'pl3.export.symbol': {'uk': 'Символ', 'en': 'Symbol'},
    'pl3.export.royalty': {'uk': 'Роялті (%)', 'en': 'Royalty (%)'},
    'pl3.export.creator': {'uk': 'Creator (Solana)', 'en': 'Creator (Solana)'},
    'pl3.export.build_zip': {'uk': '🗜️ Зібрати ZIP', 'en': '🗜️ Build ZIP'},
    'pl3.export.download_zip': {'uk': '⬇️ Завантажити ZIP', 'en': '⬇️ Download ZIP'},
    'pl3.export.ipfs_folder': {'uk': '📁 Відвантажити в IPFS-папку', 'en': '📁 Upload to IPFS folder'},
    'pl3.export.need_jwt': {'uk': 'Потрібен PINATA_JWT', 'en': 'PINATA_JWT required'},
    'pl3.export.ipfs_spinner': {'uk': 'Відвантаження в IPFS…', 'en': 'Uploading to IPFS…'},
    'pl3.export.ipfs_done': {'uk': 'Відвантажено {n} токенів у IPFS.', 'en': 'Uploaded {n} tokens to IPFS.'},
    'pl3.export.ipfs_uris': {'uk': 'images   → {img}\nmetadata → {meta}  (baseURI для контракту)', 'en': 'images   → {img}\nmetadata → {meta}  (baseURI for contract)'},
    'pl3.share.title': {'uk': '### 🔗 Поділитись колекцією', 'en': '### 🔗 Share your collection'},
    'pl3.share.caption': {'uk': 'Опублікуйте публічну сторінку-вітрину колекції (read-only) — нею можна ділитись у соцмережах. Кожен перегляд має кнопку «Зроби свою».', 'en': 'Publish a public read-only showcase page for your collection — share it on socials. Every view has a «Make your own» button.'},
    'pl3.share.button': {'uk': '🌐 Опублікувати вітрину', 'en': '🌐 Publish showcase'},
    'pl3.share.done': {'uk': 'Опубліковано! Публічне посилання:', 'en': 'Published! Public link:'},
    'pl3.share.open': {'uk': '↗ Відкрити сторінку', 'en': '↗ Open page'},
    'pl3.share.empty': {'uk': 'Немає зображень для публікації — спершу зберіть чергу активів.', 'en': 'No images to publish — build the asset queue first.'},
    'pl3.queue_empty': {'uk': 'Черга порожня. **2️⃣ Зображення** → Куратор → «Зберегти обрані» → «Взяти схвалені». Або завантажте PNG нижче.', 'en': 'Queue empty. **2️⃣ Images** → Curator → «Save selected» → «Take approved». Or upload PNGs below.'},
    'pl3.from_stage2': {'uk': 'Вхід з Етапу 2: **{n} схвалених робіт**.', 'en': 'From Stage 2: **{n} approved items**.'},
    'pl3.take_approved': {'uk': '📥 Взяти схвалені роботи в чергу', 'en': '📥 Add approved work to queue'},
    'pl3.upload_expand': {'uk': '✍️ Точка входу 3: завантажити власні файли (JPG/PNG)', 'en': '✍️ Entry 3: upload own files (JPG/PNG)'},
    'pl3.upload_label': {'uk': 'Зображення для експорту', 'en': 'Images for export'},
    'pl3.take_uploads': {'uk': '📥 Взяти завантажені ({n}) в чергу', 'en': '📥 Add uploads ({n}) to queue'},
    'pl3.mint.ipfs_progress': {'uk': 'IPFS-пакування…', 'en': 'IPFS packaging…'},
    'pl3.mint.asset_progress': {'uk': 'Актив {i} / {total}…', 'en': 'Asset {i} / {total}…'},
    'pl3.mint.pack_errors': {'uk': 'Помилки пакування ({n}). Перша: {first}', 'en': 'Packaging errors ({n}). First: {first}'},
    'pl3.mint.pack_ok': {'uk': 'Запаковано {n} активів. Token URI готові — можна мінтити.', 'en': 'Packaged {n} assets. Token URIs ready — you can mint.'},
    'pl3.mint.public_links_title': {'uk': '🔗 Публічні посилання на активи (через тунель)', 'en': '🔗 Public asset links (via tunnel)'},
    'pl3.mint.public_links_caption': {'uk': 'Копіює зображення у `static/` — Streamlit роздає їх на `{app_url}/app/static/…`. Зовнішні Web3-сервіси скачують файли напряму швидкими GET-запитами, не впираючись у ліміт Cloudflare 100 с на запит. Посилання працюють, поки запущені застосунок і тунель.', 'en': 'Copies images to `static/` — Streamlit serves them at `{app_url}/app/static/…`. External Web3 services fetch files via fast GET requests without the Cloudflare 100s limit. Links work while the app and tunnel run.'},
    'pl3.mint.public_links_btn': {'uk': '🔗 Створити посилання', 'en': '🔗 Create links'},
    'pl3.mint.public_links_fail': {'uk': 'Не вдалося опублікувати {n} файл(ів) — можливо, їх уже прибрано.', 'en': 'Could not publish {n} file(s) — they may have been removed.'},
    'pl3.mint.col_name': {'uk': 'Назва', 'en': 'Name'},
    'pl3.mint.col_url': {'uk': 'URL', 'en': 'URL'},
    'pl3.mint.chain': {'uk': '1. Блокчейн', 'en': '1. Blockchain'},
    'pl3.mint.engine': {'uk': '2. Web3-двигун', 'en': '2. Web3 engine'},
    'pl3.mint.engine_help': {'uk': 'Thirdweb — лише EVM (Base). Для Solana використовується Crossmint.', 'en': 'Thirdweb — EVM only (Base). Solana uses Crossmint.'},
    'pl3.mint.coll_id': {'uk': 'Collection ID (provenance)', 'en': 'Collection ID (provenance)'},
    'pl3.mint.coll_id_ph': {'uk': 'uuid або slug колекції', 'en': 'collection uuid or slug'},
    'pl3.mint.coll_id_help': {'uk': 'Записується в on-chain metadata як Collection ID.', 'en': 'Stored in on-chain metadata as Collection ID.'},
    'pl3.mint.reveal': {'uk': '🎭 Reveal mode (placeholder зображення в metadata)', 'en': '🎭 Reveal mode (placeholder image in metadata)'},
    'pl3.mint.reveal_help': {'uk': 'У metadata буде placeholder; реальне зображення збережено в revealed_image_uri для оновлення після дропу.', 'en': 'Metadata uses a placeholder; the real image is stored in revealed_image_uri for post-drop update.'},
    'pl3.mint.creator_ph': {'uk': 'опційно', 'en': 'optional'},
    'pl3.mint.step_a': {'uk': '**Крок А — Авто-пакування в IPFS (Pinata)**', 'en': '**Step A — Auto-pack to IPFS (Pinata)**'},
    'pl3.mint.pinata_jwt': {'uk': 'Pinata JWT', 'en': 'Pinata JWT'},
    'pl3.mint.pinned_caption': {'uk': 'Запаковано: {pinned} / {total} · приклад Token URI: `{example}`', 'en': 'Packaged: {pinned} / {total} · sample Token URI: `{example}`'},
    'pl3.mint.pin_all_btn': {'uk': '📡 Запакувати все в IPFS', 'en': '📡 Pack all to IPFS'},
    'pl3.mint.step_b': {'uk': '**Крок Б — Мінтинг**', 'en': '**Step B — Minting**'},
    'pl3.mint.web3_missing': {'uk': 'Пакет `web3` не встановлено: `pip install web3`. Або оберіть Crossmint.', 'en': 'Package `web3` not installed: `pip install web3`. Or choose Crossmint.'},
    'pl3.mint.contract': {'uk': 'Адреса контракту (NFT Collection)', 'en': 'Contract address (NFT Collection)'},
    'pl3.mint.recipient': {'uk': 'Гаманець отримувача', 'en': 'Recipient wallet'},
    'pl3.mint.rpc': {'uk': 'RPC URL', 'en': 'RPC URL'},
    'pl3.mint.private_key': {'uk': 'Приватний ключ мінтера', 'en': 'Minter private key'},
    'pl3.mint.private_key_help': {'uk': 'Не зберігається. Використовуйте окремий гаманець-мінтер з мінімальним балансом.', 'en': 'Not stored. Use a separate minter wallet with minimal balance.'},
    'pl3.mint.batch_mode': {'uk': 'Batch mint однією транзакцією (multicall)', 'en': 'Batch mint in one transaction (multicall)'},
    'pl3.mint.batch_mode_help': {'uk': 'Усі mintTo пакуються в один multicall — одна комісія за газ на всю партію.', 'en': 'All mintTo calls in one multicall — one gas fee for the whole batch.'},
    'pl3.mint.btn_thirdweb': {'uk': '⛓️ Мінт {n} токенів через Thirdweb', 'en': '⛓️ Mint {n} tokens via Thirdweb'},
    'pl3.mint.cm_key': {'uk': 'Crossmint API Key', 'en': 'Crossmint API Key'},
    'pl3.mint.cm_coll': {'uk': 'Crossmint Collection ID', 'en': 'Crossmint Collection ID'},
    'pl3.mint.recipient_ph': {'uk': '0x… / pubkey / email:user@x.com:base', 'en': '0x… / pubkey / email:user@x.com:base'},
    'pl3.mint.staging': {'uk': 'Staging (тестове середовище)', 'en': 'Staging (test environment)'},
    'pl3.mint.btn_crossmint': {'uk': '⛓️ Мінт {n} токенів через Crossmint', 'en': '⛓️ Mint {n} tokens via Crossmint'},
    'pl3.mint.need_pin': {'uk': 'ℹ️ Кнопки мінту активуються після повного IPFS-пакування (Крок А) і заповнення полів.', 'en': 'ℹ️ Mint buttons activate after full IPFS packaging (Step A) and required fields are filled.'},
    'pl3.mint.cleanup': {'uk': '🧹 Тимчасові файли прибрано (temp_assets/ і static/, {n} шт.) — контент уже в IPFS.', 'en': '🧹 Temp files removed (temp_assets/ and static/, {n} items) — content is already on IPFS.'},
    'pl3.mint.batch_spin': {'uk': 'Batch mint {n} токенів однією транзакцією…', 'en': 'Batch mint {n} tokens in one transaction…'},
    'pl3.mint.progress': {'uk': 'Мінтинг…', 'en': 'Minting…'},
    'pl3.mint.token_progress': {'uk': 'Токен {i} / {total}…', 'en': 'Token {i} / {total}…'},
    'pl3.results.title': {'uk': '**Результати**', 'en': '**Results**'},
    'pl3.results.col_num': {'uk': '#', 'en': '#'},
    'pl3.results.col_name': {'uk': 'Назва', 'en': 'Name'},
    'pl3.results.col_uri': {'uk': 'Token URI', 'en': 'Token URI'},
    'pl3.results.col_status': {'uk': 'Статус', 'en': 'Status'},
    'pl3.results.col_tx': {'uk': 'Tx / ID', 'en': 'Tx / ID'},
    'pl3.results.dash': {'uk': '—', 'en': '—'},
}
