"""i18n-рядки: домен shell (оболонка UI: sidebar, welcome, навігація, теми, спільне).

Збираються в `ui_strings._STRINGS` через `ui_strings._merge_strings()`. НЕ імпортуй
цей модуль у застосунку — використовуй `ui_strings.t()`. Парність uk↔en, плейсхолдери
й повноту ключів звіряє `tests/test_ui_strings.py` проти зібраного `_STRINGS`.
"""

STRINGS: dict[str, dict[str, str]] = {
    'lang.label': {'uk': 'Мова інтерфейсу', 'en': 'Interface language'},
    'theme.label': {'uk': 'Тема', 'en': 'Theme'},
    'theme.dark': {'uk': '🌙 Темна', 'en': '🌙 Dark'},
    'theme.light': {'uk': '☀️ Світла', 'en': '☀️ Light'},
    'a11y.collapse_sidebar': {'uk': 'Згорнути sidebar', 'en': 'Collapse sidebar'},
    'a11y.expand_sidebar': {'uk': 'Розгорнути sidebar', 'en': 'Expand sidebar'},
    'common.dismiss': {'uk': 'Приховати', 'en': 'Dismiss'},
    'common.all': {'uk': 'Усі', 'en': 'All'},
    'common.dash': {'uk': '—', 'en': '—'},
    'app.title': {'uk': '🚀 Професійний Конструктор NFT-Промтів', 'en': '🚀 Professional NFT Prompt Builder'},
    'app.page_title': {'uk': 'Professional NFT Prompt Builder', 'en': 'Professional NFT Prompt Builder'},
    'app.og_description': {'uk': 'Idea → AI art → mint-ready bundle in 15 minutes. Pay-as-you-go, non-custodial.', 'en': 'Idea → AI art → mint-ready bundle in 15 minutes. Pay-as-you-go, non-custodial.'},
    'app.hero.classic': {'uk': 'Шлях «Колекція»: ідея → traits → batch → швидке превʼю / images → ZIP · ваш API-ключ (+ cr на ai.w3ir.io)', 'en': 'Collection path: idea → traits → batch → quick preview / images → ZIP · your API key (+ cr on ai.w3ir.io)'},
    'app.hero.pipeline': {'uk': 'Шлях «Конвеєр»: текст → зображення (кредити) → export (OpenSea, Thirdweb, Metaplex / Magic Eden, …)', 'en': 'Pipeline path: text → images (credits) → export (OpenSea, Thirdweb, Metaplex / Magic Eden, …)'},
    'app.no_api_key': {'uk': '⚠️ Ключ OpenAI API не знайдено. Створіть `.env` або введіть ключ у бічній панелі.', 'en': '⚠️ OpenAI API key not found. Create `.env` or enter the key in the sidebar.'},
    'app.version': {'uk': 'v4.3.3 · NFT Prompt Builder', 'en': 'v4.3.3 · NFT Prompt Builder'},
    'app.trust_strip': {'uk': '<span>🔐 Вхід через SIWE</span><span>🔑 Non-custodial</span><span>💳 Оплата за використання</span><span>⛓️ Base · Solana</span>', 'en': '<span>🔐 SIWE login</span><span>🔑 Non-custodial</span><span>💳 Pay-as-you-go</span><span>⛓️ Base · Solana</span>'},
    'welcome.title': {'uk': '### 👋 З чого почнемо?', 'en': '### 👋 Where to start?'},
    'welcome.subtitle': {'uk': '3 кроки до mint-ready колекції: **Промпт → Зображення → Експорт**.', 'en': '3 steps to a mint-ready collection: **Prompt → Image → Export**.'},
    'welcome.pilot_playbook': {
        'uk': '**💡 Міні-дроп:** Pilot **10** → рейтинг у кураторі → **двигун-переможець** → повний run → QC **≥75** → export. Рецепт: **📖 Довідка § 4.4.2**.',
        'en': '**💡 Mini-drop:** Pilot **10** → rate in curator → **engine winner** → full run → QC **≥75** → export. Recipe: **📖 Help § 4.4.2**.',
    },
    'welcome.one': {'uk': '🚀 1 NFT (1/1)', 'en': '🚀 1 NFT (1/1)'},
    'welcome.one_desc': {'uk': 'Унікальний арт-твір за ~10 хв · шаблон 1/1 Fine Art', 'en': 'A unique 1/1 art piece in ~10 min · 1/1 Fine Art template'},
    'welcome.batch': {'uk': '📦 Міні-дроп 25', 'en': '📦 Mini-drop 25'},
    'welcome.batch_desc': {'uk': '≈25 NFT · абстрактна геометрія · висока варіативність', 'en': '~25 NFT · abstract geometry · high variety'},
    'welcome.advanced': {'uk': '⚙️ Розширений режим', 'en': '⚙️ Advanced mode'},
    'welcome.advanced_desc': {'uk': 'Generative 500+ · traits, Batch, Колекція (класичні вкладки)', 'en': 'Generative 500+ · traits, Batch, Collection (classic tabs)'},
    'welcome.guide_label': {'uk': '📋 Детальний гайд', 'en': '📋 Detailed guide'},
    'welcome.one_guide': {'uk': '**Для кого:** один унікальний арт-твір — 1/1, PFP, обкладинка, сингл-мінт.\n\n**Результат:** 1 зображення + metadata + mint-ready ZIP (OpenSea / Thirdweb / Metaplex / W3IR).\n\n**Крок за кроком (вкладка Конвеєр):**\n1. **💳 Кредити** — підключи гаманець (Sign-In). Новим гаманцям — до **5** вітальних кредитів (EVM з мін. балансом ETH на Base). Або пакет **Start $4.99 = 100** cr.\n2. **1️⃣ Текст** — Етап 1. Шаблон *1/1 Fine Art* уже застосовано; промпт зʼявиться автоматично — підправ ідею/стиль. Режим **Сингл** → «Зібрати один промпт». Опційно: lint + **polish** (1 cr). Збережи промпт.\n3. **2️⃣ Зображення** — Етап 2. Двигун **Flux / Stability = 1 cr**, OpenAI = 4 cr (draft). Згенеруй 1–3 варіанти; слабкі — **Regenerate** у кураторі. Оцінка **≥4★** → **Схвалити** → «Зберегти обрані».\n4. **3️⃣ Експорт** — Export Center: preflight (рейтинг, цілісність файлу). Завантаж **ZIP** або pin **IPFS** (Pinata). On-chain мінт — окремо (Thirdweb / OpenSea Studio).\n\n**Кредити (типово):** 1–4 cr на фінальний кадр (+1 cr за polish).\n**Порада:** у sidebar **🏠 Обрати напрям** — повернутися на цей екран.\n\n⏱ **~10–15 хв**', 'en': '**For whom:** a single unique piece — 1/1 art, PFP, cover, one-off mint.\n\n**Outcome:** 1 image + metadata + mint-ready ZIP (OpenSea / Thirdweb / Metaplex / W3IR).\n\n**Step by step (Pipeline tab):**\n1. **💳 Credits** — connect your wallet (Sign-In). New wallets get up to **5** welcome credits (EVM with min ETH balance on Base). Or **Start $4.99 = 100** cr.\n2. **1️⃣ Text** — Stage 1. The *1/1 Fine Art* template is pre-applied; a prompt appears automatically — tweak the idea/style. **Single** mode → «Build one prompt». Optional: lint + **polish** (1 cr). Save the prompt.\n3. **2️⃣ Images** — Stage 2. Engine **Flux / Stability = 1 cr**, OpenAI = 4 cr (draft). Render 1–3 variants; weak ones — **Regenerate** in the curator. Rate **≥4★** → **Approve** → «Save selected».\n4. **3️⃣ Export** — Export Center: preflight (rating, file integrity). Download **ZIP** or pin **IPFS** (Pinata). On-chain minting is separate (Thirdweb / OpenSea Studio).\n\n**Credits (typical):** 1–4 cr for the final frame (+1 cr for polish).\n**Tip:** sidebar **🏠 Choose your path** returns you to this screen.\n\n⏱ **~10–15 min**'},
    'welcome.batch_guide': {'uk': '**Для кого:** міні-дроп **≈25 NFT** — абстрактна геометрія, бренд, пейзаж або івент-бейдж (не PFP з 6 traits).\n\n**Результат:** 25 зображень + rarity/metadata + export-бандл під маркетплейс.\n\n**Крок за кроком (вкладка Конвеєр):**\n1. **💳 Кредити** — підключи гаманець. На 25 кадрів (Flux draft): **~25 cr** + запас на regenerate. Пакет **Creator $14.99 = 400 cr** зазвичай вистачає.\n2. **1️⃣ Текст** — Етап 1. Стартовий шаблон *Abstract Geometry Series* (5 форм × 5 фонів = 25 промптів). Підправ ідею в sidebar за потреби. Опційно: **Rich prompts** (LLM-polish після матриці). Збережи чергу промптів.\n3. **2️⃣ Зображення** — Етап 2. Рекомендовано: **Pilot ~10** → рейтинг → «Застосувати двигун-переможець» → повний run. **Hybrid** tier — баланс ціна/якість. У **Кураторі**: фільтр слабких, **Regenerate**, bulk **≥4★**, «Зберегти обрані».\n4. **3️⃣ Експорт** — preflight (min rating, дублікати, corrupt). **ZIP** + опційно **IPFS**. Upscale 2048 — чекбокс перед export. Платформи: OpenSea, Thirdweb, Metaplex, **W3IR .w3ir-nft.zip**.\n\n**Кредити (орієнтир):** 25–40 cr (залежить від двигуна та regenerate).\n**Порада:** step bar зверху веде 💳→1→2→3; кнопки «← / →» між етапами.\n**Усі гайди міні-дропів:** вкладка Довідка **§ 4.1.8** (кожен шаблон ~25).\n\n⏱ **~20–40 хв**', 'en': '**For whom:** a mini-drop of **~25 NFTs** — abstract geometry, brand icons, landscapes, or event badges (not 6-trait PFP).\n\n**Outcome:** 25 images + rarity/metadata + marketplace-ready export bundle.\n\n**Step by step (Pipeline tab):**\n1. **💳 Credits** — connect your wallet. For 25 frames (Flux draft): **~25 cr** plus headroom for regenerates. **Creator $14.99 = 400 cr** is usually enough.\n2. **1️⃣ Text** — Stage 1. Starter template *Abstract Geometry Series* (5 shapes × 5 backgrounds = 25 prompts). Tweak the idea in the sidebar if needed. Optional: **Rich prompts** (LLM polish). Save the prompt queue.\n3. **2️⃣ Images** — Stage 2. Recommended: **Pilot ~10** → rate → «Apply engine winner» → full run. **Hybrid** tier balances cost/quality. In the **Curator**: filter weak frames, **Regenerate**, bulk **≥4★**, «Save selected».\n4. **3️⃣ Export** — preflight (min rating, duplicates, corrupt files). **ZIP** + optional **IPFS**. 2048 upscale — checkbox before export. Platforms: OpenSea, Thirdweb, Metaplex, **W3IR .w3ir-nft.zip**.\n\n**Credits (estimate):** 25–40 cr (engine + regenerates).\n**Tip:** sidebar **🏠 Choose your path** returns you to this screen.\n**All mini-drop guides:** Help tab **§ 4.1.8** (every ~25 template).\n\n⏱ **~20–40 min**'},
    'welcome.advanced_guide': {'uk': '**Для кого:** велика **generative-колекція (50–10 000+)** з traits, rarity-матрицею і повним контролем над промптами.\n\n**Результат:** сотні/тисячі унікальних комбінацій + Rarity Score/Rank + export.\n\n**Крок за кроком (класичні вкладки):**\n1. **💳 Кредити** — підключи гаманець. Великий обсяг: **Pro $29.99 = 1000 cr** або власний OpenAI key у sidebar (Classic Images).\n2. **🛠️ Конструктор** — ідея, стиль, камера, світло. Шаблон з sidebar → «Застосувати».\n3. **🧬 Traits** — категорії (Голова, Очі, Фон…), ваги рідкісності, rarity-слайдери. Перевір комбінації.\n4. **📦 Batch** — тест **10–20** промптів (перевірка якості тексту перед повним run).\n5. **🏭 Колекція** — повна генерація промптів (50–10 000). Checkpoint + resume.\n6. **⑤ Швидке превʼю** — 1–4 картинки для тесту промпта (**OpenAI key** + на ai.w3ir.io ще **4 cr/кадр**; це не mint-ready дроп) **або** кнопка «→ У Конвеєр» → Етап 2 (кредити, куратор, export).\n7. **Експорт** — ZIP/IPFS, provenance, rarity-звіт.\n\n**Коли Classic, коли Конвеєр:** 50+ traits-heavy — Classic; 25–100 без складної матриці — швидше через **Конвеєр → Матриця**; бренд/community 25 — шаблон **Brand Icon System** (див. довідку § 4.1.2).\n**Порада:** sidebar → «Перемкнути на Конвеєр» повертає рекомендований шлях.\n\n⏱ **години** (залежить від supply)', 'en': '**For whom:** a large **generative collection (50–10,000+)** with traits, a rarity matrix, and full prompt control.\n\n**Outcome:** hundreds/thousands of unique combos + Rarity Score/Rank + export.\n\n**Step by step (classic tabs):**\n1. **💳 Credits** — connect your wallet. High volume: **Pro $29.99 = 1000 cr** or your own OpenAI key in the sidebar (Classic Images).\n2. **🛠️ Constructor** — idea, style, camera, lighting. Sidebar template → «Apply».\n3. **🧬 Traits** — categories (Head, Eyes, Background…), rarity weights, rarity sliders. Review combinations.\n4. **📦 Batch** — test **10–20** prompts (text quality before the full run).\n5. **🏭 Collection** — full prompt generation (50–10,000). Checkpoint + resume.\n6. **⑤ Quick preview** — 1–4 images to test a prompt (**OpenAI key** + on ai.w3ir.io also **4 cr/frame**; not a mint-ready drop) **or** «→ To Pipeline» → Stage 2 (credits, curator, export).\n7. **Export** — ZIP/IPFS, provenance, rarity report.\n\n**Classic vs Pipeline:** 50+ traits-heavy → Classic; 25–100 without a complex matrix → faster via **Pipeline → Matrix**; brand/community 25 → **Brand Icon System** template (help § 4.1.2).\n**Tip:** sidebar → «Switch to Pipeline» for the recommended path.\n\n⏱ **hours** (depends on supply)'},
    'welcome.dismiss': {'uk': 'Пропустити — я розберуся сам', 'en': "Skip — I'll explore myself"},
    'welcome.continue': {'uk': '▶️ Продовжити останній проєкт', 'en': '▶️ Continue last project'},
    'welcome.continue_hint': {'uk': 'У вас уже є збережений дроп — можна продовжити з того місця, де зупинились.', 'en': 'You already have a saved drop — pick up where you left off.'},
    'welcome.new_drop_caption': {'uk': 'Або почніть **новий** дроп (створиться окремий проєкт):', 'en': 'Or start a **new** drop (creates a separate project):'},
    'welcome.archetype_row_title': {'uk': '#### Інші міні-дропи (~25)', 'en': '#### More mini-drops (~25)'},
    'welcome.landscape': {'uk': '🌄 Пейзаж 25', 'en': '🌄 Landscape 25'},
    'welcome.landscape_desc': {'uk': 'Atmospheric Worlds · 16:9 · сцена × настрій', 'en': 'Atmospheric Worlds · 16:9 · scene × mood'},
    'welcome.event': {'uk': '🎫 Івент-бейдж 25', 'en': '🎫 Event badge 25'},
    'welcome.event_desc': {'uk': 'Event Badge Series · tier × подача', 'en': 'Event Badge Series · tier × style'},
    'welcome.brand': {'uk': '🏷️ Бренд-іконки 25', 'en': '🏷️ Brand icons 25'},
    'welcome.brand_desc': {'uk': 'Brand Icon System · знак × фон', 'en': 'Brand Icon System · mark × background'},
    'welcome.landscape_guide': {'uk': '**Для кого:** міні-дроп **25 пейзажів** — обкладинки, atmospheric art, без людей у кадрі.\n\n**Шаблон:** *Atmospheric Worlds* (5 сцен × 5 настроїв). Aspect за замовч. **16:9**.\n\n**Крок за кроком:**\n1. **💳 Кредити** — ~25–50 cr (Flux) + запас на regenerate.\n2. **1️⃣ Текст** — шаблон застосовано → **Матриця** → 25 промптів. Підправ **ідею** EN (`alpine fantasy coast`). Style Bible: `no people, no characters`.\n3. **2️⃣ Зображення** — **Flux** або **Stability**; Style lock → **Landscape**. Pilot 8–10 → куратор ≥4★ → повний run.\n4. **3️⃣ Експорт** — ZIP; traits EN: `Scene`, `Mood / Lighting`.\n\n📖 Повний гайд: Довідка **§ 4.1.3** і **§ 4.1.8**.\n\n⏱ **~25–40 хв**', 'en': '**For whom:** a **25-frame landscape** mini-drop — covers, atmospheric worlds, no people.\n\n**Template:** *Atmospheric Worlds* (5 scenes × 5 moods). Default aspect **16:9**.\n\n**Step by step:**\n1. **💳 Credits** — ~25–50 cr (Flux) + headroom for regenerates.\n2. **1️⃣ Text** — template applied → **Matrix** → 25 prompts. Tweak **idea** in EN (`alpine fantasy coast`). Style Bible: `no people, no characters`.\n3. **2️⃣ Images** — **Flux** or **Stability**; Style lock → **Landscape**. Pilot 8–10 → curator ≥4★ → full run.\n4. **3️⃣ Export** — ZIP; EN traits: `Scene`, `Mood / Lighting`.\n\n📖 Full guide: Help **§ 4.1.3** and **§ 4.1.8**.\n\n⏱ **~25–40 min**'},
    'welcome.event_guide': {'uk': '**Для кого:** **25 івент-бейджів** — конференція, DAO-сезон, POAP-стиль (tier = рідкість).\n\n**Шаблон:** *Event Badge Series* (5 tier × 5 подач).\n\n**Крок за кроком:**\n1. **💳 Кредити** — ~25–100 cr (GPT Image = 4 cr/кадр).\n2. **1️⃣ Текст** — **ідея** EN без дат у промпті: `neon summit badge, no readable text`. Дати й назва події — у **metadata** на експорті.\n3. **2️⃣ Зображення** — **GPT Image**; Style lock → **Event badge**. Pilot → куратор ≥4★.\n4. **3️⃣ Експорт** — `name`: `Your Event #12`; attributes `Tier`, `Visual Style`.\n\n📖 Повний гайд: **§ 4.1.4** і **§ 4.1.8**. Альтернатива: **🏛️ Art Deco Medallions**.\n\n⏱ **~30–45 хв**', 'en': '**For whom:** **25 event badges** — conference, DAO season, POAP-style (tier = rarity).\n\n**Template:** *Event Badge Series* (5 tiers × 5 visual styles).\n\n**Step by step:**\n1. **💳 Credits** — ~25–100 cr (GPT Image = 4 cr/frame).\n2. **1️⃣ Text** — **idea** in EN without dates in the prompt: `neon summit badge, no readable text`. Event name and dates go in **export metadata**.\n3. **2️⃣ Images** — **GPT Image**; Style lock → **Event badge**. Pilot → curator ≥4★.\n4. **3️⃣ Export** — `name`: `Your Event #12`; attributes `Tier`, `Visual Style`.\n\n📖 Full guide: **§ 4.1.4** and **§ 4.1.8**. Alternative: **🏛️ Art Deco Medallions**.\n\n⏱ **~30–45 min**'},
    'welcome.brand_guide': {'uk': '**Для кого:** **25 бренд-іконок** — один знак/маскот у різних фонах і подачах.\n\n**Шаблон:** *Brand Icon System* (подача × фон). Це **текст → зображення**, не upload лого.\n\n**Крок за кроком:**\n1. **💳 Кредити** — ~100 cr якщо GPT на всі 25 (+ regenerate).\n2. **1️⃣ Текст** — замініть **ідею** EN: `minimal geometric owl mark, navy and gold, no text`. Style Bible: `no watermark, no extra logos`.\n3. **2️⃣ Зображення** — **GPT Image** (чіткі flat-форми); Style lock → **Brand mark**. Pilot 5–10 → куратор.\n4. **3️⃣ Експорт** — preflight; EN description колекції.\n\n📖 Повний гайд: **§ 4.1.2** і **§ 4.1.8**.\n\n⏱ **~30–45 хв**', 'en': '**For whom:** **25 brand icons** — one mark/mascot in many backgrounds and layouts.\n\n**Template:** *Brand Icon System* (layout × background). This is **text → image**, not logo upload.\n\n**Step by step:**\n1. **💳 Credits** — ~100 cr if GPT for all 25 (+ regenerates).\n2. **1️⃣ Text** — replace **idea** in EN: `minimal geometric owl mark, navy and gold, no text`. Style Bible: `no watermark, no extra logos`.\n3. **2️⃣ Images** — **GPT Image** (crisp flat shapes); Style lock → **Brand mark**. Pilot 5–10 → curator.\n4. **3️⃣ Export** — preflight; English collection description.\n\n📖 Full guide: **§ 4.1.2** and **§ 4.1.8**.\n\n⏱ **~30–45 min**'},
    'welcome.more_mini_title': {'uk': '#### Ще міні-дропи (~25)', 'en': '#### More mini-drops (~25)'},
    'welcome.more_mini_caption': {'uk': 'Оберіть шаблон — покроковий гайд зʼявиться в sidebar і на Етапі 1. Повний каталог: **Довідка § 4.1.8**.', 'en': 'Pick a template — step-by-step guide appears in the sidebar and Stage 1. Full catalog: **Help § 4.1.8**.'},
    'welcome.glitch': {'uk': '📺 Glitch 25', 'en': '📺 Glitch 25'},
    'welcome.glitch_desc': {'uk': 'Glitch Geometry · форма × поле', 'en': 'Glitch Geometry · form × field'},
    'welcome.glitch_guide': {'uk': '**Для кого:** crypto-native **абстракт** з RGB-split / datamosh.\n\n**Шаблон:** *Glitch Geometry* (5×5). Style lock → **Geometric**.\n\n**Кроки:** 💳 ~25–50 cr → **Матриця** 25 → **Stability/Flux** Pilot → куратор ≥4★ → Export.\n**Ідея:** `corrupted sacred geometry, RGB split, no readable text`.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 хв**', 'en': '**For whom:** crypto-native **glitch abstract** with RGB-split / datamosh.\n\n**Template:** *Glitch Geometry* (5×5). Style lock → **Geometric**.\n\n**Steps:** 💳 ~25–50 cr → **Matrix** 25 → **Stability/Flux** Pilot → curator ≥4★ → Export.\n**Idea:** `corrupted sacred geometry, RGB split, no readable text`.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 min**'},
    'welcome.sumie': {'uk': '🖋️ Sumi-e 25', 'en': '🖋️ Sumi-e 25'},
    'welcome.sumie_desc': {'uk': 'Ink Studies · мотив × настрій', 'en': 'Ink Studies · motif × mood'},
    'welcome.sumie_guide': {'uk': '**Для кого:** **монохромна туш** — zen fine-art без PFP.\n\n**Шаблон:** *Sumi-e Ink Studies* (5×5). Style lock → **Fine art**.\n\n**Кроки:** 💳 ~25 cr → **Stability AI** → Pilot → Export; traits `Form`, `Background`.\n\n📖 **§ 4.1.5** + **§ 4.1.8** · ⏱ **~25–40 хв**', 'en': '**For whom:** **monochrome ink** — zen fine art, no PFP.\n\n**Template:** *Sumi-e Ink Studies* (5×5). Style lock → **Fine art**.\n\n**Steps:** 💳 ~25 cr → **Stability AI** → Pilot → Export; traits `Form`, `Background`.\n\n📖 **§ 4.1.5** + **§ 4.1.8** · ⏱ **~25–40 min**'},
    'welcome.chibi': {'uk': '🍡 Chibi 25', 'en': '🍡 Chibi 25'},
    'welcome.chibi_desc': {'uk': 'Chibi Champs · kawaii PFP', 'en': 'Chibi Champs · kawaii PFP'},
    'welcome.chibi_guide': {'uk': '**Для кого:** **kawaii / SD** PFP — велика голова, жирний контур.\n\n**Шаблон:** *Chibi Champs* (голова × одяг). Style lock → **Portrait / PFP**.\n\n**Кроки:** 💳 ~25–50 cr → **ідея** скваду EN → Flux/Stability Pilot 10 → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 хв**', 'en': '**For whom:** **kawaii / SD** PFP — oversized head, bold outlines.\n\n**Template:** *Chibi Champs* (head × outfit). Style lock → **Portrait / PFP**.\n\n**Steps:** 💳 ~25–50 cr → squad **idea** in EN → Flux/Stability Pilot 10 → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 min**'},
    'welcome.vinyl': {'uk': '🧸 Vinyl 25', 'en': '🧸 Vinyl 25'},
    'welcome.vinyl_desc': {'uk': 'Vinyl Toy Squad · designer toy', 'en': 'Vinyl Toy Squad · designer toy'},
    'welcome.vinyl_guide': {'uk': '**Для кого:** **designer vinyl toy** PFP — глянцевий пластик.\n\n**Шаблон:** *Vinyl Toy Squad*. Style lock → **PFP**. **Stability AI** → Pilot → Export.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 хв**', 'en': '**For whom:** **designer vinyl toy** PFP — glossy plastic.\n\n**Template:** *Vinyl Toy Squad*. Style lock → **PFP**. **Stability AI** → Pilot → Export.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 min**'},
    'welcome.retro': {'uk': '🛸 Ретро 25', 'en': '🛸 Retro 25'},
    'welcome.retro_desc': {'uk': 'Retro Poster · сцена × палітра', 'en': 'Retro Poster · scene × palette'},
    'welcome.retro_guide': {'uk': '**Для кого:** **ретро space-age постери** без персонажів.\n\n**Шаблон:** *Retro Poster Series*. Style lock → **Landscape**. Stability/Flux → Export.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 хв**', 'en': '**For whom:** **vintage space-age posters** without characters.\n\n**Template:** *Retro Poster Series*. Style lock → **Landscape**. Stability/Flux → Export.\n\n📖 **§ 4.1.8** · ⏱ **~25–40 min**'},
    'welcome.chrome': {'uk': '✨ Chrome 25', 'en': '✨ Chrome 25'},
    'welcome.chrome_desc': {'uk': 'Chrome Fashion · editorial PFP', 'en': 'Chrome Fashion · editorial PFP'},
    'welcome.chrome_guide': {'uk': '**Для кого:** **editorial fashion** PFP — хром, подіум.\n\n**Шаблон:** *Chrome Fashion Icons*. Flux/GPT → Pilot → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 хв**', 'en': '**For whom:** **editorial fashion** PFP — chrome, runway.\n\n**Template:** *Chrome Fashion Icons*. Flux/GPT → Pilot → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 min**'},
    'welcome.artdeco': {'uk': '🏛️ Art Deco 25', 'en': '🏛️ Art Deco 25'},
    'welcome.artdeco_desc': {'uk': 'Art Deco Medallions · tier × орнамент', 'en': 'Art Deco Medallions · tier × ornament'},
    'welcome.artdeco_guide': {'uk': '**Для кого:** **преміум-медальйони** Art Deco.\n\n**Шаблон:** *Art Deco Medallions*. GPT Image → Style lock **Event badge** → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 хв**', 'en': '**For whom:** **premium Art Deco** medallions.\n\n**Template:** *Art Deco Medallions*. GPT Image → Style lock **Event badge** → Export.\n\n📖 **§ 4.1.8** · ⏱ **~30–45 min**'},
    'welcome.lineart_guide': {'uk': '**Для кого:** **лінійна система знаків** — 25 монограм однієї товщини штриха.\n\n**Шаблон:** *Line Art Monograms* (мотив × поле). Style lock → **Brand mark**.\n\n**Кроки:** 💳 ~25 cr → замініть **мотив** EN: `interlocking leaf monogram, no text` → **GPT Image** (найчистіша лінія) Pilot 5 → куратор → Export.\n\n**Чим тримається серія:** незмінна товщина штриха й оптичний розмір — не міняйте їх між айтемами.\n\n📖 **§ 4.1.2** · ⏱ **~25–40 хв**', 'en': '**For whom:** **a linear sign system** — 25 monograms of one stroke weight.\n\n**Template:** *Line Art Monograms* (motif × field). Style lock → **Brand mark**.\n\n**Steps:** 💳 ~25 cr → replace the **motif** in EN: `interlocking leaf monogram, no text` → **GPT Image** (cleanest line) Pilot 5 → curator → Export.\n\n**What holds the series together:** constant stroke weight and optical size — keep them identical across items.\n\n📖 **§ 4.1.2** · ⏱ **~25–40 min**'},
    'welcome.showcase_guide': {'uk': '**Admin / staging:** *W3IR Showcase Demo* — 25 cyber PFP.\n\nПублічним користувачам — шаблони з **§ 4.1.8**.', 'en': '**Admin / staging:** *W3IR Showcase Demo* — 25 cyber PFP.\n\nPublic users — templates from **§ 4.1.8**.'},
    'sidebar.settings': {'uk': '### ⚙️ Налаштування', 'en': '### ⚙️ Settings'},
    'sidebar.ai_settings': {'uk': '🤖 AI та ключі', 'en': '🤖 AI & keys'},
    'sidebar.generation_opts': {'uk': '⚙️ Параметри генерації', 'en': '⚙️ Generation options'},
    'sidebar.classic_config_export': {'uk': '📄 Експорт конфігу конструктора (JSON)', 'en': '📄 Constructor config export (JSON)'},
    'sidebar.classic_config_hint': {'uk': 'Опційно: зберегти лише поля конструктора (idea, traits) у файл. Не замінює autosave проєкту зверху.', 'en': 'Optional: save constructor fields only (idea, traits) to a file. Does not replace project autosave above.'},
    'sidebar.config_snapshot_name': {'uk': 'Назва файлу', 'en': 'File name'},
    'sidebar.save_config_snapshot': {'uk': '💾 Зберегти JSON', 'en': '💾 Save JSON'},
    'sidebar.saved_config_snapshots': {'uk': 'Збережені файли', 'en': 'Saved files'},
    'sidebar.load_config_snapshot': {'uk': '📂 Завантажити', 'en': '📂 Load'},
    'sidebar.delete_config_snapshot': {'uk': '🗑️ Видалити', 'en': '🗑️ Delete'},
    'sidebar.config_snapshot_saved': {'uk': 'Збережено: {path}', 'en': 'Saved: {path}'},
    'sidebar.config_snapshot_name_required': {'uk': 'Вкажіть назву файлу.', 'en': 'Enter a file name.'},
    'sidebar.openai_key': {'uk': 'OpenAI API Key', 'en': 'OpenAI API Key'},
    'sidebar.openai_key_help': {'uk': 'Потрібен для GPT-моделей і вкладки **⑤ Швидке превʼю** / масових images у **④ Колекція**. На ai.w3ir.io превʼю також списує **кредити платформи** (окремо від рахунку OpenAI).', 'en': 'Required for GPT models and **⑤ Quick preview** / bulk images in **④ Collection**. On ai.w3ir.io preview also charges **platform credits** (separate from your OpenAI bill).'},
    'sidebar.anthropic_key': {'uk': 'Anthropic API Key', 'en': 'Anthropic API Key'},
    'sidebar.llm_model': {'uk': 'Модель для промптів', 'en': 'Prompt model'},
    'sidebar.prompt_model_help': {'uk': 'Який ШІ пише **текст** промптів на вкладках Конструктор, Batch і Колекція (classic). Не впливає на зображення (Етап 2) і не на polish / archetypes / image-to-prompt у Конвеєрі.', 'en': 'Which AI writes **prompt text** on Builder, Batch and Collection tabs (classic). Does not affect images (Stage 2) or polish / archetypes / image-to-prompt in the Pipeline.'},
    'sidebar.prompt_model_caption': {'uk': 'Дешевші моделі економніші на рахунку OpenAI/Anthropic; кредити платформи — 1 cr за запит для будь-якої моделі.', 'en': 'Cheaper models save on your OpenAI/Anthropic bill; platform credits are 1 cr per request for any model.'},
    'sidebar.pipeline_llm_fixed': {'uk': 'У **Конвеєрі** текстові моделі (polish, archetypes, image-to-prompt) обираються автоматично. Двигун зображень — на **Етапі 2**.', 'en': 'In **Pipeline**, text models (polish, archetypes, image-to-prompt) are picked automatically. Image engine — on **Stage 2**.'},
    'sidebar.platform': {'uk': 'Цільова платформа', 'en': 'Target platform'},
    'sidebar.creativity': {'uk': 'Креативність', 'en': 'Creativity'},
    'sidebar.images_openai': {'uk': 'ℹ️ Зображення (gpt-image-1) завжди через OpenAI.', 'en': 'ℹ️ Images (gpt-image-1) always use OpenAI.'},
    'sidebar.templates': {'uk': '#### 📋 Шаблони колекцій', 'en': '#### 📋 Collection templates'},
    'sidebar.templates_supply_hint': {'uk': 'Мітки: **1k+ / 10k+** — великий дроп через Classic → **Колекція**; **~N міні** — швидкий дроп у Конвеєрі.', 'en': 'Labels: **1k+ / 10k+** — large drops via Classic → **Collection**; **~N mini** — quick Pipeline drops.'},
    'sidebar.template_badge_mini': {'uk': '~{short} міні', 'en': '~{short} mini'},
    'sidebar.template_guide_label': {'uk': '📋 Гайд міні-дропу', 'en': '📋 Mini-drop guide'},
    'sidebar.template_guide_help_hint': {'uk': 'Повний каталог усіх шаблонів ~25: вкладка **📖 Довідка** → секція **4. Конвеєр** → **§ 4.1.8**.', 'en': 'Full catalog of all ~25 templates: **📖 Help** tab → section **4. Pipeline** → **§ 4.1.8**.'},
    'sidebar.template_badge_large': {'uk': '{short} · Classic Колекція', 'en': '{short} · Classic Collection'},
    'sidebar.pick_template': {'uk': 'Змінити шаблон', 'en': 'Switch template'},
    'sidebar.no_template': {'uk': '— без шаблону —', 'en': '— no template —'},
    'sidebar.apply_template': {'uk': '✅ Застосувати шаблон', 'en': '✅ Apply template'},
    'sidebar.active_template': {'uk': 'Активний: {label}', 'en': 'Active: {label}'},
    'sidebar.projects': {'uk': '### 💾 Проєкти', 'en': '### 💾 Projects'},
    'sidebar.project_name': {'uk': 'Назва проєкту', 'en': 'Project name'},
    'sidebar.save_project': {'uk': '💾 Зберегти проєкт', 'en': '💾 Save project'},
    'sidebar.saved_projects': {'uk': 'Збережені проєкти', 'en': 'Saved projects'},
    'sidebar.load_project': {'uk': '📂 Завантажити', 'en': '📂 Load'},
    'sidebar.delete_project': {'uk': '🗑️ Видалити', 'en': '🗑️ Delete'},
    'sidebar.constructor_opts': {'uk': 'Нижче — лише для одиночної генерації на вкладці «Конструктор».', 'en': 'Below — single-prompt generation on the Builder tab only.'},
    'sidebar.gen_traits': {'uk': 'Генерувати таблицю Traits', 'en': 'Generate Traits table'},
    'sidebar.negative_prompt': {'uk': 'Додати Negative Prompt', 'en': 'Add Negative Prompt'},
    'sidebar.collection_size': {'uk': 'Розмір колекції (шт.)', 'en': 'Collection size'},
    'sidebar.collection_size_pipeline': {'uk': 'Supply сценарію: **{n}** NFT (змінюється шаблоном welcome або Етапом 1)', 'en': 'Scenario supply: **{n}** NFTs (set by welcome template or Stage 1)'},
    'sidebar.api_ok': {'uk': 'API підключено', 'en': 'API connected'},
    'sidebar.api_missing': {'uk': 'API ключ не знайдено', 'en': 'API key not found'},
    'sidebar.anthropic_ok': {'uk': 'Anthropic API підключено', 'en': 'Anthropic API connected'},
    'sidebar.anthropic_missing': {'uk': 'Anthropic API Key не знайдено', 'en': 'Anthropic API key not found'},
    'sidebar.openai_for_images': {'uk': '⚠️ OpenAI Key потрібен для **⑤ Швидке превʼю** і images у **④ Колекція**.', 'en': '⚠️ OpenAI key required for **⑤ Quick preview** and images in **④ Collection**.'},
    'sidebar.session_cost': {'uk': '💸 Витрачено за сесію', 'en': '💸 Spent this session'},
    'sidebar.session_cost_hint': {'uk': 'Орієнтовні витрати **вашого API-ключа** (USD), класичний режим.', 'en': 'Estimated **your API key** spend (USD), classic mode only.'},
    'sidebar.session_credits': {'uk': '💳 Списано за сесію', 'en': '💳 Charged this session'},
    'sidebar.session_credits_hint': {'uk': 'Кредити W3IR у класичному режимі (LLM + превʼю зображень).', 'en': 'W3IR credits in classic mode (LLM + image previews).'},
    'sidebar.reset_cost': {'uk': '↺ Скинути лічильник', 'en': '↺ Reset counter'},
    'sidebar.credits': {'uk': '💳 Баланс кредитів', 'en': '💳 Credit balance'},
    'sidebar.connected_wallet': {'uk': 'Підключено · `{short}`', 'en': 'Connected · `{short}`'},
    'sidebar.copy_wallet': {'uk': 'Копіювати адресу', 'en': 'Copy address'},
    'sidebar.topup': {'uk': '➕ Поповнити кредити', 'en': '➕ Top up credits'},
    'sidebar.topup_full': {'uk': 'Повна панель — вкладка «Конвеєр» → 💳 Кредити', 'en': 'Full panel — “Pipeline” tab → 💳 Credits'},
    'tab.builder': {'uk': '① Конструктор', 'en': '① Builder'},
    'tab.traits': {'uk': '② Traits', 'en': '② Traits'},
    'tab.batch': {'uk': '③ Batch', 'en': '③ Batch'},
    'tab.collection': {'uk': '④ Колекція', 'en': '④ Collection'},
    'tab.images': {'uk': '⑤ Швидке превʼю', 'en': '⑤ Quick preview'},
    'tab.pipeline': {'uk': 'Конвеєр', 'en': 'Pipeline'},
    'tab.history': {'uk': 'Історія', 'en': 'History'},
    'tab.help': {'uk': 'Довідка', 'en': 'Help'},
    'tab.admin': {'uk': 'Адмін', 'en': 'Admin'},
    'nav.help_this_step': {'uk': '📖 Довідка: цей крок', 'en': '📖 Help: this step'},
    'nav.help_open_tab': {'uk': 'Відкрийте вкладку **📖 Довідка** зверху — потрібна секція буде розгорнута.', 'en': 'Open the **📖 Help** tab above — the relevant section will be expanded.'},
    'nav.help_all_mini_drops': {'uk': '📖 Усі гайди міні-дропів (§ 4.1.8)', 'en': '📖 All mini-drop guides (§ 4.1.8)'},
    'nav.choose_direction': {'uk': '🏠 Обрати напрям', 'en': '🏠 Choose your path'},
    'nav.choose_direction_help': {'uk': 'Повернутися на екран вибору: 1 NFT, міні-дроп 25 або розширений режим', 'en': 'Return to the start screen: 1 NFT, mini-drop 25, or advanced mode'},
    'error.blocked_prompt': {'uk': '🚫 Промпт відхилено модерацією контенту: недопустимий запит.', 'en': '🚫 Prompt rejected by content moderation: disallowed request.'},
    'creative.styles_catalog': {'uk': '📖 Каталог стилів (опис і варіативність)', 'en': '📖 Style catalog (descriptions & variety)'},
    'creative.style_notes': {'uk': 'Опис обраних стилів', 'en': 'Selected style notes'},
    'hist.title': {'uk': '📜 Історія', 'en': '📜 History'},
    'hist.search_ph': {'uk': 'Ідея, концепт, платформа…', 'en': 'Idea, concept, platform…'},
    'hist.clear_all': {'uk': '🗑️ Очистити всі', 'en': '🗑️ Clear all'},
    'hist.no_match': {'uk': 'Нічого не знайдено за вашим запитом.', 'en': 'No matches for your query.'},
    'hist.shown': {'uk': 'Показано {shown} із {total} записів.', 'en': 'Showing {shown} of {total} entries.'},
    'hist.download': {'uk': 'Завантажити', 'en': 'Download'},
    'hist.empty': {'uk': 'Історія порожня.', 'en': 'History is empty.'},
    'help.missing': {'uk': 'Файл `ДОВІДКА.md` не знайдено поруч із `app.py`.', 'en': '`ДОВІДКА.md` not found next to `app.py`.'},
    'help.download': {'uk': '📥 Завантажити довідку (.md)', 'en': '📥 Download help (.md)'},
    'gateway.opening': {'uk': '🔐 Відкриваємо вхід гаманцем…', 'en': '🔐 Opening wallet sign-in…'},
    'gateway.fallback': {'uk': 'Якщо сторінка не перейшла автоматично — натисніть кнопку нижче.', 'en': 'If the page did not redirect automatically, use the button below.'},
    'gateway.connect': {'uk': 'Підключити гаманець →', 'en': 'Connect Wallet →'},
    'footer.caption': {'uk': 'NFT Prompt Builder v4.3 · Rarity · Metadata · Зображення · OpenAI + Claude', 'en': 'NFT Prompt Builder v4.3 · Rarity · Metadata · Images · OpenAI + Claude'},
    'footer.legal': {'uk': 'Умови · Privacy · Refund', 'en': 'Terms · Privacy · Refund'},
    'sidebar.project_saved': {'uk': 'Збережено: {path}', 'en': 'Saved: {path}'},
    'sidebar.project_name_required': {'uk': 'Вкажіть назву проєкту.', 'en': 'Enter a project name.'},
}
